### ISSUE TITLE
Ground height map bug? Karthwasten

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#100]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Newest Beta Release

**Describe the bug**
A lot of ground issues throughout Karthwasten screenshots show it better than I can describe.

**To Reproduce**
Walk into Karthwasten a look around at the ground throughout. 

**Expected behavior**
No Height Map bugs

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods added
![20200603174523_1](https://user-images.githubusercontent.com/62521502/83703059-4864e900-a5c3-11ea-9011-cc37582b1ca0.jpg)
![20200603174531_1](https://user-images.githubusercontent.com/62521502/83703083-574b9b80-a5c3-11ea-96eb-bc4c43d5a1dc.jpg)
![20200603174552_1](https://user-images.githubusercontent.com/62521502/83703089-5f0b4000-a5c3-11ea-9958-b745090d15c2.jpg)
![20200603174555_1](https://user-images.githubusercontent.com/62521502/83703093-60d50380-a5c3-11ea-8b8d-34abf8d52662.jpg)
![20200603174613_1](https://user-images.githubusercontent.com/62521502/83703097-616d9a00-a5c3-11ea-9f45-cf50e820184a.jpg)
![20200603174614_1](https://user-images.githubusercontent.com/62521502/83703098-62063080-a5c3-11ea-8699-bb249795fbf4.jpg)
![20200603174626_1](https://user-images.githubusercontent.com/62521502/83703100-63375d80-a5c3-11ea-9bb5-f2635db4ecde.jpg)
![20200603174633_1](https://user-images.githubusercontent.com/62521502/83703102-63cff400-a5c3-11ea-8ce7-b705767d56c3.jpg)
![20200603174647_1](https://user-images.githubusercontent.com/62521502/83703105-64688a80-a5c3-11ea-8ac6-f376f3861af4.jpg)
![20200603174651_1](https://user-images.githubusercontent.com/62521502/83703107-65012100-a5c3-11ea-8cca-077f158a286b.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
