### ISSUE TITLE
Snow mismatch outside windhelm

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#102]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
Snow mismatch at the beginning of the bridge to windhelm 
*EDIT* Also a seam around half way through near the end

. I added the screenshots after the initial ones.

**To Reproduce**
Go to windhelm and look at the snow before the bridge.

**Expected behavior**
Same colored snow.

**Screenshots**
![ScreenShot282](https://user-images.githubusercontent.com/62785432/83705663-2d05d800-a5db-11ea-9e3e-ef0c37378959.png)
![ScreenShot283](https://user-images.githubusercontent.com/62785432/83705666-2e370500-a5db-11ea-8a78-bbddf2048272.png)
![ScreenShot284](https://user-images.githubusercontent.com/62785432/83705668-2ecf9b80-a5db-11ea-872a-85f71087c169.png)
![ScreenShot285](https://user-images.githubusercontent.com/62785432/83705669-2f683200-a5db-11ea-92c7-ab60b4e7bd3e.png)
![ScreenShot280](https://user-images.githubusercontent.com/62785432/83705670-30995f00-a5db-11ea-8053-e5de2abe48cc.png)
![ScreenShot281](https://user-images.githubusercontent.com/62785432/83705672-32632280-a5db-11ea-9918-78d8670ac681.png)
![ScreenShot289](https://user-images.githubusercontent.com/62785432/83705891-bd441d00-a5db-11ea-88cf-e08d4ded0943.png)
![ScreenShot288](https://user-images.githubusercontent.com/62785432/83705894-be754a00-a5db-11ea-9d07-b0c0e53d9be5.png)
![ScreenShot287](https://user-images.githubusercontent.com/62785432/83705919-d220b080-a5db-11ea-80c9-824afb104f35.png)
![ScreenShot290](https://user-images.githubusercontent.com/62785432/83706097-3a6f9200-a5dc-11ea-8d50-1aff57fb4ec1.png)
![ScreenShot291](https://user-images.githubusercontent.com/62785432/83706102-3ba0bf00-a5dc-11ea-9119-662ac85d2057.png)

**Additional context**
These are all on the windhelm bridge.(just to clarify)

**Comment by ForgottenGlory** [comment]
Windhelm in general, and its bridge, are known to be nightmares when it comes to retextures and such. I've modified the most egregious seam to make it smaller but the texture mismatch still happens. I don't have the skills to fix it further.
