### ISSUE TITLE
Black Face Bug Ulfric Stormcloak

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#103]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
Black Face Bug Ulfric Stormcloak

**To Reproduce**
Look at ulfric

**Expected behavior**
No black face bug

**Screenshots**
![ScreenShot300](https://user-images.githubusercontent.com/62785432/83706854-2a58b200-a5de-11ea-8bc4-4c4b4e43c7f3.png)
![ScreenShot299](https://user-images.githubusercontent.com/62785432/83706856-2c227580-a5de-11ea-8333-0bd67d7724cb.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
