### ISSUE TITLE
Black Face bug galmar stone-fist and he's not wearing armor

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#104]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
Black Face bug galmar stone-fist and he's not wearing armor (but hes not nude.)

**To Reproduce**
Walk into palace of kings and look at galmar.

**Expected behavior**
no black face and should be wearing clothes

**Screenshots**
![ScreenShot301](https://user-images.githubusercontent.com/62785432/83707166-f92cb180-a5de-11ea-9b20-302e4fb283b1.png)
![ScreenShot302](https://user-images.githubusercontent.com/62785432/83707171-fb8f0b80-a5de-11ea-9c78-c88e8e30007b.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
