### ISSUE TITLE
Small Seam in the Road

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#105]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Newest Beta Release

**Describe the bug**
Small Seam in the road

**To Reproduce**
Walk along the road leaving Karthwasten towards Morthal

**Expected behavior**
No Seam

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods Added
![20200603180508_1](https://user-images.githubusercontent.com/62521502/83712466-bc5ebb80-a5da-11ea-8c78-dcb4dba61a9f.jpg)
![20200603180507_1](https://user-images.githubusercontent.com/62521502/83712467-bd8fe880-a5da-11ea-92ba-843490c2c2c7.jpg)

**Comment by daffodilian** [comment]
Would you mind going back to that spot, opening the DynDOLOD MCM, and taking a screenshot of the "You are here!" section?

**Comment by tHiNgXX9** [comment]
![20200603224806_1](https://user-images.githubusercontent.com/62521502/83719873-ddc8a300-a5ec-11ea-999f-e012a7a4a9e9.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
