### ISSUE TITLE
Small Clipping Pine tree near Dragonsbridge Camp

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#106]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Newest Beta Release

**Describe the bug**
A small Clipping Pine tree near in Dragonbridge Camp

**To Reproduce**
Arrive at the small fortified camps near Dragonsbridge and check near the Imperial tents

**Expected behavior**
No Clipping Pine tree

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods Added
![20200603182519_1](https://user-images.githubusercontent.com/62521502/83712691-2bd4ab00-a5db-11ea-95fb-ba0d1fab72ca.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
