### ISSUE TITLE
Improved Camera

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#109]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

[Alduin Save(Save 175).zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4727645/Alduin.Save.Save.175.zip) 
This save was made in beta 1

**Mod Name**
Improved Camera

**Mod Link**
https://www.reddit.com/r/skyrimmods/comments/cae3x2/mod_improved_camera_beta_3/ <--- that is the post about it for info

https://drive.google.com/file/d/12hqOZbfeFK0zXJxpzsEXsyQyDclDQaZk/view <--- this is the download link provided

**Why?**
It adds another level of immersion (i will admit the "level" is small) by being able to view your body in 1st person. I don't really have anything else to say other than I've had it work pretty well on personal lists I have made without personally experiencing any of the known issues EXCEPT a weird problem with 360 walk and run animations. Although I do know there can be some hefty conflicts with other mods.

**Additional context**
It hasn't been updated in quite a long time(i think nearing a year) and there are a few known issues. Thought I'd still post this as I feel it *might* be a nice addition to the list :)
Thanks for considering

**Comment by daffodilian** [comment]
This version of a camera mod is the best for SSE in my opinion, but still nowhere as polished as the one from LE. There are a couple bugs that can be hard to get over, but they are rare in my experience and are fixed by a restart of skyrim.
[These tweaks](https://www.nexusmods.com/skyrimspecialedition/mods/31805?tab=files) seem like they would help. 
I'd support adding this as it is just an skse plugin. Possibly having it disabled by default like The widescreen fixes

**Comment by ForgottenGlory** [comment]
So... playing around with this mod a bit, it is very disorienting to play with for me, but it has some interesting features. I may include this but make it optional.

**Comment by TwistedModding** [comment]
I would also suggest using the tweaks that daffodilian linked in his comment. They fix a couple minor issues that are annoying such as clipping, no inertia, and head bobbing

**Comment by daffodilian** [comment]
Just recently brought this into LS again. Something isn't playing nicely, I had quite a few crashes all pointing to improvedcamera.dll, along with some weird bugs when switching to 3rd person.  I'm going to withdraw my suggestion of this.
