### ISSUE TITLE
Small Seam in the Rift

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#110]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Newest Beta Release
**Describe the bug**
A small Seam in the road near Ivarstead
**To Reproduce**
Walk north down the road from Ivarstead
**Expected behavior**
No Seam
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods Added
![20200603221652_1](https://user-images.githubusercontent.com/62521502/83718530-12872b00-a5ea-11ea-8280-befbb3cfca0c.jpg)
![20200603221654_1](https://user-images.githubusercontent.com/62521502/83718535-15821b80-a5ea-11ea-9b09-f20fad19c2d4.jpg)

**Comment by tHiNgXX9** [comment]
![20200603225018_1](https://user-images.githubusercontent.com/62521502/83719907-eb7e2880-a5ec-11ea-910b-cca8dbe23095.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
