### ISSUE TITLE
Derkeethus appearance bug

### ISSUE THREAD

**Issue by CentralSmith** [ForgottenGlory/Living-Skyrim-2#113]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 2

**Describe the bug**
Derkeethus's head does not match the rest of his body, and his eyes appear to pop out of his face as if set for a different physical model's skull.

**To Reproduce**
Find (or spawn) Derkeethus

**Expected behavior**
Either an altered or original appearance that matches.

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83778737-b9061700-a650-11ea-8d45-97f687885357.png)

**Additional context**
N/A

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
