### ISSUE TITLE
Active Effect showing Familiar scales with level not working

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#114]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 2

**Describe the bug**
Active effect show that familiar should scale with player's level, doesn't seem to show any scaling

**To Reproduce**

**Expected behavior**
Familiar should become stronger?

**Screenshots**
First screenshot is level 6 character.
![ScreenShot221](https://user-images.githubusercontent.com/13601605/83780009-7983fe80-a641-11ea-9d3e-e030f018b81b.png)
New character below.
![ScreenShot222](https://user-images.githubusercontent.com/13601605/83780018-7b4dc200-a641-11ea-871b-96de53105278.png)
![ScreenShot223](https://user-images.githubusercontent.com/13601605/83780023-7d178580-a641-11ea-8571-85d7def44385.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Does the lack of scaling persist if you dismiss the familiar and resummon it? Most likely the familiar's level is only calculated when you cast the spell, it likely won't update dynamically.

**Comment by Konsetsuki** [comment]
Due to the fact that the familiar doesn't follow you in caves and dungeons, I do periodically resummon, even with a dispel in restoration and to resummon they still remain level 2 with similar stats for hp/mp/st. I have been progressing with the brand new character that I revealed in the screenshot, at character level 14 and 40+ points in conjuration, they remain level 2 with minimal stats.
![ScreenShot226](https://user-images.githubusercontent.com/13601605/83936397-32e4f000-a778-11ea-8f27-884a966dcbf7.png)

**Comment by Fjodik** [comment]
Hmm, maybe I am wrong but Summon Familiar is a vanilla spell, right? I have checked the wiki and the familiar does not seem to scale with your level, so it has to be connected with SkyRem Rae race feature of Breton (connected soul ability). Maybe SkyTest overwrites something here?

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
