### ISSUE TITLE
Rorikstead: 3 random chimneys/ 2 floating Lanterns 

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#115]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.
Newest Beta Release
**Describe the bug**
3 random chimneys coming out of the ground not connected to any building/ 2 floating Lanterns 
**To Reproduce**
Walk into Rorikstead and see chimneys and lanterns misplaced
**Expected behavior**
no random chimneys or floating lanterns
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods Added
![20200604102637_1](https://user-images.githubusercontent.com/62521502/83792425-e7cfbd80-a64f-11ea-9d19-b5ef53255b22.jpg)
![20200604102757_1](https://user-images.githubusercontent.com/62521502/83792433-eacaae00-a64f-11ea-926d-0c73a46311e4.jpg)
![20200604102830_1](https://user-images.githubusercontent.com/62521502/83792438-edc59e80-a64f-11ea-9ce6-1a5062f7ca7c.jpg)
![20200604102906_1](https://user-images.githubusercontent.com/62521502/83792448-f1592580-a64f-11ea-92fd-1fedd3df486b.jpg)
![20200604102908_1](https://user-images.githubusercontent.com/62521502/83792465-f4541600-a64f-11ea-988c-338d73b4c9dc.jpg)
![20200604102924_1](https://user-images.githubusercontent.com/62521502/83792480-f6b67000-a64f-11ea-9a45-423fd571b78f.jpg)

**Comment by ForgottenGlory** [comment]
Should be resolved Beta 3
