### ISSUE TITLE
Issue with Immersive Spell Learning

### ISSUE THREAD

**Issue by Fjodik** [ForgottenGlory/Living-Skyrim-2#117]
**LS Version**
LS2 Beta 1

**Describe the bug**
It seems that certain spell tomes are not caught by the mechanics of Imersive Spell Learning mod. With Conjuration skill at 1, it is possible to learn Conjure Frost and Storm Atronach within 1 hour. If required I may check all spell tomes and list them here as I am pretty sure there are much more.

**To Reproduce**
Using Add Item Menu to obtain particular spell tome

**Expected behavior**
With conjuration level of 1, it should take eternity to learn such spells

**Screenshots**

For comparison purposes attaching also Flame Atronach Spell Tome which seems to work ok

![ScreenShot215](https://user-images.githubusercontent.com/63248466/83793577-0c05bb80-a69d-11ea-9882-4d7064a52690.png)

![ScreenShot216](https://user-images.githubusercontent.com/63248466/83793563-060fda80-a69d-11ea-893a-37f14ee4c0ac.png)

![ScreenShot217](https://user-images.githubusercontent.com/63248466/83793545-ff816300-a69c-11ea-87fd-cdef65df1695.png)

**Comment by ForgottenGlory** [comment]
This is an issue I cannot fix. When you plug such a low skill level number into the formula that ISL uses, it likely overflows the limit (the exact number generated its 2.220446049250313e+35, if you care) of what the variable can handle so the game probably just defaults to a standard overflow number like 0 or 1.
