### ISSUE TITLE
Forgotten Magic: Blessed Weapon triggers Vigilant of Stendarr response

### ISSUE THREAD

**Issue by CentralSmith** [ForgottenGlory/Living-Skyrim-2#118]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 2

**Describe the bug**
Use of the 'Blessed Weapon' function seems to trigger responses by the Vigilant of Stendarr via the Reputation system, as far as I can tell.

**To Reproduce**
Utilize the Blessed Weapon spell

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83828275-e204c700-a6a5-11ea-967d-1678ba0b42dc.png)
![image](https://user-images.githubusercontent.com/1962028/83828285-e4ffb780-a6a5-11ea-8c21-cdd155a5a285.png)
![image](https://user-images.githubusercontent.com/1962028/83828317-f3e66a00-a6a5-11ea-860d-24661615aa8f.png)

**Additional context**

**Comment by daffodilian** [comment]
Even though it's described as a 'divine weapon', it's still conjuration. I see no reason to change this.

**Comment by CentralSmith** [comment]
The magic is specifically listed under the 'paladin' tree of Forgotten Magic, and for a paladin-style playthrough it does seem to not fit so well, especially so as Stendarr is against Daedra and Undead, whereas Atronach summons do not trigger this behavior in either Wintersun _or_ Reputation, but are still considered 'Conjuration'.

**Comment by Konsetsuki** [comment]
Stendarr will abandon you just for summoning a familiar I'm certain that anything that's under the conjuration tree will trigger Stendarr to abandon you.

**Comment by daffodilian** [comment]
> 
> 
> The magic is specifically listed under the 'paladin' tree of Forgotten Magic, and for a paladin-style playthrough it does seem to not fit so well, especially so as Stendarr is against Daedra and Undead, whereas Atronach summons do not trigger this behavior in either Wintersun _or_ Reputation, but are still considered 'Conjuration'.

That's a rather good point. The spell does have the Summon familiar keyword. I will play around with it, but it's ultimately not my decision if its included or not.

**Comment by CentralSmith** [comment]
I just did some testing, Konsetsuki is right - Stendarr is hilariously less tolerant than I thought he was. Even familiar and atronachs rustle his jimmies.

**Comment by daffodilian** [comment]
Atronachs are Daedra. And I think the reasoning is that summoning of any kind is too close to necromancy. But with that spell being in the Paladin path, it's worth looking at. I'll test the changes tomorrow. Closing for now, We'll see if it's included in the next update.
