### ISSUE TITLE
Seams with "You Are Here" Dyndolod

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#119]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.
Newest Beta Release
**Describe the bug**
More Random Seems on the road I found while exploring
**To Reproduce**
go to the "you are here" locations
**Expected behavior**
No seams
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods added
![20200604190945_1](https://user-images.githubusercontent.com/62521502/83831629-a6b1ca80-a69c-11ea-9643-d19e828d7b75.jpg)
![20200604190954_1](https://user-images.githubusercontent.com/62521502/83831638-aadde800-a69c-11ea-94db-b50ac799b659.jpg)
![20200604193206_1](https://user-images.githubusercontent.com/62521502/83831653-b4675000-a69c-11ea-89a3-fab66ccc9ba1.jpg)
![20200604193216_1](https://user-images.githubusercontent.com/62521502/83831657-b6c9aa00-a69c-11ea-9945-8494a423366c.jpg)

**Comment by ForgottenGlory** [comment]
Seams issues should be resolved as of Beta 3, no need to report them further.
