### ISSUE TITLE
Disable Follower Collision or Move it Dammit

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#121]
[Alduin Save(Save 175).zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4739191/Alduin.Save.Save.175.zip) \

**Mod Name**
Disable Follower Collision or Move it Dammit.

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/35925 - Disable Follower Collision
https://www.nexusmods.com/skyrimspecialedition/mods/752 - Move it Dammit

**Why?**
I know I'm not the only one that finds it annoying when a follower is quite literally dry humping(pushing you around) or not moving out of a doorway, this however can be un-immersive for some just walking through a follower which is why i also linked a different mod which makes ALL npcs move further out of the way for a more immersive. Overall they both have the general idea of "Get out of my way"

**Additional context**
Realistically this should be low priority because its really not a huge deal, more of a quality of life thing. 
Thanks for considering :)

**Comment by ForgottenGlory** [comment]
Nether's Follower Framework has multiple commands for followers that would serve to get them out of the way, I believe these mods would just be redundant with that in mind.
