### ISSUE TITLE
Serana and other npc blackface

### ISSUE THREAD

**Issue by mcbadass253** [ForgottenGlory/Living-Skyrim-2#122]
**LS Version**
LS2 beta 1

**Describe the bug**
Serana and a few other npcs in caatle vorkihar had black unmodded faces.

**Expected behavior**
To have modded face from either bijin, seranaholic or pandorables npcs
![20200605_202023](https://user-images.githubusercontent.com/66504768/83935234-f82d8880-a774-11ea-82b9-99add3992da9.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
