### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by Mortulak** [ForgottenGlory/Living-Skyrim-2#124]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_6_5_20-48-27.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4739596/Crash_2020_6_5_20-48-27.txt)
[Crash_2020_6_5_23-24-46.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4739597/Crash_2020_6_5_23-24-46.txt)
[Crash_2020_6_5_23-55-36.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4739598/Crash_2020_6_5_23-55-36.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 Beta 2

**Describe the bug**
CTD1: tried to store items in a chest
CTD2: fighting and a group of bandits -> died -> CTD
CTD3: just running around

**To Reproduce**
different CTD couldn't be reproduced

**Expected behavior**
no CTD.

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Are any of these repeatable or just one-off crashes?

**Comment by Mortulak** [comment]
One-off crashes. Played 1h today with no issues.
