### ISSUE TITLE
Floating Lantern in Soljund's Stinkhole

### ISSUE THREAD

**Issue by Mortulak** [ForgottenGlory/Living-Skyrim-2#125]
**LS Version**
2.0.0 Beta 2

**Describe the bug**
Lantern not attached to the house

**To Reproduce**
go to Soljund's stinkhole

**Expected behavior**
lantern attached to the house it is closest to

**Screenshots**
![ScreenShot215](https://user-images.githubusercontent.com/66409946/83939510-e0d6b580-a7dd-11ea-8aeb-1845616a1510.png)
![ScreenShot216](https://user-images.githubusercontent.com/66409946/83939512-e59b6980-a7dd-11ea-9800-cbff2d022067.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
