### ISSUE TITLE
Axe of Injustice has no charges/infinite charges

### ISSUE THREAD

**Issue by Mortulak** [ForgottenGlory/Living-Skyrim-2#126]
**LS Version**
2.0.0 Beta 2

**Describe the bug**
Health drain enchant has no charge bar, but works on hit

**To Reproduce**
get Axe of Injustice

**Expected behavior**
charge bar/limited charges

**Screenshots**
![ScreenShot217](https://user-images.githubusercontent.com/66409946/83939709-5c853200-a7df-11ea-9143-7c90b3a56441.png)
![ScreenShot218](https://user-images.githubusercontent.com/66409946/83939713-6149e600-a7df-11ea-8f1b-5ba6cca35194.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
