### ISSUE TITLE
BETA 3 - Auri has a bad face part - Causes immediate CTD when selected in Racemenu

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#127]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Crash_2020_6_6_11-47-23.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4740747/Crash_2020_6_6_11-47-23.txt)
[Crash_2020_6_6_11-42-23.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4740748/Crash_2020_6_6_11-42-23.txt)

**LS Version**
b3

**Describe the bug**
bad face part

**To Reproduce**
Racemenu - head - face part - move slider to right - CTD, reload

**Expected behavior**
was hoping that the mod that added the male zombie face part also added a female one but no luck.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by tjbassoon** [comment]
Confirmed by testing in RaceMenu on player character in qasmoke. This affects non-beast races and females only. Not sure if any NPCs have this face part, but if they do I suspect a CTD would occur. Not sure how to test that.

**Comment by ForgottenGlory** [comment]
Unfortunately there isn't a good way to fix this, the parts in question are required for Auri to have the correct appearance. We might just have to live with this one and advise people to not select that head part in RaceMenu.
