### ISSUE TITLE
Beta 5 - Campfire for start "camping in the woods" is floating midair

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#128]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

![image](https://user-images.githubusercontent.com/11461193/83951980-ce1aab80-a7f2-11ea-9124-c94c72772d17.png)

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by TwistedModding** [comment]
Known issue, and if you submit another issue please fill everything out. Dont just leave a screenshot.

**Comment by ForgottenGlory** [comment]
This didn't have an issue open already if I remember correctly, it's fine. Will fix when I get a chance.

**Comment by Fjodik** [comment]
Some grass / bushes near the campfire are floating too, see screenshot
![ScreenShot250](https://user-images.githubusercontent.com/63248466/83971518-eadede00-a8db-11ea-8571-a8075d7fe514.png)

**Comment by JaceVenture** [comment]
Also a very much known bug.

**Comment by pgdeaner** [comment]
What do you guys mean by known bug?  Known bug with what?

**Comment by TwistedModding** [comment]
Glory knows about it

**Comment by pgdeaner** [comment]
So that means he has no intention of fixing? or can't fix?

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
