### ISSUE TITLE
Captain Aldis BFB

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#129]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.
Beta 3
**Describe the bug**
Captain Aldis bfb
**To Reproduce**
go to solitude and see Captain Aldis
**Expected behavior**
no BFB
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No Mods Added
![20200606122415_1](https://user-images.githubusercontent.com/62521502/83952901-294b9e80-a7f1-11ea-9208-458d1d6f329b.jpg)
![20200606122412_1](https://user-images.githubusercontent.com/62521502/83952903-2b156200-a7f1-11ea-8dce-30efbf1e65d2.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
