### ISSUE TITLE
Hole in the ground behind alchemy shop in Riverwood

### ISSUE THREAD

**Issue by Bossaruuu** [ForgottenGlory/Living-Skyrim-2#131]
**LS Version**
Beta 3

**Describe the bug**
There's a hole in the ground behind the alchemy shop in Riverwood

**To Reproduce**
Go behind the alchemy shop in Riverwood

**Expected behavior**
You can see through the ground

**Screenshots**
https://i.gyazo.com/2f34a13d5df7234e897b3f88fab8b4c0.jpg

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
