### ISSUE TITLE
Stuck after activating crafting stations.

### ISSUE THREAD

**Issue by Bossaruuu** [ForgottenGlory/Living-Skyrim-2#132]
**LS Version**
Beta 3 

**Describe the bug**
You are unable to do anything after activating crafting stations such as a tanning rack or enchanting table while having your hands up.

**To Reproduce**
Have your hands up(spells ready, swords unsheathed or whatever) and activate crafting stations such as a tanning rack or enchanting table.

**Expected behavior**
When doing this you will go to 3rd person, unequip what you have in your hands, go back to 1st person, get shoved closer to the object and get completely stuck. You will not be able to do anything except press escape or open the console. 

**Screenshots**
https://i.gyazo.com/774b14719de4478c2340b1351c66af3f.jpg

**Comment by tjbassoon** [comment]
Unable to reproduce

**Comment by ForgottenGlory** [comment]
Also unable to reproduce
