### ISSUE TITLE
Chest clipping through ground in Riverwood

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#134]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 3

**Describe the bug**
Chest clipping through ground in Riverwood under a bridge just to the left after walking in from Helgen path. Has a TON of items in it.

**To Reproduce**
Should be a chest underneath a bridge in Riverwood

**Expected behavior**

**Screenshots**
![ScreenShot246](https://user-images.githubusercontent.com/13601605/83959606-b9aad300-a833-11ea-9e4c-ef1c950f6096.png)
![ScreenShot245](https://user-images.githubusercontent.com/13601605/83959607-bb749680-a833-11ea-855a-3e6c4ed2ef39.png)
![ScreenShot247](https://user-images.githubusercontent.com/13601605/83959627-fbd41480-a833-11ea-884e-14ff16cc297c.png)

**Additional context**

**Comment by Fjodik** [comment]
I think I found the chest too, but this one seems different, the place should be correct (left side of Riverwood close to the mill under the bridge) but the chest is not in the water, standing on the ground normally but with couple of good stuff inside, see pictures. Maybe this one is intended, posting here anyway.

![ScreenShot245](https://user-images.githubusercontent.com/63248466/83970962-dfd67e80-a8d8-11ea-83d9-39cd5acef3bb.png)
![ScreenShot246](https://user-images.githubusercontent.com/63248466/83970972-eb29aa00-a8d8-11ea-9ea4-7278f9f4433f.png)

**Comment by ForgottenGlory** [comment]
The second chest is intended, it's from LOTD. The first is not, will fix.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
