### ISSUE TITLE
Derkeethus still appears mismatched

### ISSUE THREAD

**Issue by CentralSmith** [ForgottenGlory/Living-Skyrim-2#135]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4741362/saves.zip)

**LS Version**
Beta 3

**Describe the bug**
Derkeethus's head, while now appearing properly shaped, still has a vastly different scale color from the rest of his body with a very visible seam.

**To Reproduce**
Find (or spawn) Derkeethus

**Expected behavior**
Derkeethus to not appear mismatched

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83959944-8cb4eb00-a848-11ea-82bc-1f97a64ae61e.png)
![image](https://user-images.githubusercontent.com/1962028/83959948-8fafdb80-a848-11ea-8dd6-e8cc65da16a9.png)

**Additional context**
Save added in the event you want to investigate.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
