### ISSUE TITLE
Stoneflesh (or general armor spell?) Invisibility bug

### ISSUE THREAD

**Issue by CentralSmith** [ForgottenGlory/Living-Skyrim-2#136]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Bugged.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4741385/Bugged.zip)
[Before bug.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4741386/Before.bug.zip)

**LS Version**
Beta 3

**Describe the bug**
A strange effect has caused a 'see-through' like effect on the body both in first and third person, with no associated magic effect. Removing, or adding, equipment causes the effect to end for a split second before re-applying. 

In the 'bugged' save, I have Stoneflesh going. Disabling it, then re-enabling it fixes the invisibility issue, but it is unknown why the initial invisibility was apparently.

**To Reproduce**
Unknown. 

**Expected behavior**
Invisibility with Invisibility spells/potions!

**Screenshots**
![image](https://user-images.githubusercontent.com/1962028/83960259-51b4b680-a84c-11ea-9974-df3ae7a87ab2.png)

**Additional context**
I have _no_ clue how this happened or why. The best guess I have is something to do with Stoneflesh's skin-effect derping.

**Comment by CentralSmith** [comment]
An update: While applying Stoneflesh fixes the issue, for as long as Stoneflesh is cast, the fix is temporary. Removing Stoneflesh will leave me visible up and until I go into first-person, upon which time the invisibility is re-applied.

**Comment by CentralSmith** [comment]
Solution discovered. Spell effect AtronachUnsummonDeathFXS: 000EA8FF was the cause of the invisibility. Utilizing player.sms 000EA8FF resolved the issue fully. This may be a vanilla bug, or some odd interaction involving that specific spell effect.

**Comment by daffodilian** [comment]
Casting Stoneflesh (enabling or disabling with sustained magic) gets rid of the effect in third person. But going into first person triggers it.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
