### ISSUE TITLE
Floating lanterns in Riverwood

### ISSUE THREAD

**Issue by Fjodik** [ForgottenGlory/Living-Skyrim-2#138]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2 Beta 3

**Describe the bug**
Two floating lanterns in Riverwood (on the back way to Bleak Falls, the road between Riverwood trader and the Sleeping Giant Inn)

**To Reproduce**
Turn right after passing the Riverwood trader and see two floating lanterns on the way

**Expected behavior**
No floating lanterns

**Screenshots**
![ScreenShot247](https://user-images.githubusercontent.com/63248466/83971275-e4039b80-a8da-11ea-9544-a00232d74036.png)
![ScreenShot248](https://user-images.githubusercontent.com/63248466/83971280-ee259a00-a8da-11ea-9b76-bc8f0b873c6c.png)
![ScreenShot249](https://user-images.githubusercontent.com/63248466/83971291-f67dd500-a8da-11ea-89e1-12e7e8b20da5.png)

**Comment by JaceVenture** [comment]
Known bug, there are also more than two.
