### ISSUE TITLE
Crash when entering Rayek's end

### ISSUE THREAD

**Issue by Ajexais** [ForgottenGlory/Living-Skyrim-2#141]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

[Crash_2020_6_7_17-43-54.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4742600/Crash_2020_6_7_17-43-54.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

BETA 3

**Describe the bug**

Crash when enter Rayek's end

**To Reproduce**

Enter Rayek's end

**Expected behavior**

To not crash

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

none

**Additional context**

worked on beta 2
You can see on log that it mentions AArayeksend as "Possible relevant objects"

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
