### ISSUE TITLE
Blood Texture bug

### ISSUE THREAD

**Issue by SovnSkyrim** [ForgottenGlory/Living-Skyrim-2#142]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 Beta 3

**Describe the bug**
The blood on the ground appears unimmersively

**To Reproduce**
Kill a bunch of bandits.

**Expected behavior**
The squary texture should be transparent

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
http://prntscr.com/svium5

**Comment by Capzien** [comment]
I also have this - using Silent Horizons
![ScreenShot258](https://user-images.githubusercontent.com/66503902/84344389-0274da00-abee-11ea-945e-741e2889bfc5.png)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 7
