### ISSUE TITLE
False Sheathing CTD

### ISSUE THREAD

**Issue by SovnSkyrim** [ForgottenGlory/Living-Skyrim-2#143]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 Beta 3

**Describe the bug**
The sheathing animation for 1H plays but the weapon stays in hand. Normally this isnt a problem but for some reasons in this modlist, changing weapons make the game CTD.

**To Reproduce**
It happens more frequently in crowed areas. ie: bandits forts/camps
-Draw/Sheath your weapon often, you'll know it's bugged when your weapon stays in your hand when looking down in first person.
-Now try to switch weapon from the favourites menu or the inventory (I didnt try iEquip since I dont use it). It should CTD the game.

**Expected behavior**
This bug is really common but generally the game isnt supposed to CTD,
So technically the expected behavior is to just change weapons.

**Screenshots**
X

**Additional context**
My best bet would be ALLGUD, since this is a frequent bug of DSR but not to this extent.

**Comment by ForgottenGlory** [comment]
Need some testers on this one, I'm not able to replicate

**Comment by tjbassoon** [comment]
Can you suggest a location or weapon that was equipped when this happened?

**Comment by Konsetsuki** [comment]
Other things to consider is states, like getting knocked down or the vamprisim's revive after being downed once, I do know the vampire being down does some funky thing with your equipment and hands.

**Comment by ForgottenGlory** [comment]
I've not been able to replicate this
