### ISSUE TITLE
CTD when loading a saved game

### ISSUE THREAD

**Issue by gooeymonster** [ForgottenGlory/Living-Skyrim-2#145]
[Crash_2020_6_7_20-28-35.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4743425/Crash_2020_6_7_20-28-35.txt)

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

Beta 3

**Describe the bug**

I fast travelled to Solitude from Whiterun, ran around a bit. An accidental fight with some 'good' NPCs made me reload a previous save, and the game crashed then. 
[Save128_A6E8D0BF_0_426A6F726E2049726F6E73696465_Tamriel_000515_20200608012617_11_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4743426/Save128_A6E8D0BF_0_426A6F726E2049726F6E73696465_Tamriel_000515_20200608012617_11_1.zip)

**To Reproduce**
Fast travel to Solitude from Whiterun. Reload saved game in Whiterun. 

**Expected behavior**

I expected for the game to just load normally. 

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

Not sure if this is another case of 'Skyrim being Skyrim' but I thought it'd be important to report.

**Comment by daffodilian** [comment]
Is this a consistent CTD? Or it has just happened once?

**Comment by gooeymonster** [comment]
> Is this a consistent CTD? Or it has just happened once?

Once so far, I haven't played since. I'll try it again and let you know.

If it's random, you think its 'skyrim being skyrim'?

**Comment by gooeymonster** [comment]
Wasn't able to reproduce.
