### ISSUE TITLE
Unable to obtain Conjuration perks Atromancy and Necromancy

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#146]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 3

**Describe the bug**
Even with sufficient requirements, with skill level meeting standard and having perk points available, Atromancy and Necromancy remain dim in the skills tree.

**To Reproduce**
Conjuration up to 40 or higher for Atromancy and 50+ for Necromancy

**Expected behavior**
Perks should be available.

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
