### ISSUE TITLE
Thieves Guild side quest: Help the poor - Can give Septim to any NPC/animal i can talk to

### ISSUE THREAD

**Issue by Mortulak** [ForgottenGlory/Living-Skyrim-2#147]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2 Beta 3

**Describe the bug**
can give 50 septim to dog, see screenshot

**To Reproduce**
join thieves guild, start quest to help the poor, speak to any npc/animal

**Expected behavior**

**Screenshots**
![ScreenShot245](https://user-images.githubusercontent.com/66409946/84068592-7aae8600-a9c9-11ea-8628-98f2ea79b6ce.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
....I love this. I'm keeping it.
