### ISSUE TITLE
Black Face bug: Mercer Frey and Aringoth

### ISSUE THREAD

**Issue by Mortulak** [ForgottenGlory/Living-Skyrim-2#148]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2 Beta 3

**Describe the bug**
black faces of mercer Frey in thieves guild and Aringoth on the quest "Loud and Clear" in Goldenglow Estate

**To Reproduce**
go to thieves guild/ goldenglow estate

**Expected behavior**
no black faces

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Future bug reports of BFBs need to have a screenshot of the affected NPC selected while you have the console open. Fixed Beta 4
