### ISSUE TITLE
Wayfarer's Belt Bag/Dual Sheath conflict

### ISSUE THREAD

**Issue by CentralSmith** [ForgottenGlory/Living-Skyrim-2#149]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 4

**Describe the bug**
Equipping two swords (resulting in dual sheaths on the back) force-unequips the Wayfarer's Belt Bags from the Wayfarer armor set. The second sheath for the left-hand weapon occupies the same slot.

**To Reproduce**
Equip Wayfarer Belt Bags, attempt to equip and draw/sheath 2 swords.

**Expected behavior**
Belt bags possible while wielding 2 swords.

**Screenshots**
https://i.gyazo.com/10be95ef186d30e8ee5cb6a4053f1767.mp4

**Additional context**
Wayfarer's Belt Bags - 3C004929

**Comment by Konsetsuki** [comment]
If you check weapon slots in the all geared up in MCM, you can change the secondary weapon sword to something like slot 60 where the shield is, it replaces it and won't overlap on the slot where the bags go.

**Comment by ForgottenGlory** [comment]
I find Konsetsuki's fix to be acceptable.
