### ISSUE TITLE
Summon Familiar not working with Sustain mod

### ISSUE THREAD

**Issue by quidgy** [ForgottenGlory/Living-Skyrim-2#150]
2.0 Beta 4

Use Summon Familiar spell playing as a Breton

This spell was interacting with the sustain spell mod when using Beta 3. Not working on Beta 4.

![ScreenShot251](https://user-images.githubusercontent.com/66656142/84103312-066df400-aa56-11ea-86f3-10740202d5ed.png)

I tested with another spell, Summon Flame Atronach, and that is working as intended.

Possibly something to do with the fix implemented to have the familiar spell scale with Breton's?

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
