### ISSUE TITLE
Floating rock/seat

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#151]
**LS Version**
L.S. Beta 4

**Describe the bug**
A stone block/seat is floating in the Helgen tunnels under the fort. Just after the jailor area.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
![ScreenShot251](https://user-images.githubusercontent.com/66503902/84131314-bd369800-aa87-11ea-9c8d-4e276e54f217.png)
![ScreenShot252](https://user-images.githubusercontent.com/66503902/84131325-c1fb4c00-aa87-11ea-8f51-4aac4a235092.png)
![ScreenShot253](https://user-images.githubusercontent.com/66503902/84131332-c45da600-aa87-11ea-88d5-91d2059552bd.png)

**Comment by ForgottenGlory** [comment]
This looks fine to me
