### ISSUE TITLE
cluster of lanterns 

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#154]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
beta 4

**Describe the bug**
there is a cluster of lanterns

**To Reproduce**
dont know i just slept at riverwood inn and went outside and it was there

**Expected behavior**
not to be one
![ScreenShot251](https://user-images.githubusercontent.com/66355096/84165959-eb8d8680-aa39-11ea-9398-c1a7bcc9ec4b.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by tjbassoon** [comment]
I don't see them outside the inn. Picture doesn't help locate them much

**Comment by Capzien** [comment]
I also have these, they were a little bit outside the inn in Riverwood and towards the gate Whiterun side, if that makes sense.

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
