### ISSUE TITLE
Floating barrels outside Sleeping Giant inn (Riverwood)

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-2#155]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 4

**Describe the bug**
Cluster of barrels not sitting flush on the terrain outside inn in Riverwood.

**To Reproduce**
Begin a new game, select patron of inn, Riverwood. Go outside and look.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
![ScreenShot254](https://user-images.githubusercontent.com/19911571/84185774-22bd6100-aa55-11ea-8bbc-225f7cf9ff26.jpg)
![ScreenShot255](https://user-images.githubusercontent.com/19911571/84185776-2355f780-aa55-11ea-86f0-76ad685993ee.jpg)

**Additional context**
Player sits on terrain fine. Cannot select this section of terrain in console.

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
