### ISSUE TITLE
Fire spell "Firebolt"

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#156]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 4

**Describe the bug**
Spell "Firebolt" doing little to no damage, only doing burn tick damage. Spells like Fire Rune and Flames are doing decent enough damage.

**To Reproduce**
Cast spell Firebolt from either left or right hand.

**Expected behavior**
Should expect damage to occur.

**Screenshots**

**Additional context**
The tooltip does state the fire damage to be 24~ but it is doing 0 damage.

**Comment by Konsetsuki** [comment]
Adding, it seems like many of the projectile based fire spells are not damaging enemies.

**Comment by tjbassoon** [comment]
Yes, Firebolt and Fireball are not damaging enemies. Flames does.

**Comment by ForgottenGlory** [comment]
Testing a possible fix in Beta 5, please double check this once Beta 5 is available.

**Comment by tjbassoon** [comment]
Still present in Beta 5

**Comment by ForgottenGlory** [comment]
I'm at a loss for this one, these spells are vanilla. I'm open to suggestions for how to fix.

**Comment by TwistedModding** [comment]
If its not doing any damage against specific types of enemies, something might editing those enemies giving them immunity to that fire projectiles (unless its only with firebolt)

**Comment by Konsetsuki** [comment]
Anything projectile related isn't doing the impact damage. Was the first fix disabling the friendly fire?

**Comment by TwistedModding** [comment]
Is it a specific enemy or is it with everything?

**Comment by Konsetsuki** [comment]
I've tried against bandits, animals such as bears, wolves, sabercats..., dwemer constructs, the impact doesn't do damage, but it'll still take 1-2 burn damage a second for a brief time. the explosion from fireball damages enemies, but the impact doesn't deal damage.

**Comment by ForgottenGlory** [comment]
I'm implementing a less than ideal fix for this in Beta 6, but I'll be revisiting this at some point for a better fix.

**Comment by Wears-No-Pants** [comment]
I'm still experiencing this bug on Beta 6, only using the firebolt and ice spike spells. I'll add he other spells to my PC to test them and let you know if it's the same all around

**Comment by tjbassoon** [comment]
> I'm still experiencing this bug on Beta 6, so far i've only tried using the firebolt and ice spike spells. I'll add the other spells to my PC to test them and let you know if it's the same all around

I cannot replicate in b6. All spells I've tested do damage when playing as a Nord. Firebolt and Ice Spike both do damage. Ice Spike wasn't an issue in previous betas. Try a fresh install, start a character in qasmoke (just coc qasmoke from the title screen on the console) and add the spells to your character by finding them in the chest of spells. This is a more organic way to test them.

**Comment by Wears-No-Pants** [comment]
>Try a fresh install, start a character in qasmoke (just coc qasmoke from the title screen on the console) and add the spells to your character by finding them in the chest of spells. This is a more organic way to test them.

I shall do that. 
One thing I noticed in previous betas was that this bug only seemed to affect certain characters. I'm wondering if has something to do with the classes, as characters that have focused to being a novice mage can cast all spells fine compared to say if I've been a warrior who wants to cast a few spells down the line.

**Comment by tjbassoon** [comment]
The bug only affected Nords. It didn't seem to affect any other races.

**Comment by Wears-No-Pants** [comment]
I was a Nord, that would explain it

**Comment by TwistedModding** [comment]
It should be fixed in beta 6 though.

**Comment by Wears-No-Pants** [comment]
Would you like my save so you can see if anything is up?

**Comment by Konsetsuki** [comment]
Beta 4 and 5 it effected my redguard.

**Comment by Konsetsuki** [comment]
Can confirm that in B6 my redguard can use firebolt effectively.

**Comment by Wears-No-Pants** [comment]
The firebolt problem persits for me, I've tried removing it through the console and re-adding it, I've reverted to a previous save, I started a new character and added firebolt to them and It worked fine (Altmer) so I loaded back up into my Nord and firebolt was worthless again. It's a mystery to to be sure

**Comment by ForgottenGlory** [comment]
This is only fixed on new saves, existing saves will still have the issue, which is one of the several reasons Beta 6 **required** a new save.

**Comment by Wears-No-Pants** [comment]
I was using completly new saves in beta 6 though

**Comment by TwistedModding** [comment]
I just tested it, firebolt still doesn't seem to be working for nords. 

Yes this was on a new save.
