### ISSUE TITLE
Floating door outside Castle Dawnguard

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#158]
**LS Version**
Beta 4

**Describe the bug**
There is a door floating in the sky outside Castle Dawnguard, noticable as you approach. The door when entered takes you into the free space outside the kitchen of castle dawnguard.

**To Reproduce**
Enter the outer area of Castle Dawnguard

**Expected behavior**
The door would be in an appropriate area.

**Screenshots**
https://youtu.be/SNxoxzDYPFY

A video is easier to describe it.

**Comment by ForgottenGlory** [comment]
Bug reports like this need the object in question selected in console so I can see the FormID of the object. Will fix once I have that.

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
