### ISSUE TITLE
Floating lantern at Dawnstar

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#159]
**LS Version**
Beta 4

**Describe the bug**
Floating lantern at Dawnstar where you zone in after using the carriage service

**To Reproduce**
Use a carriage to zone into Dawnstar, it is in the area

**Expected behavior**
The lantern wouldn't be floating in mid-air.

**Screenshots**
![ScreenShot257](https://user-images.githubusercontent.com/66503902/84234734-10682380-ab38-11ea-96e6-7207430110e8.png)

**Comment by ForgottenGlory** [comment]
Bug reports like this need to have a screenshot of the object selected in console so I can get the FormID. Will fix once I have that.

**Comment by mepatterson** [comment]
I saw some of these too. Captured two screens for you. I haven't seen the others yet.

![enb2020_6_13_14_16_24](https://user-images.githubusercontent.com/74207/84577572-1140c580-ad83-11ea-9849-ee5136d481f3.jpg)
![enb2020_6_13_14_15_01](https://user-images.githubusercontent.com/74207/84577573-11d95c00-ad83-11ea-806f-e5e72dca3332.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
