### ISSUE TITLE
shield changes picture

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#160]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
beta 4

**Describe the bug**
shield changes what it looks like when not out

**To Reproduce**
get shield in pic and equip but not use

**Expected behavior**
for it to look the original
![SkyrimSE 2020-06-10 15-20-14](https://user-images.githubusercontent.com/66355096/84314950-8e273180-ab2e-11ea-8f79-be70a0e85e10.png)
![SkyrimSE 2020-06-10 15-19-40](https://user-images.githubusercontent.com/66355096/84314969-94b5a900-ab2e-11ea-8098-6ae09bb68d87.png)

 

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by ForgottenGlory** [comment]
Hmm. This is correct in xEdit, unsure of what's causing it. Suggestions welcome.

**Comment by KNGLogan** [comment]
pretty  it was by a mod because this happened with a few other shields they would just got back to riften shields when not in use
