### ISSUE TITLE
CTD in College of Winterhold

### ISSUE THREAD

**Issue by DarkWolfiie** [ForgottenGlory/Living-Skyrim-2#161]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Crash_2020_6_10_22-21-49.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4761506/Crash_2020_6_10_22-21-49.txt)
**LS Version**

Beta 4

**Describe the bug**
I had a CTD in the college of winterhold in the building to the left of the the stufent housing(when you come out of student housing go left and enter the building). I was looking in the bookshelf to immeditally to the right once you enter said building.

**To Reproduce**
I Could not reproduce it.

**Expected behavior**
To not CTD.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by ForgottenGlory** [comment]
I'm unable to reproduce this.
