### ISSUE TITLE
Moth Priest caravan just inside Imperial Legion post

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#163]
**LS Version**
LS2 Beta 4

**Describe the bug**
Not so much a bug but an oddity - the caravan the Moth Priest for Dawnguard is ambushed in is just within' an Imperial Legion post. Whilst not a bug, this doesn't seem to make sense - the post is manned 24/7.

**To Reproduce**
N/A

**Expected behavior**
It would make more sense for the caravan to be outside the gates

**Screenshots**
![ScreenShot259](https://user-images.githubusercontent.com/66503902/84344189-72369500-abed-11ea-8f79-4afb083dad45.png)

**Comment by ForgottenGlory** [comment]
I agree this is a bit odd but the amount of time it would take to fix it isn't really worth it.
