### ISSUE TITLE
Multiple Vampires in Castle Volkihar with BFB bug (updated with screenshots)

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#164]
**LS Version**
LS2 Beta 4

**Describe the bug**
Fura Bloodmouth, Hestla and Modhna suffering from BFB

**To Reproduce**
Visit them in Castle Volkihar

**Expected behavior**
Their skin colours would be the same

**Screenshots**
![ScreenShot263](https://user-images.githubusercontent.com/66503902/84465058-6adcbd80-acb9-11ea-8de1-66d2ee8129f2.png)
![ScreenShot264](https://user-images.githubusercontent.com/66503902/84465066-6e704480-acb9-11ea-84fa-945a64a176da.png)
![ScreenShot265](https://user-images.githubusercontent.com/66503902/84465164-ac6d6880-acb9-11ea-8042-e03083dfd03e.png)

**Comment by Capzien** [comment]
Hestla also has this issue
![ScreenShot261](https://user-images.githubusercontent.com/66503902/84344838-208f0a00-abef-11ea-8be9-8ee92b154caf.png)

**Comment by Capzien** [comment]
Modhna also has this issue
![ScreenShot262](https://user-images.githubusercontent.com/66503902/84345161-f2f69080-abef-11ea-99ae-f411b839dc12.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
