### ISSUE TITLE
Dexion hangs when reading Elder Scroll

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#165]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2 Beta 4

**Describe the bug**
Dexion Evicus (the Moth Priest for Dawnguard) hangs after reading the Elder Scroll for Harkon - you are unable to advance the quest.

**To Reproduce**
Reach the stage in the quest "Prophet" titled "Command the Moth Priest to read the Elder Scroll." Do so, he will read it and then remain in the animation of reading and remain un-interactable. Sleeping, waiting, etc. do not work.

**Expected behavior**
The priest would read the scroll then the quest would progress as per normal.

**Screenshots**
https://youtu.be/bbusgO7Y3M8

**Additional context**
I was forced to utilise the console command setstage DLC1VQ03Vampire 200 in order to progress.

**Comment by ForgottenGlory** [comment]
Need some testers on this one please.

**Comment by Capzien** [comment]
As an update - on Beta 5 I did not have a repeat of this
