### ISSUE TITLE
Floating Door Visible from Breakwind Basin

### ISSUE THREAD

**Issue by greenbluegray** [ForgottenGlory/Living-Skyrim-2#166]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

[savegame.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4766463/savegame.zip)

**LS Version**
Beta 4

**Describe the bug**
A door, floating high up in the air, is visible from the ground at Breakwind Basin. The door can be opened, but does not seem to lead anywhere.

**To Reproduce**
Go to Breakwind Basin, face toward the Western Watchtower, and look up.

**Expected behavior**
The floating door should not be there.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

![ScreenShot254](https://user-images.githubusercontent.com/66795544/84421475-3b5a8200-abe1-11ea-876e-7d8bead83efa.png)
![ScreenShot255](https://user-images.githubusercontent.com/66795544/84421443-3269b080-abe1-11ea-9042-9e5b293c5564.png)
![ScreenShot256](https://user-images.githubusercontent.com/66795544/84421447-34cc0a80-abe1-11ea-8c60-08867f1cc82e.png)
![ScreenShot257](https://user-images.githubusercontent.com/66795544/84421456-372e6480-abe1-11ea-9697-56e1765685c6.png)
![ScreenShot258](https://user-images.githubusercontent.com/66795544/84421467-38f82800-abe1-11ea-8ad5-cddd94558243.png)

**Additional context**
N/A

**Comment by ForgottenGlory** [comment]
Issues like this need the object selected with the console open. Will fix once I have that.

**Comment by greenbluegray** [comment]
Here's the screenshot you asked for, also from Beta 4.

![ScreenShot261](https://user-images.githubusercontent.com/66795544/84603136-b75b0100-ae51-11ea-8443-880a6f472a55.png)
