### ISSUE TITLE
Hert and Hern BFB

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#167]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 4

**Describe the bug**
Black Face Bug on Hern and Hert

**To Reproduce**
Steps to reproduce the behavior: Visit Blood Moon Mill

**Expected behavior**
No BFB
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No addition Mods
![20200611163052_1](https://user-images.githubusercontent.com/62521502/84449144-5f2dc000-ac01-11ea-9d68-15f1af778af1.jpg)
![20200611163055_1](https://user-images.githubusercontent.com/62521502/84449152-60f78380-ac01-11ea-8152-fd3354296443.jpg)
![20200611163124_1](https://user-images.githubusercontent.com/62521502/84449154-62c14700-ac01-11ea-81d7-659a4829d2ec.jpg)
![20200611163128_1](https://user-images.githubusercontent.com/62521502/84449158-63f27400-ac01-11ea-955c-bfdd6fdf5f78.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
