### ISSUE TITLE
NPCs at Rift Watchtower not reacting to Vampire Lord

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#168]
**LS Version**
LS2 Beta 4

**Describe the bug**
None of the NPCs at Rift Watchtower react to Vampire Lord form except for the bandits outside.

**To Reproduce**
Activate Vampire Lord form and approach the NPCs

**Expected behavior**
The NPCs should become hostile to a Vampire Lord

**Screenshots**
![ScreenShot266](https://user-images.githubusercontent.com/66503902/84561113-1276f000-ad8d-11ea-95fa-b8649c588e66.png)
![ScreenShot267](https://user-images.githubusercontent.com/66503902/84561115-173ba400-ad8d-11ea-8dda-dfc2ee1187eb.png)
![ScreenShot268](https://user-images.githubusercontent.com/66503902/84561117-1b67c180-ad8d-11ea-8b97-fc3db503412a.png)
![ScreenShot269](https://user-images.githubusercontent.com/66503902/84561119-1efb4880-ad8d-11ea-9d49-3b1a84943a25.png)
![ScreenShot270](https://user-images.githubusercontent.com/66503902/84561120-23276600-ad8d-11ea-8527-0aecb9eb15c6.png)
![ScreenShot271](https://user-images.githubusercontent.com/66503902/84561124-27538380-ad8d-11ea-9a47-9e26cde0c184.png)

**Comment by ForgottenGlory** [comment]
As far as I can tell based on the NPC records from 3DNPC, this is intended. The NPCs in this tower are Dremora, which as far as I'm aware shouldn't be hostile to vampires? Someone can correct me if I'm wrong but I think this is working correctly.
