### ISSUE TITLE
7000 steps etched tablet incorrectly placed

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#169]
**LS Version**
LS2 Beta 4

**Describe the bug**
The etched tablet for the first shrine on the way up the 7000 steps to High Hrothgar is incorrectly placed

**To Reproduce**
Visit the shrine

**Expected behavior**
The etched tablet would be in the recess where it is meant to be

**Screenshots**
![ScreenShot272](https://user-images.githubusercontent.com/66503902/84561518-7d75f600-ad90-11ea-85bb-fcfca25617d2.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
