### ISSUE TITLE
Moonlit Waters not working correctly

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#170]
**LS Version**
LS2 Beta 4

**Describe the bug**
Moonlit Waters is a passive bonus that states it allows Vampires to walk on water. It seems to work if you jump into a spot and stand still however as soon as you move you sink. 

**To Reproduce**
Step 1: Become a Vampire
Step 2: Attempt to walk on water

**Expected behavior**
The Vampire character would be able to walk on water akin to when using the Vampire Lord ability/similar to the Waterwalking spell (000b8307) (which appears to work perfectly)

**Screenshots**
https://youtu.be/_qbkNlxZbP8

**Comment by ForgottenGlory** [comment]
Nothing is affecting this in xEdit, I'm open to suggestions on how to fix this one.

**Comment by Capzien** [comment]
Not sure if it'd work as a long-term fix but I used the console to give myself waterwalking 000b8307 when testing this and it worked perfectly, perhaps simply adding that to characters at the same time on a permanent basis would be a decent band-aid?

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
