### ISSUE TITLE
Reliquary of Myth - Can't Download b/c of Updates

### ISSUE THREAD

**Issue by jtmoney412** [ForgottenGlory/Living-Skyrim-2#171]
Reliquary of Myth has been updated a few times in the past week and the download is failing as a result. Someone posted on the discord that the list uses version 2.9.15, but the earliest available on Nexus is 2.9.17.

**Comment by ForgottenGlory** [comment]
This was fixed about an hour ago. Download the latest installer and try again.

**Comment by jtmoney412** [comment]
Oh wow, such a fast turnaround! Thanks for following up and keeping this
guide so fresh!
