### ISSUE TITLE
Summon Familiar Cost is Broken

### ISSUE THREAD

**Issue by Dommius** [ForgottenGlory/Living-Skyrim-2#173]
**LS Version**
Beta 5

**Describe the bug**
Summon Familiar costs over 29,000 Magicka to cast

**To Reproduce**
Make any Breton character and check the cost.

**Expected behavior**
It to cost the standard 40 or so to sustain.

**Screenshots**
![20200613133649_1](https://user-images.githubusercontent.com/66885351/84577768-7a710a80-ad7c-11ea-85c0-cf71506e9893.jpg)

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
