### ISSUE TITLE
AGO PCA compatibility fix.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#174]
**LS Version**
2.0.0 beta 5

**Describe the bug**
AGO PCA bow compatibility issues

**To Reproduce**
Just load up the game create character find bow and arrow  go in third person and shoot

**Expected behavior**
No animation conflict

STEPS:
1.) Make 2 copies each of the files and place them somewhere you'll remember. "bow_drawlight.hkx" and "sneakbow_drawlight.hkx" 
These files can be found in D:\Living Skyrim\mods\Archery Gameplay Overhaul SE\meshes\actors\character\animations
2.) Make 1 copy of each place them somewhere you'll remember. "bow_idleheld.hkx" and "bow_idledrawn.hkx" 
These files can be found in D:\Living Skyrim\mods\Archery Gameplay Overhaul SE\meshes\actors\character\animations
3.) Rename one of each of the copied files named "bow_drawlight.hkx" and "sneakbow_drawlight.hkx" to "bow_drawheavy.hkx" and "sneakbow_drawheavy.hkx" and place them somewhere you'll remember.
4.) Move all of those files to D:\Living Skyrim\mods\Pretty Combat Animations\meshes\actors\character\animations AND D:\Living Skyrim\mods\Pretty Combat Animations\meshes\actors\character\animations\female

This will take the needed bow animations from AGO and have them overwrite PCA's bow animations while keeping all other animations in PCA intact. 

Once again I don't think there is any other way to fix this as they both have different idle/drawing animations for bows. Changing the mod order doesn't seem to effect anything for the female character because of the separate folder in PCA specifically for female animations doesn't get overwritten by anything in AGO.

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
