### ISSUE TITLE
BETA 5 - Choosing Kynareth gives no speed benefit.  Used to give 110%

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#176]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

**Describe the bug**
Choosing Kynareth gives no speed benefit.  Used to give 110%

**To Reproduce**
Start game, choose Kynareth, check stats.

**Expected behavior**
Earlier versions of LS speed benefit was 110%

**Screenshots**
![image](https://user-images.githubusercontent.com/11461193/84580827-f7f64400-ad97-11ea-8329-4413474e42d4.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Nothing has changed regarding this, and the bonus only applies while in combat.
