### ISSUE TITLE
BETA 5 - Missing Breakdown Recipes for the attached weapons and armor

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#177]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
BETA 5

**Describe the bug**
Can't be broken down at rack or forge.

**To Reproduce**
Try to break these items down.

**Expected behavior**
The items should yield crafting materials based on the links provided by FG.

**Screenshots**
![image](https://user-images.githubusercontent.com/11461193/84581261-af8d5500-ad9c-11ea-8299-35c7fbe79807.png)
![image](https://user-images.githubusercontent.com/11461193/84581272-d77cb880-ad9c-11ea-8876-a6fb15c2c54f.png)
![image](https://user-images.githubusercontent.com/11461193/84581279-ed8a7900-ad9c-11ea-8858-8a4c0000280c.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
