### ISSUE TITLE
BETA 5 - Ralof's behavior broken.

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#178]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 5

**Describe the bug**
Ralof does not behave normally.  He does not follow you, he chases bandits, and he only meets you in riverwood if you are fortunate.  He does not speak his lines about BFB or the Standing Stones.

**To Reproduce**
Find Ralof under helgen and give him a healing potion.

**Expected behavior**
He should say "we better split up" and head to Riverwood.  Then stop to explain BFB to you and the standing stones.  Then he follows you to Riverwood to speak to Gerdur.

**Screenshots**
Just stands there.  Will not move.  Waited for 10 minutes.
![image](https://user-images.githubusercontent.com/11461193/84581492-ca60c900-ad9e-11ea-8bd3-5ce5f8f07da7.png)

**Only moved when I was attacked by bandits near the guard tower.

Runs ahead of me and does not wait.
![image](https://user-images.githubusercontent.com/11461193/84581482-b3ba7200-ad9e-11ea-89b2-7be3cd79c646.png)

Runs up this hill for no reason.
![image](https://user-images.githubusercontent.com/11461193/84581477-9be2ee00-ad9e-11ea-8432-0f880db66a92.png)

Chasing Bandits:
![image](https://user-images.githubusercontent.com/11461193/84581471-7bb32f00-ad9e-11ea-872b-26194c161bc9.png)

**Additional context**

**Comment by pgdeaner** [comment]
Never seen this behavior before.

**Comment by Capzien** [comment]
His behaviour is also broken using the Vanilla start option, basically the same behaviour.

**Comment by ForgottenGlory** [comment]
This might be fixed Beta 6 - there were some landscape changes that probably didn't match up with the navmesh causing him to get confused. Followup on this.

**Comment by ForgottenGlory** [comment]
Just tested and this is sort-of fixed. If you move far enough away he starts moving normally. He isn't required to progress the story, you can head straight to Riverwood and talk to Sven or whoever to progress.

**Comment by pgdeaner** [comment]
But then you miss all of the background on BFB and the standing stones.
Also don't get the key from Gerdur which allows you to skip paying for an inn.

**Comment by pgdeaner** [comment]
The key is the most important.

**Comment by pgdeaner** [comment]
I tested and you are correct.  He no longer wanders off, you just need to go far enough.
