### ISSUE TITLE
Attacked in starting cell

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#179]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2 Beta 5

**Describe the bug**
Whilst in starting area, waiting for mods to finish starting up, was attacked by NPCs

**To Reproduce**
Start a new character, wait.

**Expected behavior**
This would be a safe zone

**Screenshots**
![ScreenShot251](https://user-images.githubusercontent.com/66503902/84581767-39363480-ae28-11ea-8549-52112c919658.png)
![ScreenShot252](https://user-images.githubusercontent.com/66503902/84581768-3d625200-ae28-11ea-980e-4293f6377220.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
