### ISSUE TITLE
Floating Flora and Braizers outside Museum

### ISSUE THREAD

**Issue by electraumatized** [ForgottenGlory/Living-Skyrim-2#180]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
BETA 5

**Describe the bug**
Floating Flora and braziers outside of the LoTD Museum

**To Reproduce**
Walk into Legacy courtyard

**Expected behavior**
Plants should not be floating

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
![ScreenShot252](https://user-images.githubusercontent.com/66895387/84584620-36a5f180-adcc-11ea-9a6e-9e336ea73b68.png)
![ScreenShot253](https://user-images.githubusercontent.com/66895387/84584622-3ad20f00-adcc-11ea-9efb-e32ebadfc05c.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 6

**Comment by electraumatized** [comment]
I personally still have this issue in BETA 6
