### ISSUE TITLE
Unable to equip shield

### ISSUE THREAD

**Issue by quidgy** [ForgottenGlory/Living-Skyrim-2#181]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 5

**Describe the bug**
Unable to equip a shield in either hand. The character animates as though it is equipped and I can bash and block etc but it doesn't move from the character's back.

**To Reproduce**
Tried two different shields

**Expected behavior**
Equip shield as normal

![enb2020_6_14_15_51_12](https://user-images.githubusercontent.com/66656142/84585974-85996880-ae58-11ea-8990-1da0b9741053.jpg)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by ForgottenGlory** [comment]
The screenshot provided does not have the shield in question selected. Drop it on the ground, open console, and click on the shield to select it so I can see what's going on with that.
