### ISSUE TITLE
Beta 5 - Random Spawns Seem Misplaced and incongruous

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#182]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 5

**Describe the bug**

**To Reproduce**
Play the game, examples are everywhere.

**Expected behavior**
Dungeons should be a progression.  You should not be fighting mobs in the first room of a dungeon that are tougher than the boss in the final room.

**Screenshots**
This "wight" spawned in the first area of BFB.  He was fully capable of shouts and was able to shout almost faster than I could draw a bow.
![image](https://user-images.githubusercontent.com/11461193/84594795-dfc30b00-ae11-11ea-9ffb-2a4398905ad4.png)

This same wight killed all of the bandits in this room.
![image](https://user-images.githubusercontent.com/11461193/84594777-cde16800-ae11-11ea-88e2-e6826d02d71d.png)

**Additional context**

**Comment by pgdeaner** [comment]
Also there is a report on the support forum of someone getting mobs spawned in the starting cell.  I'd expect it's the same mod.

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
