### ISSUE TITLE
Beta 5 - Spawned follower behaves strangely.

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#183]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 5

**Describe the bug**
I spawned an instance of Serana.  When talking to her I was presented with a dialog to hire her as a follower.  I paid a fee and hired her.  Once that transaction was complete she drew her dagger and ran off.

**To Reproduce**
Spawn an instance of serana using player.placeatme.

**Expected behavior**
I would expect some weirdness from Serana, but I have done this before and she didn't just run off.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
Wonder if this is related to the odd behavior that Ralof has.

**Comment by ForgottenGlory** [comment]
I'm assuming this is caused by spawning in Serana instead of finding her normally through the questline, there are likely some game flags that didn't get set properly by skipping it, resulting in this behavior.
