### ISSUE TITLE
velothi mountain tunnel area

### ISSUE THREAD

**Issue by DontCareAboutName** [ForgottenGlory/Living-Skyrim-2#184]
![6Lx9JNktud](https://user-images.githubusercontent.com/66926331/84607059-b2597a00-ae70-11ea-936b-88381af14ca6.jpg)
![hgKKCs2x7T](https://user-images.githubusercontent.com/66926331/84607061-bab1b500-ae70-11ea-8410-9e88088ad382.jpg)

**Comment by ForgottenGlory** [comment]
Screenshots like this need to have the console open and object in question selected so I can locate it. Will fix once I have that.
