### ISSUE TITLE
Shrine of Clavicus Vile outside Fort Dawnguard

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#185]
**LS Version**
LS2 Beta 5

**Describe the bug**
The Shrine of Clavicus Vile statue outside the entrance to Fort Dawnguard clips on the arch over its head

**To Reproduce**
Visit the Shrine/statue

**Expected behavior**
The statue would not clip

**Screenshots**
![ScreenShot256](https://user-images.githubusercontent.com/66503902/84632218-eea0df00-af31-11ea-9812-d3f1e416cf9c.png)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 6
