### ISSUE TITLE
Fort Dawnguard Doorway

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#186]
**LS Version**
LS2 Beta 5

**Describe the bug**
The main door to Fort Dawnguard is incorrectly placed. This was not the case in previous builds of LS2

**To Reproduce**
Visit Fort Dawnguard0

**Expected behavior**
The door would be in its correct position

**Screenshots**
![ScreenShot257](https://user-images.githubusercontent.com/66503902/84632351-1ee87d80-af32-11ea-8a67-c59d37f037c6.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
