### ISSUE TITLE
Floating seeking treasure hunters note Old Hroldun Inn

### ISSUE THREAD

**Issue by Steve1405** [ForgottenGlory/Living-Skyrim-2#187]
**LS Version**
LS2 Beta 5

**Describe the bug**
When entering inn a floating treasure hunters note.

**To Reproduce**
If you enter the inn using the door to the left with the signpost inside the main gate first then enter via the door to the right you get the floating note roughly half way up the door.

**Screenshots**
![enb2020_6_15_11_34_32](https://user-images.githubusercontent.com/55761833/84649945-496d1300-aeff-11ea-86e7-4e0a895ae15f.jpg)

**Comment by ForgottenGlory** [comment]
Screenshots like this need to have the console open and item selected so I can locate it. Will fix once I have that.

**Comment by tjbassoon** [comment]
I couldn't find the note at all.
