### ISSUE TITLE
Alternate Start: Imperial Legion - Unable to advance MQ

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#188]
**LS Version**
LS2 Beta 5

**Describe the bug**
This will be lengthy;

Started Beta 5 character using the Imperial Legion start. Completed the first quest - Jagged Crown. The quest after this sends you to Jarl Balgruuf of Whiterun to make him pick a side. You are unable to advance this at this point. I headed to Helgen and witnessed the dragon attack and headed to Riverwood as instructed to speak to Alvor (the blacksmith). From there I was asked to head to Whiterun to alert the Jarl as per normal and was allowed into the city and to speak to the Jarl. 

Quest completed. I was then walked over to Farengarr (the court mage) to have a chat about the Dragonstone. That quest was completed as I already had the tablet on me. This is the end of how I can progress - I am stuck on the quest "Message to Whiterun" as you can see below on the step "Assist Jarl Balgruuf with the dragon threat." 

![ScreenShot260](https://user-images.githubusercontent.com/66503902/84684499-16b53000-af7c-11ea-9786-75cdb873fdeb.png)

As you can notice in the screenshot I have no other quests relating to the main quest/assisting the Jarl in my quest log and have attempted to talk to everyone. I cannot engage anything at the guard tower (where I am in the screenshot, where you would fight the 1st dragon). As such I am unable to advance the MQ.

Attempting to use "movetoqt 000D661C" as a last resort results in a "No current targets" message

Jarl Balgruuf wont speak to me - he just says "Not now" and Irileth is nowhere to be found.

**To Reproduce**
Described above

**Expected behavior**
I would expect the MQ to advance as per normal at this point

**Comment by Konsetsuki** [comment]
There's a mod that prevents you from advancing the quest immediately. It's "Not so quick" variation, wait 7 days.

**Comment by Capzien** [comment]
That was it, however I think this should be made more obvious for this quest as you have an active quest asking you to assist that you get prior to ever going to Helgen
