### ISSUE TITLE
Dark Vision isn't doing anything.

### ISSUE THREAD

**Issue by Dommius** [ForgottenGlory/Living-Skyrim-2#189]
**LS Version**
Beta Version 5.0

**Describe the bug**
Dark vision isn't doing anything. Neither the spell, vampire sight, or granting myself it through cheats in the MCM to test it.

**To Reproduce**
Make a new character, leave the starting cell and try activating night vision in a dark place. Nothing happens outside of the small blur at the edges of the screen. 

**Expected behavior**
The game to brighten up enough to let me see, similar to the screenshots on the mod page. Or at least enough I don't still need to use the lantern / magelight to explore as a vampire. 

**Screenshots**
Normal Vision
![Normal](https://user-images.githubusercontent.com/66885351/84715378-7df7c380-af2d-11ea-9a50-4d3841f39dbc.jpg)

Night Vision
![Night Vision](https://user-images.githubusercontent.com/66885351/84715390-8b14b280-af2d-11ea-939b-1385987af3e9.jpg)

Predator Vision
![Predator Vision](https://user-images.githubusercontent.com/66885351/84715402-97007480-af2d-11ea-988d-4bf178eccb2d.jpg)

**Additional context**
As you can see predator vision is functioning. I tried messing with brightness and colour settings in the MCM, tried disabling my ENB and nothing helped. However even cranking the colour shift to max for predator vision didn't change the filter to be even close to the screenshots on the mod page. So maybe it's not working 100% either.

**Comment by Dommius** [comment]
Scratch this, turns out the issue was on my end and I'm idiot. Have it fixed now.

**Comment by cloumb** [comment]
I'm also having the same issue with predator / night vision. What did you do to fix it?

**Comment by KNGLogan** [comment]
what enb you have

**Comment by cloumb** [comment]
Rudy's ENB

**Comment by cloumb** [comment]
The night vision makes a sound when I activate it, but the predator vision does not. Neither do anything visually.

**Comment by KNGLogan** [comment]
look in last part of this https://docs.google.com/presentation/d/1oZ7UgK3fkUbN3jtrP7AHBUH3fxwAOwDnkYHDYOwvWeo/edit#slide=id.g8eea88c806_0_16

**Comment by cloumb** [comment]
Interesting - for me, it didn't change the picture.
![Nighteye values](https://user-images.githubusercontent.com/71395107/93654128-d62cde80-f9d0-11ea-9bef-d5eb4f840bb7.PNG)
![enb effect](https://user-images.githubusercontent.com/71395107/93654132-dc22bf80-f9d0-11ea-8b3c-8d86e5ddcfe3.PNG)

**Comment by cloumb** [comment]
What's weird is I can see clearly when looking through the fog/mist in the cave, but otherwise it is dark.

![Clear vision](https://user-images.githubusercontent.com/71395107/93656220-8accfd00-f9dd-11ea-93c8-1f3c2fb3c96c.PNG)
![Dark vision](https://user-images.githubusercontent.com/71395107/93656221-8c96c080-f9dd-11ea-99e8-f48acf3e9986.PNG)

**Comment by KNGLogan** [comment]
params not right

**Comment by cloumb** [comment]
Thank you very much! That did the trick. I greatly appreciate your help - it was kind of frustrating to stumble through that on my own for a few hours.
