### ISSUE TITLE
Darkwater Crossing landscape conflict

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim-2#19]
![ScreenShot162](https://user-images.githubusercontent.com/63564258/82158518-6d80fa00-9856-11ea-8208-1f62419d881f.png)
![ScreenShot161](https://user-images.githubusercontent.com/63564258/82158520-6fe35400-9856-11ea-9ce8-2ad9dc79a383.png)
![ScreenShot163](https://user-images.githubusercontent.com/63564258/82158523-7245ae00-9856-11ea-9f2b-8108b09bf07f.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
