### ISSUE TITLE
Lantern outside Dragonbridge spazzing out

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#190]
**LS Version**
LS2 Beta 5

**Describe the bug**
Lantern at the guard post outside Dragonbridge is shaking like crazy

**To Reproduce**
Visit it

**Expected behavior**
It would be still/blowing in an expected way in the wind

**Screenshots**
![ScreenShot263](https://user-images.githubusercontent.com/66503902/84758920-65f57200-b009-11ea-9eb0-11a3c806f3f7.png)
![ScreenShot264](https://user-images.githubusercontent.com/66503902/84758994-802f5000-b009-11ea-85ba-ca0151f455f1.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 6
