### ISSUE TITLE
Divine Steel Helmet invisible

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#192]
**LS Version**
2.0.0 beta 5.1

**Describe the bug**
Divine Steel Helmet invisible
**To Reproduce**
 Craft or spawn in Divine Steel Helmet 

**Expected behavior**
visible helmet

**Screenshots**
![ScreenShot251](https://user-images.githubusercontent.com/62785432/84815868-48a8af80-afd9-11ea-9e4e-9c1dfca03ca7.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Nothing is changing these in xEdit, need to investigate further. Should be working normally.

**Comment by TwistedModding** [comment]
Intented, closing.
