### ISSUE TITLE
Foot of the Mountain quest won't progress

### ISSUE THREAD

**Issue by JG1995** [ForgottenGlory/Living-Skyrim-2#193]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Living Skyrim 2 - Beta 5

**Describe the bug**
Upon being attacked by the guy who starts "Foot of the Mountain", the quest log asks you to "Read Camilla's note". Despite doing this, the quest will not progress and show the marker on the map.

**To Reproduce**
Be attacked by the guy who's name I don't remember. Something with an "i". Read the note as instructed. Observe how it doesn't progress.

**Expected behavior**
The quest should progress.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by ForgottenGlory** [comment]
Need some testers on this, I'm not able to replicate.
