### ISSUE TITLE
Sword of First Ember missing crafting recipes and temper recipes

### ISSUE THREAD

**Issue by jprlink23** [ForgottenGlory/Living-Skyrim-2#195]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 5.1

**Describe the bug**
Cannot upgrade the Sword of First Ember (Worn) and Sword of First Ember (New) to the next tier because the recipe is missing. Cannot temper any of the versions of the sword.

**To Reproduce**
Spawn in the Worn and New versions and go to the forge or grindstone.

**Expected behavior**
To be able to upgrade and temper these weapons
**Screenshots**
![ScreenShot256](https://user-images.githubusercontent.com/66271389/84951616-4bc59d80-b0b6-11ea-866e-5f081c082036.png)
![ScreenShot257](https://user-images.githubusercontent.com/66271389/84951789-8cbdb200-b0b6-11ea-8b32-47306107e2f9.png)
![ScreenShot258](https://user-images.githubusercontent.com/66271389/84951870-b37be880-b0b6-11ea-9208-dd9a0a791406.png)
![ScreenShot259](https://user-images.githubusercontent.com/66271389/84951955-d0182080-b0b6-11ea-806f-2fbfe5481ba0.png)
![ScreenShot260](https://user-images.githubusercontent.com/66271389/84952016-ecb45880-b0b6-11ea-9e2b-b65de1e92bd0.png)

**Additional context**
This issue might also affect the 2-handed version as well. Didn't test that version though

**Comment by ForgottenGlory** [comment]
Fixed Beta 6

**Comment by jprlink23** [comment]
Don't know if I should just open a new issue for this but all the crafting recipes are in the forge except for the Ignited version for the 1-handed variation
