### ISSUE TITLE
Having Dawnbreaker equipped causes QuickLight to not emit light

### ISSUE THREAD

**Issue by jprlink23** [ForgottenGlory/Living-Skyrim-2#196]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 5.1

**Describe the bug**
While having Dawnbreaker equipped, turning on quick light doesn't light up the area around you

**To Reproduce**
Equip Dawnbreaker and turn on quick light

**Expected behavior**
To be able to have Dawnbreaker equipped and have the light work

**Screenshots**
![ScreenShot252](https://user-images.githubusercontent.com/66271389/84952391-8845c900-b0b7-11ea-90f9-587365c7d963.png)
![ScreenShot251](https://user-images.githubusercontent.com/66271389/84952457-9e538980-b0b7-11ea-9db6-5733b1882c6c.png)
![ScreenShot254](https://user-images.githubusercontent.com/66271389/84952559-c511c000-b0b7-11ea-9bad-bb30df6154f5.png)
![ScreenShot253](https://user-images.githubusercontent.com/66271389/84952623-de1a7100-b0b7-11ea-9af2-2eb2b145acfe.png)
![ScreenShot255](https://user-images.githubusercontent.com/66271389/84952728-0efaa600-b0b8-11ea-88a7-8437faa37c86.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
This seems to be a known issue with Dawnbreaker retextures and QuickLight, I don't believe I can fix this short of removing the Dawnbreaker retexture.
