### ISSUE TITLE
Possibly 2 Alfarinn's in the world, breaking Missives delivery mission.

### ISSUE THREAD

**Issue by epierrej** [ForgottenGlory/Living-Skyrim-2#197]
**LS Version**
Beta 5.0

**Describe the bug**
Trying to do a delivery from the Missives mod. Alfarinn's quest marker is separate from him. When I talk to him, he has no option to give him the delivery item. Also cannot interact with the independent quest marker.

**To Reproduce**
Go to Windhelm stables, go to Alfarinn, the carriage driver. Enter dialogue with him.

**Expected behavior**
The quest marker should be over him, and he should have a dialogue option to give him the delivery item.

[Save13_7917A601_0_456772696D6D_Tamriel_000209_20200618043208_1_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4796266/Save13_7917A601_0_456772696D6D_Tamriel_000209_20200618043208_1_1.zip)

**Additional context**
There may be 2 Alfarinn's in this world as the independent quest icon has its own ID that has the vanilla Alfarinn's ref ID and can be teleported, rather than the physical Alfarinn sitting on the carriage.

**Comment by ForgottenGlory** [comment]
Only one Alfarinn exists in the game, however, I have had other reports of Missives not being completable when targeting carriage drivers. I'll look into this further.

**Comment by ForgottenGlory** [comment]
Upon further research this is a known issue with Missives and NPCs that have scripted actions, unfortunately I can't fix it. There are workarounds in the bugs section on the mod's page.
