### ISSUE TITLE
Konahrik Mask Issues

### ISSUE THREAD

**Issue by Dingenerate** [ForgottenGlory/Living-Skyrim-2#198]
**LS Version**
2.0 Beta 5

**Describe the bug**
Apophysis Dragon Priest Mask Retextures cause the Default Konahrik Mask to look significantly different than the armor set intended to go with it in Konahrik's Accoutrements.

Additionally the Light Konahrik Mask added by Konahrik's Accoutrement that retains the original texture has a bug where you can see inside the eyes and the back of the head, your head being invisible essentially. I'm assuming some kind of conflict with the improved closedface helmets mod.

**To Reproduce**
Equip the light Konahrik mask in a well lit area.

**Expected behavior**
The default Konahrik helmet will be ugly with Konahrik Accoutrement's armor.

The light Konahrik mask will be ugly because you can see inside it.

**Additional context**
I added both mask using console commands.

**Comment by ForgottenGlory** [comment]
The texture I don't believe I can fix but the seethrough mask should be fixed Beta 7.
