### ISSUE TITLE
Flickering carpet in Breezehome

### ISSUE THREAD

**Issue by epierrej** [ForgottenGlory/Living-Skyrim-2#199]
**LS Version**
Beta 6

**Describe the bug**
Lighting flicker/flashing carpet in the upstairs player bedroom of Breezehome.

**To Reproduce**
Go to player bedroom in Breezehome. Move around in the room while looking at the carpet.

**Expected behavior**
Consistent lighting

**Screenshots**
![ScreenShot251](https://user-images.githubusercontent.com/23179930/85088516-eea91500-b1a5-11ea-9612-37341129fe55.png)
![ScreenShot252](https://user-images.githubusercontent.com/23179930/85088546-ff598b00-b1a5-11ea-8a0c-d28943a05f33.png)

**Save File**
[Save3_D7E09E5E_0_456772696D6D_WhiterunBreezehome_000009_20200619015139_1_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4802045/Save3_D7E09E5E_0_456772696D6D_WhiterunBreezehome_000009_20200619015139_1_1.zip)

**Comment by tjbassoon** [comment]
Vanilla skyrim engine behavior? Too many light sources causes this. That's my guess.

**Comment by TwistedModding** [comment]
I haven't seen an issue like that before with the lighting limit, although it still very is possible that is the cause.

If thats the case there is no fix as its an engine limitation.

**Comment by tjbassoon** [comment]
This doesn't happen in my game either. Can't reproduce

**Comment by ForgottenGlory** [comment]
I'm also unable to reproduce this. You might need to try a fresh install of the list.
