### ISSUE TITLE
Neck seam on Belethor

### ISSUE THREAD

**Issue by epierrej** [ForgottenGlory/Living-Skyrim-2#200]
**LS Version**
2.0 Beta 6

**Describe the bug**
Discolored neck seam on Belethor

**To Reproduce**
Go to Whiterun. Go to Belethor's shop. Look at Belethor up close.

**Expected behavior**
Consistent transition from head/neck to body.

**Screenshots**
![ScreenShot254](https://user-images.githubusercontent.com/23179930/85089172-8ce9aa80-b1a7-11ea-95e2-05cc04cd7ccf.png)

**Save File**
[Save4_D7E09E5E_0_456772696D6D_WhiterunBelethorsGeneralGoods_000022_20200619020453_1_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4802076/Save4_D7E09E5E_0_456772696D6D_WhiterunBelethorsGeneralGoods_000022_20200619020453_1_1.zip)

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
