### ISSUE TITLE
Freestanding Chimney with no Building at Rorikstead

### ISSUE THREAD

**Issue by epierrej** [ForgottenGlory/Living-Skyrim-2#201]
**LS Version**
2.0 Beta 6

**Describe the bug**
Chimney freestanding, not attached to any building

**To Reproduce**
Go to southern edge of Rorikstead

**Screenshots**
![ScreenShot258](https://user-images.githubusercontent.com/23179930/85092731-f40b5d00-b1af-11ea-92fa-7a023bf4c717.png)

**Save File**
[Save17_D7E09E5E_0_456772696D6D_Tamriel_000106_20200619030856_1_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4802267/Save17_D7E09E5E_0_456772696D6D_Tamriel_000106_20200619030856_1_1.zip)

**Additional context**
The MCM for arm chimneys only supports added structures and not removed ones?

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
