### ISSUE TITLE
Loot Menu

### ISSUE THREAD

**Issue by Sinful-Soles** [ForgottenGlory/Living-Skyrim-2#202]
**LS Version**
Beta 6

**Describe the bug**
Fallout 4 real time loot sometimes does not clear the item from the menu until opening a new menu or looking away from the menu.

**To Reproduce**
Find any container with loot and grab item, sometimes the item will stay on the menu and you can repeatedly 'loot' it as sound effect procs but you will only get one item added to your inventory. 

**Expected behavior**
Item is looted and updated in real time.

**Additional context**
When I was looting and this bug happened, it also seemed to affect all items meaning if there were 3 potions, one for each attribute, and you took one, it would be added to your inventory but trying to loot the others would not.

**Comment by mikk198** [comment]
also it seems to never happen when theres only one item in container/body/etc...

**Comment by tjbassoon** [comment]
I can't reproduce

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
