### ISSUE TITLE
Korvanjund exterior graphical glitches

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#203]
**LS Version**
LS2 Beta 60

**Describe the bug**
Some minor graphical glitches on textures outside Korvanjund below the stairs/ramp. I was unable to target the texture with confidence in the console so simply included pictures of location, hopefully this is ok. Apologies.

**To Reproduce**
Visit Korvanjund

**Expected behavior**
The textures would look natural/as if they fit

**Screenshots**
![ScreenShot251](https://user-images.githubusercontent.com/66503902/85133338-d5739780-b27d-11ea-92ef-bb8e8358eb50.png)
![ScreenShot253](https://user-images.githubusercontent.com/66503902/85133351-dad0e200-b27d-11ea-9b44-9946cdaa6279.png)
![ScreenShot254](https://user-images.githubusercontent.com/66503902/85133362-defcff80-b27d-11ea-9ccd-d0e851f2f006.png)

**Comment by ForgottenGlory** [comment]
As usual I need the object selected in console to fix.
