### ISSUE TITLE
Whiterun Dragonsreach NPCs broken - Alt Start: Aldmeri Dom.

### ISSUE THREAD

**Issue by rb-evans** [ForgottenGlory/Living-Skyrim-2#204]
If you make a high elf, and select your alternate start to be a Thalmor Agent (or something like that), when you go to Whiterun the NPCs in Dragonsreach think they are at the party at the Thalmor Embassy. I imagine all the NPCs throughout the world who typically go to that party will be equally as confused.

**Comment by ForgottenGlory** [comment]
I'm unable to replicate this.

**Comment by rb-evans** [comment]
Could be that I triggered part of the "party" before leaving the Embassy. I
remember two of the Thalmor running over to a counter and then having a
conversation about "maybe the dragons will eat all the mages, they are
stuck up thinking us grunts are blah blah blah". Which if I'm not mistaken,
is dialogue you are able to overhear during the actual Thalmor Embassy
mission. Following my departure I went to Whiterun, where I spoke to the
Jarl and his man servant. All they would say was "I wish I was back at
Whiterun, I really don't care for parties" etc.

At any rate, if you can't reproduce it, maybe it was just a strange glitch
I managed to trigger.
Loving LS2 btw!
