### ISSUE TITLE
Certain Meshes/Textures eat frames

### ISSUE THREAD

**Issue by electraumatized** [ForgottenGlory/Living-Skyrim-2#205]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
BETA 6

**Describe the bug**
Certain Meshes/Textures tank frames from a solid 60 fps down to, in some cases, 9-10 fps. Disabling said items brings fps back up to 60. Unsure if "bug" or just nature of Skyrim's engine.

**To Reproduce**
Look at reported Meshes/Texture

**Expected behavior**
FPS should not drop as drastically low as it does.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
![ScreenShot251](https://user-images.githubusercontent.com/66895387/85183760-8401e300-b252-11ea-82bd-3291b31f33bf.png)
![ScreenShot253](https://user-images.githubusercontent.com/66895387/85183765-8b28f100-b252-11ea-8ccf-60acd1c0ade6.png)
![ScreenShot254](https://user-images.githubusercontent.com/66895387/85183767-90863b80-b252-11ea-8d90-5210f98c9412.png)
![ScreenShot255](https://user-images.githubusercontent.com/66895387/85183776-9845e000-b252-11ea-9c59-2db55963a55e.png)
![ScreenShot256](https://user-images.githubusercontent.com/66895387/85183778-9d0a9400-b252-11ea-9f25-bbf2114b16bc.png)

**Additional context**
If not considered a bug, please close. I am playing at 1080p. i7 8700k @ 4.2ghz and RTX 2070 Super.
I average a pretty Solid 60fps and everything is installed on a Samsung 860evo SSD

**Comment by tjbassoon** [comment]
Confirmed with that chest in the museum. Drops to 10fps, but only when centered on parts of the chest when you're close to it. Just looking at it from a distance isn't a problem.

**Comment by tjbassoon** [comment]
Does this happen with containers only or other static objects? This happened with the gem strong box in breezehome but it's another container that isn't working with quick loot.

**Comment by electraumatized** [comment]
Statics as well, such as the skeletons. The mortar and pestle happens as you go go loot the shelf it is on. The museum chest can be interacted with to sort items which, you are then close enough for the frames to drop.

**Comment by ForgottenGlory** [comment]
I'm uncertain how to fix this, we'll need to identify which mod(s) are adding these statics causing the issues.

**Comment by zhangalexh** [comment]
i also noticed the left statue outside of the LOTD gallery would drop the frame rate down to ~10 when moving close to it while looking at it. might be another one you can look at if you can repro

**Comment by tjbassoon** [comment]
![enb2020_6_18_12_11_40](https://user-images.githubusercontent.com/19911571/85913080-41627c80-b7f7-11ea-9f80-8aa17fb16154.jpg)
![enb2020_6_26_21_32_26](https://user-images.githubusercontent.com/19911571/85913081-41627c80-b7f7-11ea-98bc-b9042692190d.jpg)
![enb2020_6_26_21_34_36](https://user-images.githubusercontent.com/19911571/85913082-41fb1300-b7f7-11ea-975c-5bad6ac50985.jpg)
![enb2020_6_26_21_35_30](https://user-images.githubusercontent.com/19911571/85913083-4293a980-b7f7-11ea-80f6-35e0e9a75cdc.jpg)
![enb2020_6_26_21_38_07](https://user-images.githubusercontent.com/19911571/85913084-4293a980-b7f7-11ea-8bda-b32c7ac53f20.jpg)

This is just in the dragonborn museum and the blue palace. I feel like this isn't a specific mod or whatever causing this problem, but something in the overall settings of the mod list. I don't find this issue in Lexy's LOTD list at all, it's not related to ENB. I can try copying the ini file from that list over to see if that makes a difference, but I'm not sure. I was unable to target just the statues in front of the gallery, they show as just part of the entire exterior. Proximity to the object matters a great deal. Back away a few steps and the FPS does not drop.

**Comment by electraumatized** [comment]
Seems the new update of Legacy of the Dragonborn fixes these for that mod at least.
