### ISSUE TITLE
Grelod the Kind's Journal

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#206]
**LS Version**
LS2 Beta 6

**Describe the bug**
Grelod the Kinds journal has a typo. It states "One meal a deal is more than good enough for them"

This seems as if it should state "One meal a day is more than good enough for them" in the context

**To Reproduce**
View her journal, page 6. 

**Expected behavior**
This seems as if it should state "One meal a day is more than good enough for them" in the context

**Screenshots**
![ScreenShot255](https://user-images.githubusercontent.com/66503902/85190216-54f27c80-b2f9-11ea-8c0f-c48f8a88cf1d.png)
![ScreenShot256](https://user-images.githubusercontent.com/66503902/85190219-591e9a00-b2f9-11ea-8b5a-a552f384eb1d.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
