### ISSUE TITLE
Staff of Magnus incorrect description

### ISSUE THREAD

**Issue by buffetleaf666** [ForgottenGlory/Living-Skyrim-2#208]
**LS Version**
Beta 6

**Describe the bug**
Staff of Magnus enchantment description uses the vanilla description instead of the one from reliquary of myth even through the staff uses the mods enchantments instead of the vanilla one.

**To Reproduce**
View Staff of Magnus in inventory

**Expected behavior**
Staff should use the reliquary description instead of the vanilla one.

**Screenshots**
![ScreenShot251](https://user-images.githubusercontent.com/67215122/85216714-1048fe80-b356-11ea-8c36-efa24a6374b9.png)

![Screenshot (2)](https://user-images.githubusercontent.com/67215122/85216757-864d6580-b356-11ea-85fe-e5d6b990a3e7.png)

**Comment by tjbassoon** [comment]
Confirmed. Easy fix, forward the (blank) description from Reliquery into LS2 Patches Mrged.exp

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
