### ISSUE TITLE
Quickloot causing crashes

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#209]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

[Crash_2020_6_20_19-44-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4810426/Crash_2020_6_20_19-44-5.txt)
[Crash_2020_6_21_15-59-9.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4810428/Crash_2020_6_21_15-59-9.txt)

**LS Version**
Beta 6

**Describe the bug**
Crashing when trying to take an item from dead bodies. First was a hagraven and the veil of nature spell book, second was a forsworn with a frost enchanted cloak.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 7.
