### ISSUE TITLE
Rocks/Trees clipping (majorly) with walkway in Ivarstead

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#210]
**LS Version**
LS2 Beta 6

**Describe the bug**
Some rocks and trees in Ivarstead are clipping (majorly) with the walkway outside Hall of Kyne in Ivarstead

**To Reproduce**
Visit Ivarstead

**Expected behavior**
They would not clip

**Screenshots**
<<It's not letting me attach screenshots>>

**Comment by Capzien** [comment]
![ScreenShot258](https://user-images.githubusercontent.com/66503902/85264457-105f1080-b4b4-11ea-8bd9-8da635199695.png)
![ScreenShot259](https://user-images.githubusercontent.com/66503902/85264466-1523c480-b4b4-11ea-8b0c-31ed0e23e86c.png)
![ScreenShot260](https://user-images.githubusercontent.com/66503902/85264493-19e87880-b4b4-11ea-8372-cd0d4ba59952.png)

**Comment by ForgottenGlory** [comment]
Fixed the rock but I need the trees selected in console to fix.
