### ISSUE TITLE
Incorrectly placed leaves meshes in Ivarstead (Fellstar Farm)

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#211]
**LS Version**
LS2 Beta 6

**Describe the bug**
There are 3 leaves/moss or something meshes/textures incorrectly placed outside Fellstar farm. There is also a floating "tree" behind the building.

**To Reproduce**
Visit Fellstar Farm

**Expected behavior**
They would be attached to the building

**Screenshots**
![ScreenShot261](https://user-images.githubusercontent.com/66503902/85264843-ab57ea80-b4b4-11ea-8457-82b404316e0d.png)
![ScreenShot262](https://user-images.githubusercontent.com/66503902/85264858-af840800-b4b4-11ea-8aa1-c36657c736a7.png)
![ScreenShot263](https://user-images.githubusercontent.com/66503902/85264865-b3178f00-b4b4-11ea-82cf-f86749a65573.png)
![ScreenShot264](https://user-images.githubusercontent.com/66503902/85264873-b6127f80-b4b4-11ea-8461-718d0da6b1bd.png)

![ScreenShot265](https://user-images.githubusercontent.com/66503902/85265049-038eec80-b4b5-11ea-8edd-f9c45346fe92.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
