### ISSUE TITLE
Missing texture in embershard mine - very small.

### ISSUE THREAD

**Issue by DeadBlackRoses** [ForgottenGlory/Living-Skyrim-2#212]
Just a tiny missing texture in embershard mine. Second screenshot to show location.
![enb2020_6_22_13_00_33](https://user-images.githubusercontent.com/54689471/85320348-eea06200-b490-11ea-82d4-d96b4d324136.jpg)
![enb2020_6_22_13_00_47](https://user-images.githubusercontent.com/54689471/85320367-f52ed980-b490-11ea-9dbd-5e4e267b3ae7.jpg)

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
