### ISSUE TITLE
CTD at Bandit Camp that's north of Whiterun.

### ISSUE THREAD

**Issue by phireblast** [ForgottenGlory/Living-Skyrim-2#213]
**LS Version**
Beta 6.1

**Describe the Bug**
After my character dies, the game CTDs. I haven't tested this in other locations yet.

**To Reproduce**
Upon reaching Bandit Camp, I killed the two bandits there and equipped some gear. After that, I looted some items at the location and attempted to pick the lock on the chest(with no lockpicks). After that, two bandits spawn closeby and I died to them which was followed by a CTD during the load screen.

**Expected Behavior**
Assuming i'm filling this in correctly, I was expecting the game to simply reload my previous save as normal.

**Additional context**
Mabye this has something to do with me installing Gamepad++ and possibly the location of my ENB plugins??

[Crash_2020_6_22_18-39-16.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4815915/Crash_2020_6_22_18-39-16.txt)

**Comment by ForgottenGlory** [comment]
Unfortunately I don't have a way to confirm that mods added aren't causing the issue, if someone can replicate on an unmodified LS install then yes I will fix it.
