### ISSUE TITLE
Living Skyrim 2 Ver. 6.1

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#214]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Put the version of the list you are on here.

Beta 6.1

**Describe the bug**

Frozen Electrocuted Combustion (FEC) is not applying its effects to NPCS or dead bodies.

**To Reproduce**

Attacked bandits with Flames, Frostbite, and Sparks. None of the spells that killed activated their effects, i.e. frost damage shattering npc bodies, flames reducing npcs to ash or charred bodies. Corpses also remained unaffected.

**Expected behavior**

As stated above, I expected FEC to apply its effects to NPCs killed by specific types of damage and to corpses as well.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by jokerstyle00** [comment]
[Saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4816489/Saves.zip)

**Comment by ForgottenGlory** [comment]
Unfortunately I don't have a way to confirm that mods added aren't causing the issue, if someone can replicate on an unmodified LS install then yes I will fix it.
