### ISSUE TITLE
Ancient Nord Arrow value

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#215]
**LS Version**
LS2 Beta 6

**Describe the bug**
Ancient Nord Arrows have an oddly inflated value

**To Reproduce**
Go to sell some

**Expected behavior**
They would have a more appropriate value

**Screenshots**
![ScreenShot268](https://user-images.githubusercontent.com/66503902/85353125-e4db3500-b54a-11ea-8c13-38b383062895.png)

**Comment by ForgottenGlory** [comment]
Those arrows have a value of 1 in xEdit, most likely what's happened is Supply & Demand has adjusted the value because you have so many. Not a bug.
