### ISSUE TITLE
Unknown Thieves Guild oddity

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#216]
**LS Version**
LS2 Beta 6

**Describe the bug**
After stealing a valuable potion (value 6000) was given a quest - "Honor among thieves" (MordQuestGoodThief (3008B900)) and "The Call of Gray Cowl of Nocturnal" (manny_GF_MQ (10001E61)).

There are two issues:
1. I am not a member of the thieves guild and as such it doesn't make sense that I can be offered the option in chat below:

![ScreenShot269](https://user-images.githubusercontent.com/66503902/85353500-bad64280-b54b-11ea-9766-41754fb101a3.png)

I have this option with most NPCs in the game.

2. The Honor among thieves quest doesn't make sense - I've never met a Cairine. I recieved this quest after I picked up "Powerful Medicine" (Morditem3 (3015B27A)). This quest seems like it should be locked behind something and the potion is the 2nd or 3rd step in the quest. I am unfamiliar with it and it seems odd.

**To Reproduce**
Steal "Powerful Medicine" from, I believe, the Silver-Blood home in Markarth. 

**Expected behavior**
The thieves guild donation option would not be available unless you were a member of the thieves guild, and the Powerful Medicine would not trigger what appears to be the second step of a quest.

**Comment by tjbassoon** [comment]
#1 is expected behavior. That is how the mod The Gray Cowl of Nocturnal starts. After you steal enough you get a vision to go to a house to continue the mod. Your association with the Thieves' Guild has nothing to do with it.

#2 seems to be a bug with TCBM Thieves Guild for Good Guys. Not sure if that is an issue with LS2 specifically.

**Comment by ForgottenGlory** [comment]
Second one is intended, it's part of the TCBM quest Honor Among Thieves. It's an optional quest that you likely started once you obtained the item. Not a bug.
