### ISSUE TITLE
Irileth & Co getting stuck on run for Dragon Rising

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#217]
**LS Version**
LS2 Beta 6

**Describe the bug**
Irileth and the Whiterun Guards path collides with a wall section added by a mod.

Worth noting that they do eventually make it through, so this isn't "gamebreaking" so to speak.

**To Reproduce**
Advance mainquest to Dragon Rising, follow Irileth - she gets stuck on the wall/has pathing issues every time.

**Expected behavior**
They would follow the road I guess

**Screenshots**
![ScreenShot272](https://user-images.githubusercontent.com/66503902/85354088-1c4ae100-b54d-11ea-8555-8701d99509ae.png)
![ScreenShot273](https://user-images.githubusercontent.com/66503902/85354099-210f9500-b54d-11ea-85d7-2ad8cb94742e.png)
![ScreenShot274](https://user-images.githubusercontent.com/66503902/85354101-240a8580-b54d-11ea-91bb-fd861e631ac9.png)

**Comment by ForgottenGlory** [comment]
Should be able to workaround this by waiting an hour using the wait menu, that should snap them out of it and make them move.
