### ISSUE TITLE
Still missing the Ignited variation of the one handed Sword of the First Ember

### ISSUE THREAD

**Issue by jprlink23** [ForgottenGlory/Living-Skyrim-2#218]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 6

**Describe the bug**
Just missing the Ignited version of the Sword of the First Ember

**To Reproduce**
Check forge and search Sword of the First Ember. Can see all 3 versions for the 2-handed but only the Worn and New versions for the 1-handed

**Expected behavior**
Have 3 versions for each

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 7
