### ISSUE TITLE
Hammet's Dungeon Packs missing weapon and floating helmets

### ISSUE THREAD

**Issue by ToughSquash** [ForgottenGlory/Living-Skyrim-2#219]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**.
BETA 6.1

**Describe the bug**
The White Frigid Cave boss Hokimir doesn't drop his weapon like the mod page states it does. Also, this is the second dungeon I've completed from this mod and I've encountered floating helmets in both dungeons. Gierhall Barrow was the other one and both are ebony helmets if that helps. They are not selectable with the console. The floating helmets have been seen on different characters and different BETA versions. 

**To Reproduce**
Enter and locate the boss/items.

**Expected behavior**
The sword would be lootable and the same for the helmets.

**Screenshots**
![20200623174014_1](https://user-images.githubusercontent.com/67349252/85483086-10751400-b579-11ea-874b-dde8a6956b01.jpg)

![20200623173924_1](https://user-images.githubusercontent.com/67349252/85483063-0521e880-b579-11ea-8656-b36bece65a2e.jpg)

**Additional context**
I searched for the bosses claymore weapon using the AddItem Search book and it wasn't in there. This is my first bug report so I apologize if I made any mistakes.

**Comment by ForgottenGlory** [comment]
Screenshots like this need to have the console open and object in question selected so I can locate it. Will fix once I have that.

**Comment by KodoShinobi** [comment]
![Skyrim](https://user-images.githubusercontent.com/29106252/89752538-a57c8f80-da89-11ea-88ac-e7372e2ec722.jpg)

I encountered the same bug.  The boss Hokimir's claymore didn't drop.  This view shows the claymore as part of the same boss object without it dropping.
