### ISSUE TITLE
Sanctuary Guardian

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#220]
**LS Version**
LS2 Beta 6

**Describe the bug**
Some Sanctuary Guardians cause no damage

**To Reproduce**
Begin the quest "The Cure for Madness" for the Dark Brotherhood (chasing Cicero in the Dawnstar Sanctuary). From what I can tell the high level guardians cause no damage - the low level ones appear to cause damage.

*I was playing around with TGM in order to get screenshots because it was difficult to see and had to reposition them at times because of mist*

**Expected behavior**
All guardians would cause damage

**Screenshots**
![ScreenShot279](https://user-images.githubusercontent.com/66503902/85492871-3b16a980-b619-11ea-973a-9a5e8aec1761.png)
![ScreenShot280](https://user-images.githubusercontent.com/66503902/85492880-3f42c700-b619-11ea-84c7-b7d64bd989c8.png)

**Comment by ForgottenGlory** [comment]
Fixed for 2.0.0 release
