### ISSUE TITLE
Door bar name

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#221]
**LS Version**
LS2 Beta 6

**Describe the bug**
The door bars name/hoverover is incorrect - there is a typo

**To Reproduce**
Target a door bar

**Expected behavior**
The door bar would be named "Release door bar" instead of "Relesae Door bar"

**Screenshots**
![ScreenShot281](https://user-images.githubusercontent.com/66503902/85493490-5504bc00-b61a-11ea-9480-ff7bfbcf2120.png)

**Comment by ForgottenGlory** [comment]
Fixed for 2.0.0 release
