### ISSUE TITLE
Imperial Patrols glitch(?)

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#222]
**LS Version**
LS2 Beta 6

**Describe the bug**
Two imperial patrols crossed paths - one, without a prisoner, one with. The patrol without a prisoner attacked the prisoner of the other patrol and killed him. Both patrols then carried on their merry way.

Of note: The patrol that committed the war crime had spawned on me at Korvunjund when I had waited at the same time as a Stormcloak patrol. They had fought them and then commenced a patrol.

**To Reproduce**
I'm unsure how you could reproduce this without chance

**Expected behavior**
The Imperial Patrol would not kill a POW.

**Screenshots**
Screenshot 1: Imperial Soldier that murdered
![ScreenShot276](https://user-images.githubusercontent.com/66503902/85497515-68675580-b621-11ea-95d7-9bf2574345ef.png)
Screenshot 2: Imperial Soldier that was escorting the prisoner
![ScreenShot277](https://user-images.githubusercontent.com/66503902/85497526-6c937300-b621-11ea-9cf1-352f2d7c1362.png)
Screenshot 3: The murdered prisoner
![ScreenShot278](https://user-images.githubusercontent.com/66503902/85497537-6f8e6380-b621-11ea-9d70-14c09803499b.png)

**Comment by ForgottenGlory** [comment]
I think this is, as you said, mostly up to chance. I don't know that I have a consistent way to replicate it.
