### ISSUE TITLE
Dragonsreach Quest Rewards & Issues

### ISSUE THREAD

**Issue by jtmoney412** [ForgottenGlory/Living-Skyrim-2#223]
I've had a couple of issues with quest rewards in Dragonsreach - I'm not sure if they're related. I gave Proventus his sword from Adrianne and didn't receive the reward. I then completed Dragon Rising and didn't receive the Blade of Whiterun as the reward.

Also, probably not related, I noticed some issues in Farengar's room. There is a bookcase in the middle of the staff enchanter (screenshot included) and I don't see a mystic condenser anywhere.

**LS Version**
Beta 6

**Describe the bug**
Didn't receive quest reward for Dragon Rising and the sword delivery for Proventus/Adrianne. Also, bookcase ontop of the staff enchanter in Farengar's room.

**To Reproduce**
Steps to reproduce the behavior: complete the delivery mission for Proventus/Adrianne and complete Dragon Rising.

**Expected behavior**
I expected to get a septim reward from Proventus for delivering his sword and I expected to get the Blade of Whiterun from the Jarl after Dragon Rising.

**Screenshots**

![ScreenShot251](https://user-images.githubusercontent.com/62395499/85770134-995e8d80-b6e8-11ea-9421-fc5da398b1e5.png)

**Additional context**
For the quest rewards, the usual dialogue played but I didn't receive the items in my inventory.

**Comment by ForgottenGlory** [comment]
Fixed the clipping Staff Enchanter, but as for the quest rewards I haven't been able to replicate. Need some testers on this one.

**Comment by electraumatized** [comment]
Just got 20 septims for delivering the sword from his daughter. Also got steel armor for talking about the dragons and getting the dragon stone quest. Will  update when I kill the dragon.
