### ISSUE TITLE
spawning w/ dozens of crafting manuals

### ISSUE THREAD

**Issue by kevinr1117** [ForgottenGlory/Living-Skyrim-2#224]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
LS 7.0
**Describe the bug**
When I spawn in on my character, I spawn in with dozens of crafting manuals for various weapons
**To Reproduce**
Start a new game
**Expected behavior**
Not quite sure, just wasn't expecting dozens of crafting manuals
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
https://gyazo.com/bbf238539ac7fed1a1d36ce50fe053d5
**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed for 2.0.0 release
