### ISSUE TITLE
Hair floating off head with certain races/hairstyles

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#225]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Living Skyrim Beat 7 RC1

**Describe the bug**
During character creation, some male races/hairstyles have hair that floats off of the character.

**To Reproduce**
Tried multiple hairstyles and races, most of the male KSHair styles and male elves have noticeable floating hair.

**Expected behavior**
Hair that does not float noticeably above character heads.
![ScreenShot267](https://user-images.githubusercontent.com/67298916/85798226-f874d000-b6f1-11ea-8d9f-8df87375f77d.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
So, weirdly enough, all sources I can find seem to indicate this is caused by ENB. In ENBPatch.ini in your SSE install folder, try setting Speedhack to false.
