### ISSUE TITLE
Minor improper tree placement when choosing Guildmaster start in Abandoned Cell

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#226]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Living Skyrim Beat 7 RC1

**Describe the bug**
Some minor graphical bugs with a floating tree and a tree inside the equipment tent when choosing the Guildmaster start for Live Another Life.

**To Reproduce**
Chose Guildmaster start 3 times.

**Expected behavior**
No clipping/floating.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot269](https://user-images.githubusercontent.com/67298916/85798418-4db0e180-b6f2-11ea-93f9-26c599993b99.png)
![ScreenShot270](https://user-images.githubusercontent.com/67298916/85798421-4e497800-b6f2-11ea-956d-c8520a7757a0.png)

**Additional context**

**Comment by TwistedModding** [comment]
You need to select the trees in question for it to be fixed.

**Comment by jokerstyle00** [comment]
![ScreenShot271](https://user-images.githubusercontent.com/67298916/85799996-08da7a00-b6f5-11ea-916d-0dc19069dfee.png)
![ScreenShot272](https://user-images.githubusercontent.com/67298916/85799997-09731080-b6f5-11ea-8be7-5e1ea4415c5d.png)

Updated screenshots with console selection, my mistake.

**Comment by ForgottenGlory** [comment]
Fixed for 2.0.0 release
