### ISSUE TITLE
Amaund Motierre BFB

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#227]
**LS Version**
LS2 Beta 6

**Describe the bug**
BFB for Amaund Motierre

Is there 2 versions of him in this game? I don't recall the BFB when you visit him in the ruins to initially get the quest. Apologies for not lodging this yesterday when I saw it, I had to do something and forgot.

**To Reproduce**
Visit him

**Expected behavior**
No BFB

**Screenshots**
![ScreenShot282](https://user-images.githubusercontent.com/66503902/85810727-61fee800-b79f-11ea-99df-0c712caaac84.png)

**Comment by ForgottenGlory** [comment]
Fixed for 2.0.0 release
