### ISSUE TITLE
Floating Trees and Statics Outside Dragonborn Gallery

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-2#228]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Build 7

**Describe the bug**
Floating trees, shrubs, and a brazier near the entrance of the Dragonborn Gallery 

**To Reproduce**
N/A; objects are always floating

**Expected behavior**
N/A; expected objects to be non-existent or on the ground

**Screenshots**
![enb2020_6_26_05_54_49](https://user-images.githubusercontent.com/67465410/85852089-8ba31980-b775-11ea-9aa8-71d37fd7d497.jpg)
![enb2020_6_26_05_54_35](https://user-images.githubusercontent.com/67465410/85852092-8e9e0a00-b775-11ea-9a1d-1d433f658c97.jpg)
![enb2020_6_26_05_54_22](https://user-images.githubusercontent.com/67465410/85852098-9198fa80-b775-11ea-82c8-c23dfdad8bb2.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed for 2.0.0 release
