### ISSUE TITLE
Cave wall tiles incorrectly placed in Embershard Mine

### ISSUE THREAD

**Issue by Capzien** [ForgottenGlory/Living-Skyrim-2#229]
**LS Version**
LS2 Beta 7

**Describe the bug**
Cave walls are incorrectly placed showing the blank space behind them.

**To Reproduce**
Visit the wall section in Embershard Mine

**Expected behavior**
The walls would be closed/touching so at not to be able to see the gap.

**Screenshots**
![ScreenShot266](https://user-images.githubusercontent.com/66503902/85878155-9fa15680-b81b-11ea-9d78-6e7227b4139d.png)
![ScreenShot267](https://user-images.githubusercontent.com/66503902/85878163-a3cd7400-b81b-11ea-8e5a-f7a32ff26450.png)
![ScreenShot268](https://user-images.githubusercontent.com/66503902/85878175-a6c86480-b81b-11ea-9a42-9ab7311faa07.png)

**Comment by ForgottenGlory** [comment]
So, funnily enough, this is a vanilla bug based on what I'm seeing from the screenshots you posted. I'll see if I can't fix it but no promises.
