### ISSUE TITLE
Major conflicts between JK's Skyrim and Settlements Merged in Ivarstead

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-2#230]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
B7/RC1

**Describe the bug**
Many landscape and architecture objects in Ivarstead are conflicting.

**To Reproduce**
Visit Ivarstead

**Expected behavior**
For objects to make sense together

**Screenshots**
This is a selection. Too many objects to list them all.
![enb2020_6_26_21_42_18](https://user-images.githubusercontent.com/19911571/85913039-0a8c6680-b7f7-11ea-90f3-bdb6535b6a4e.jpg)
![enb2020_6_26_21_42_23](https://user-images.githubusercontent.com/19911571/85913040-0b24fd00-b7f7-11ea-9aef-9395550bf39c.jpg)
![enb2020_6_26_21_42_40](https://user-images.githubusercontent.com/19911571/85913041-0b24fd00-b7f7-11ea-849f-8c18c353b99a.jpg)
![enb2020_6_26_21_42_55](https://user-images.githubusercontent.com/19911571/85913042-0bbd9380-b7f7-11ea-9356-656fad9336dd.jpg)
![enb2020_6_26_21_43_09](https://user-images.githubusercontent.com/19911571/85913043-0bbd9380-b7f7-11ea-8cf5-0e098b04da2c.jpg)
![enb2020_6_26_21_43_15](https://user-images.githubusercontent.com/19911571/85913044-0bbd9380-b7f7-11ea-9f68-d245b103839e.jpg)
![enb2020_6_26_21_43_50](https://user-images.githubusercontent.com/19911571/85913045-0c562a00-b7f7-11ea-9907-111356dcdba1.jpg)
![enb2020_6_26_21_44_06](https://user-images.githubusercontent.com/19911571/85913046-0c562a00-b7f7-11ea-9425-bf7f9407a6e3.jpg)
![enb2020_6_26_21_44_37](https://user-images.githubusercontent.com/19911571/85913047-0ceec080-b7f7-11ea-87f2-6b236d5ffc83.jpg)
![enb2020_6_26_21_45_28](https://user-images.githubusercontent.com/19911571/85913048-0ceec080-b7f7-11ea-8e32-738c0d929f69.jpg)
![enb2020_6_26_21_46_18](https://user-images.githubusercontent.com/19911571/85913050-0d875700-b7f7-11ea-8a3f-1523418748be.jpg)
![enb2020_6_26_21_46_27](https://user-images.githubusercontent.com/19911571/85913052-0d875700-b7f7-11ea-9c22-93a4990a1f44.jpg)
![enb2020_6_26_21_47_07](https://user-images.githubusercontent.com/19911571/85913053-0e1fed80-b7f7-11ea-9d02-6959b2e70b38.jpg)
![enb2020_6_26_21_47_10](https://user-images.githubusercontent.com/19911571/85913054-0e1fed80-b7f7-11ea-84ec-431b17a49052.jpg)

**Additional context**
My suggestion would be just ditch JK's completely for this area unless you create or find significant patching in the CK or something, I dunno.

**Comment by Schnipserle** [comment]
Some has created a patch for JK's Skyrim and The Great Town of Ivarstead. I haven't tested it yet.

[https://www.nexusmods.com/skyrimspecialedition/mods/36380](url)

**Comment by ForgottenGlory** [comment]
Should be fixed v2.0.1

**Comment by tjbassoon** [comment]
This issue is present in the current version 2.2.1
