### ISSUE TITLE
Many sets of armor/weapons show up invisible at forge and when equipped.

### ISSUE THREAD

**Issue by Volkaru** [ForgottenGlory/Living-Skyrim-2#233]
**LS Version**
2.0.0 Beta 7 RC1

**Describe the bug**
Multiple craftable armor sets as well as some weapons show up invisible in the menu, and when equipped show up invisible, as well. When dropped NPCs can interact with them, but I cannot see nor interact with the object. Biggest culprit is the entire Ranger set. Screenshot attached.

**To Reproduce**
Steps to reproduce the behavior: Go to a forge on any save and try to make the ranger attire set, or scroll through the lists, you will see various sets invisible on preview.

**Expected behavior**
Crafted set should apear in the preview at the forge, and on characters.

**Screenshots**

![enb2020_6_29_17_30_53](https://user-images.githubusercontent.com/9113384/86255759-5e3adf00-bb6c-11ea-81c1-b7738a2aed94.png)
![enb2020_6_29_17_31_17](https://user-images.githubusercontent.com/9113384/86255773-61ce6600-bb6c-11ea-823c-18ff041919d2.png)

**Comment by ForgottenGlory** [comment]
Fixed v2.0.1
