### ISSUE TITLE
Visage of Mzund bugged

### ISSUE THREAD

**Issue by AwesomeJames2120** [ForgottenGlory/Living-Skyrim-2#235]
![image](https://user-images.githubusercontent.com/44416823/86499007-04385480-bdcc-11ea-882f-336cd4c9b2c4.png)
Upon equipping the visage of mzund, it is completely invisible. 
![image](https://user-images.githubusercontent.com/44416823/86499044-4366a580-bdcc-11ea-9983-12d7d1ed8f40.png)
It is only visible on beast races and orcs, but instead it uses the improved closefaced helmets version of the dwarven helmet, instead of the intended look
![image](https://user-images.githubusercontent.com/44416823/86499093-8aed3180-bdcc-11ea-9653-daabf9e81b24.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
