### ISSUE TITLE
Minor - Big fallen tree blocking road to Windhelm

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#236]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Official Release 

**Describe the bug**
Large fallen tree blocking road to Windhelm from west

**To Reproduce**
Reloaded save several times

**Expected behavior**
Not expecting a big tree, unless it's a conscious decision to have been placed there?

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot269](https://user-images.githubusercontent.com/67298916/86506883-6d967400-bd88-11ea-8b61-3c1d5c002c9b.png)
![ScreenShot270](https://user-images.githubusercontent.com/67298916/86506884-6e2f0a80-bd88-11ea-9d4d-0e182126b734.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
