### ISSUE TITLE
Belethor Black Face Bug

### ISSUE THREAD

**Issue by measlesbagel** [ForgottenGlory/Living-Skyrim-2#237]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.0

**Describe the bug**
Belethors face skin color is very dark, doesnt match the rest of his body

**To Reproduce**
Find Belethor

**Expected behavior**
Belethors body color to match his face

**Screenshots**
![ScreenShot267](https://user-images.githubusercontent.com/49631653/86507266-ea374b80-bda4-11ea-9326-b6713929eda4.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
