### ISSUE TITLE
Cannibalism changes aren't forwarded from RoM

### ISSUE THREAD

**Issue by PKYxReGiGiGaSx** [ForgottenGlory/Living-Skyrim-2#238]
Living Skyrim 2

Gameplay Merge.esp is not forwarding the changes to cannibalism from Reliquary of Myth.

![RoM_BugReport](https://user-images.githubusercontent.com/62578629/86507449-265eb200-bd8d-11ea-9c23-708dc00a2794.png)

**Comment by ForgottenGlory** [comment]
Can't fix this unless I know what record it is, please provide the FormID of the record in question.

**Comment by PKYxReGiGiGaSx** [comment]
DA11Cannibalism is a vanilla record and only a few perk records are edited by the Gameplay Merge.esp.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
