### ISSUE TITLE
Floating flora outside DBM in solitude

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-2#239]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0

**Describe the bug**
Some plants from JK's skyrim are floating around where the museum is

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make 
![enb2020_7_4_07_38_45](https://user-images.githubusercontent.com/19911571/86513337-06e87900-bdcf-11ea-8fdd-d152b246ee1d.png)
sure it is selected with the console open. Reports without this will be closed.

**Additional context**
Putting LOTD Patches Merged below JK's Skyrim Patches solves the problem.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
