### ISSUE TITLE
Ancient Nordic Dagger Texture Stretched

### ISSUE THREAD

**Issue by electraumatized** [ForgottenGlory/Living-Skyrim-2#240]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS 2.0

**Describe the bug**
Texture on the Ancient Nordic Dagger seems like it is stretched.

**To Reproduce**
Acquire Ancient Nordic Dagger

**Expected behavior**
Texture does not look stretched.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![enb2020_7_4_12_21_27](https://user-images.githubusercontent.com/66895387/86518105-1c23ce80-bdf4-11ea-83ac-fbbf11526c71.jpg)
![enb2020_7_4_12_21_41](https://user-images.githubusercontent.com/66895387/86518107-1ded9200-bdf4-11ea-8ce8-47ca039ac2dc.jpg)

**Additional context**
Probably unrelated bu the dagger floated when dropped and I was unable to pick it up again.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
