### ISSUE TITLE
Snow looks a bit different.

### ISSUE THREAD

**Issue by JoutenAsero** [ForgottenGlory/Living-Skyrim-2#241]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.0

**Describe the bug**
Snow seems to be mismatched outside Bleak Falls Barrow

**To Reproduce**
Just stepping outside and looking around

**Expected behavior**
I didn't expect the snow to be so drastically different.

**Screenshots**
![image](https://user-images.githubusercontent.com/67838492/86518214-ca804180-bdfd-11ea-8404-4324fab133b8.png)

![image](https://user-images.githubusercontent.com/67838492/86518224-e683e300-bdfd-11ea-8474-0f05bfbc4bdf.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Stupid bot. I'll look into this but don't think I can fix it.

**Comment by JoutenAsero** [comment]
Aw poo.  If there's anything you think I could look into, please tell me.

**Comment by CuL8Rg8r** [comment]
I'm having this issue as well with 2.4.0 - Looks like the snow normals are missing/everything looks flat and blocky. I too would love to hear if there's a fix for it that someone knows about. Cheers!
