### ISSUE TITLE
Belethor Black Face

### ISSUE THREAD

**Issue by epierrej** [ForgottenGlory/Living-Skyrim-2#242]
**LS Version**
2.0.0

**Describe the bug**
Belethor has the blackface error

**Screenshots**
![ScreenShot267](https://user-images.githubusercontent.com/23179930/86524156-a2fc9980-be3c-11ea-85be-19eea488a7be.png)

**Save File**
[Save18_68AB3C4B_0_456772696D6D_WhiterunBelethorsGeneralGoods_000233_20200705022200_4_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4874304/Save18_68AB3C4B_0_456772696D6D_WhiterunBelethorsGeneralGoods_000233_20200705022200_4_1.zip)

**Comment by TwistedModding** [comment]
this is a duplicate of post #237

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
