### ISSUE TITLE
Belrand BFB

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-2#243]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0

**Describe the bug**

Ref ID
000B9988
Base ID
000B9981

**To Reproduce**

**Expected behavior**

**Screenshots**
![enb2020_7_4_16_44_43](https://user-images.githubusercontent.com/19911571/86525545-1064f600-be4e-11ea-8c38-ffd936a9eff0.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
