### ISSUE TITLE
Major errors in plugins from xEdit & Load Order Issue

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim-2#244]
**LS Version**
2.0.0

**Describe the bug**
1) Lots of plugins are reporting errors where they can't resolve stuff or things having the wrong tags.
2) Guards Armor Replacer is loaded below Bashed Patch but its a master for it. If following the instructions from the mod author its to disable GAR for bash then load it below.

**Additional context**
Player Homes Merged
![image](https://user-images.githubusercontent.com/5535758/86533467-19b09a00-bf04-11ea-956d-80cdd2c44244.png)

Weapons Merged
![image](https://user-images.githubusercontent.com/5535758/86533475-29c87980-bf04-11ea-88cc-7efa81671dd5.png)

Armors Merged
![image](https://user-images.githubusercontent.com/5535758/86533484-351ba500-bf04-11ea-9545-7eac43d267e4.png)

NPC Additions Merged
![image](https://user-images.githubusercontent.com/5535758/86533515-57adbe00-bf04-11ea-93f4-a7cfa221e3df.png)

JK's Patches Merged
![image](https://user-images.githubusercontent.com/5535758/86533548-8c217a00-bf04-11ea-9d58-749314a8d3f8.png)

Settlements Merged
![image](https://user-images.githubusercontent.com/5535758/86533562-a4919480-bf04-11ea-9b25-e143df51f555.png)

Miscellaneous Patches Merged
![image](https://user-images.githubusercontent.com/5535758/86533578-bb37eb80-bf04-11ea-88a2-61175c2e7f6e.png)

LS2 Patches Merged
too big to list it all. 119 errors
![image](https://user-images.githubusercontent.com/5535758/86533594-d0ad1580-bf04-11ea-8a90-64050ddd189c.png)

Bashed Patch
![image](https://user-images.githubusercontent.com/5535758/86533608-e02c5e80-bf04-11ea-963f-18e0779ab2c2.png)

**Comment by ForgottenGlory** [comment]
I've fixed a huge number of these, but am still working on it.

**Comment by ForgottenGlory** [comment]
Round 2 of fixes for this coming in 2.0.3
