### ISSUE TITLE
Scorpion Scimitar - Wrong Mesh/Texture 

### ISSUE THREAD

**Issue by jtmoney412** [ForgottenGlory/Living-Skyrim-2#245]
**LS Version** 
2.0.0

**Describe the bug**
The Scorpion Scimitar has the wrong mesh/texture - see photos below. In the inventory and when sheathed it's showing an axe/hammer. It's invisible when equipped, but it shows the right model while on the ground. 

**To Reproduce**
View the Scorpion Scimitar in you inventory, when sheathed, when equipped, and on the ground.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
Unrelated - my apologies for not creating a second bug report - but Aldavinur Félagi constantly walks into this tree (screenshot below) outside of Sleeping Giant Inn. His rags are also clipping with his calves.

![Aldavinur Félagi - Console](https://user-images.githubusercontent.com/62395499/86538060-99694500-bec1-11ea-8eca-8cd79a6e81a0.png)
![Aldavinur Félagi](https://user-images.githubusercontent.com/62395499/86538062-9b330880-bec1-11ea-8fa4-c67228d3f47c.png)
![Scorpion Scimitar - Equiping](https://user-images.githubusercontent.com/62395499/86538064-9d956280-bec1-11ea-9978-e70a20c42a98.png)
![Scorpion Scimitar - Ground Console](https://user-images.githubusercontent.com/62395499/86538066-9f5f2600-bec1-11ea-8089-f871a0112a44.png)
![Scorpion Scimitar - Inventory](https://user-images.githubusercontent.com/62395499/86538067-a128e980-bec1-11ea-801f-85af9f0a8b3e.png)
![Scorpion Scimitar - Sheathed](https://user-images.githubusercontent.com/62395499/86538068-a25a1680-bec1-11ea-9d2d-27a01af59d83.png)

**Comment by ForgottenGlory** [comment]
Scimitar fixed 2.0.1

**Comment by ForgottenGlory** [comment]
Aldavinur maybe fixed 2.0.1, let me know.
