### ISSUE TITLE
enabling widescreen fixes goes above plugin limit.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#246]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.0

**Describe the bug**
enabling widescreen fixes goes above plugin limit. unloading dyndolod

**To Reproduce**
enable widescreen fixes.

**Expected behavior**
dyndolod not unloading, reduce plugin limit by however much required.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
Solution would be to eslify however many plugins needed or re-create a merge.

**Comment by ForgottenGlory** [comment]
Fixed v2.0.1
