### ISSUE TITLE
MCM Settings recommendation.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#247]
Wildcat combat and Ultimate combat both have a "timed block" feature which do the same thing. 

The problem is that under the shield perks for ordinator there is a perk called "Timed Block" as well which does the same thing as the  rest of the mods mentioned. My suggestion would to be disable timed block in wildcat and ultimate combat through the mcm settings so that the shield perk is actually useful.

**Comment by ForgottenGlory** [comment]
Agreed, will update MCM settings v2.0.1
