### ISSUE TITLE
CTD Serpent's Bluff Redoubt.

### ISSUE THREAD

**Issue by SibSama** [ForgottenGlory/Living-Skyrim-2#248]
Fresh Install of Skyrim SE and Living Skyrim 2.0.0.

When entering Serpent's Bluff Redoubt i get a CTD. It happens about 50% of the time.

To reproduce simply walk towards the front entrance (east side) near forsworn archer. 
[Crash_2020_7_5_20-23-9.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4875439/Crash_2020_7_5_20-23-9.txt)
![20200705202224_1](https://user-images.githubusercontent.com/67875291/86540522-fa167300-befd-11ea-845d-55d0d2e843bb.jpg)

GitHub won't let me upload my saves so i put them on [Google Drive](https://drive.google.com/drive/folders/1XWqyQjmubayHQffrFh-vt79N6GUM3UoZ?usp=sharing)

System specs:
I9 9900k 5GHz
2080ti
32 GB DDR4
Game installed on SSD

**Comment by TwistedModding** [comment]
Looking at the crashlog it looks like it has something to do with the hedgemagecamp which is known. This will be fixed most likely in the next update.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
