### ISSUE TITLE
Tree inside shed in Rorikstead

### ISSUE THREAD

**Issue by electraumatized** [ForgottenGlory/Living-Skyrim-2#249]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS 2.0

**Describe the bug**
Tree is growing through the middle of a shed in Rorikstead

**To Reproduce**
Go to Rorikstead

**Expected behavior**
No tree inside of the shed

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot278](https://user-images.githubusercontent.com/66895387/86544482-e6aedc00-beec-11ea-91aa-4e571ef017b7.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
