### ISSUE TITLE
Major fence clipping in riverwood.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#250]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.0

**Describe the bug**
Two fences clipping at hod's and sigrid's house

**To Reproduce**
go to riverwood

**Expected behavior**
The stone wall to be gone leaving the wood fences by themselves for npcs to enter and exit.

**Screenshots**
![ScreenShot273](https://user-images.githubusercontent.com/62785432/86611365-31276b80-bf74-11ea-8490-3aa35dc4db60.png)
![ScreenShot274](https://user-images.githubusercontent.com/62785432/86611368-32589880-bf74-11ea-8f28-25bb14834c74.png)
![ScreenShot275](https://user-images.githubusercontent.com/62785432/86611372-34225c00-bf74-11ea-91f0-44d73d26766a.png)
![ScreenShot276](https://user-images.githubusercontent.com/62785432/86611377-35538900-bf74-11ea-8a49-c1eb9cc42d38.png)
![ScreenShot277](https://user-images.githubusercontent.com/62785432/86611382-371d4c80-bf74-11ea-83fe-577ff5effd8f.png)
![ScreenShot278](https://user-images.githubusercontent.com/62785432/86611389-38e71000-bf74-11ea-9b56-5ce4a3607e4a.png)
![ScreenShot279](https://user-images.githubusercontent.com/62785432/86611393-3a183d00-bf74-11ea-9885-fbded1dbdbb1.png)
![ScreenShot280](https://user-images.githubusercontent.com/62785432/86611401-3b496a00-bf74-11ea-98d4-4fa37a0e7188.png)
![ScreenShot281](https://user-images.githubusercontent.com/62785432/86611404-3c7a9700-bf74-11ea-92a1-c4e7f1135d82.png)
![ScreenShot282](https://user-images.githubusercontent.com/62785432/86611408-3dabc400-bf74-11ea-9ff2-9a5ea7c4eda9.png)
![ScreenShot283](https://user-images.githubusercontent.com/62785432/86611411-3edcf100-bf74-11ea-924b-74192046a85d.png)
![ScreenShot284](https://user-images.githubusercontent.com/62785432/86611416-400e1e00-bf74-11ea-989f-74f2b4f15377.png)
![ScreenShot285](https://user-images.githubusercontent.com/62785432/86611421-413f4b00-bf74-11ea-9200-d78995d2312d.png)
![ScreenShot286](https://user-images.githubusercontent.com/62785432/86611428-42707800-bf74-11ea-8a0b-99d504e4a613.png)
![ScreenShot287](https://user-images.githubusercontent.com/62785432/86611431-43a1a500-bf74-11ea-9ae3-079a304e3389.png)
![ScreenShot288](https://user-images.githubusercontent.com/62785432/86611432-44d2d200-bf74-11ea-8785-fdd6127bcd52.png)
![ScreenShot289](https://user-images.githubusercontent.com/62785432/86611439-4603ff00-bf74-11ea-939b-0656ec1c7e80.png)
**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.1
