### ISSUE TITLE
FEC not working unless manually unhidden via MO2

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#251]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.01 

**Describe the bug**
Frozen Electrocuted Combustion (FEC) is still not applying its effects to corpses/killed enemies unless the esp is unhidden via Mod Organizer, which leads to two FEC menus in the ingame MCM.

**To Reproduce**
Used Flames, Frostbite, and Sparks on corpses and bandits. Effects were not applied until the esp was unhidden and the game was reloaded.

**Expected behavior**
FEC to work without unhiding the esp.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Unmerging it first would be better as you won't get two mcm settings.

**Comment by jokerstyle00** [comment]
Unsure which merge has it, let alone how to safely unmerge mods in a list this complex.

**Comment by TwistedModding** [comment]
For Glory:  
The esp is called "Fireburns.esp" and is in the merge "Graphics Merged" 
I recommend to eslify another plugin to make room for it in the list. I turned the Landscape for Grass Mods patches into esls for room. 

Can confirm that this fix works as I'm right at the plugin limit still while getting the animations from FEC.

**Comment by powerof3** [comment]
FEC author here, please don't merge the esp. The included FEC.dll requires formIDs to be intact so it can apply effects to NPCs.

**Comment by ForgottenGlory** [comment]
Thanks for the heads up! That's my mistake, I'll fix in the next update.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
