### ISSUE TITLE
Hadvar BFB

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#252]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2

**Describe the bug**
bfb on hadvar

**To Reproduce**
find hadvar

**Expected behavior**
no bfb

**Screenshots**
![ScreenShot270](https://user-images.githubusercontent.com/62785432/86678471-37443900-bfc2-11ea-984d-0e61c20fae48.png)

**Additional context**

**Comment by halgari** [comment]
![ScreenShot276](https://user-images.githubusercontent.com/654621/87213863-5bb35480-c2e5-11ea-9741-1b388fb999c3.png)
From my install

**Comment by jchritton** [comment]
![ScreenShot270](https://user-images.githubusercontent.com/18075641/87259767-44a26d00-c473-11ea-9ef2-0c5b5c546bd5.png)

Same from mine if there's more examples needed.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
