### ISSUE TITLE
MCM Locational Damage/poise disable

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#253]
I would suggest to disable staggering/pose effects on player and NPC (or at least on npc as it makes archery very very strong for stun locking everything.) 

Ultimate Combat:
Under the stagger section 
-Disable Enemy Poise 
- Disable Player Stagger
-NPC's Bow Poise: 0
-Player;s Bow Poise: 0
Under the Locational Damage section
-Headhsot Damage Mult: 0
-Headshot Message disabled
-Locational Damage Sound disabled
-Location Damage Effect Disabled.

This will make archery still strong but weaker in 1 on 1 situations where you can forever stun lock an enemy by hitting them in the head with poise.

**Comment by ForgottenGlory** [comment]
Incorporated for 2.0.2 update
