### ISSUE TITLE
Viking Shield Missing texture when on back.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#255]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.0

**Describe the bug**
Viking Shield Missing texture when on back.

**To Reproduce**
Spawn in/find the shield, equip it then sheath your weapons. 

**Expected behavior**
Correct Texture.

**Screenshots**
![ScreenShot274](https://user-images.githubusercontent.com/62785432/86874221-9a5acc00-c0a5-11ea-9a59-a925351b6188.png)
![ScreenShot275](https://user-images.githubusercontent.com/62785432/86874222-9b8bf900-c0a5-11ea-9d3c-40fe13853096.png)
![ScreenShot272](https://user-images.githubusercontent.com/62785432/86874226-9d55bc80-c0a5-11ea-89c8-1f9ec91a9960.png)
![ScreenShot273](https://user-images.githubusercontent.com/62785432/86874230-9e86e980-c0a5-11ea-9b98-4e33febaaf32.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed 2.0.2, followup on this.

**Comment by TwistedModding** [comment]
Just looked back on this, fixed.
