### ISSUE TITLE
Stenvarr BFB

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#256]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Stenvarr has the BFB

**To Reproduce**
Go to Candlehearth Hall in Windhelm and find Stenvarr.

**Expected behavior**
No BFB

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
