### ISSUE TITLE
Floating Terrain near Velothi Mountain Tunnel

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#258]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Several pieces of floating terrain.

**To Reproduce**
Go to Velothi Mountain Tunnel and look towards the left when facing the dungeon entrance.

**Expected behavior**
No floating terrain.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot271](https://user-images.githubusercontent.com/67993113/86980766-5b328680-c14a-11ea-9904-41980a476fa2.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Bug reports like this need to have a screenshot of the object selected in console so I can get the FormID. Will fix once I have that.

**Comment by baldone98** [comment]
![ScreenShot274](https://user-images.githubusercontent.com/67993113/87358702-fa30f700-c52b-11ea-9c5d-8a0e8a0e3e87.png)
![ScreenShot275](https://user-images.githubusercontent.com/67993113/87358709-fbfaba80-c52b-11ea-9ac0-9492963ea206.png)
![ScreenShot276](https://user-images.githubusercontent.com/67993113/87358714-fd2be780-c52b-11ea-8028-0286e0c77d92.png)
![ScreenShot277](https://user-images.githubusercontent.com/67993113/87358716-fdc47e00-c52b-11ea-88de-f70fc8a3d71b.png)
![ScreenShot273](https://user-images.githubusercontent.com/67993113/87358718-fe5d1480-c52b-11ea-980d-a9bd6877b9ac.png)

Sorry about that. I believe I found them all in that area.

**Comment by ForgottenGlory** [comment]
Thank you! Fixed 2.1.0
