### ISSUE TITLE
Marcurio BFB

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-2#259]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v2.0.1

**Describe the bug**
Marcurio has the BFB.

**To Reproduce**
N/A. Upon entering Bee and Barb, Marcurio has BFB.

**Expected behavior**
N/A

**Screenshots**

![ScreenShot269](https://user-images.githubusercontent.com/67465410/87032276-fb6bc800-c1a9-11ea-93f4-ffc72105edc7.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
