### ISSUE TITLE
Brynjolf BFB

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-2#260]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v2.0.1

**Describe the bug**
Brynjolf has BFB.

**To Reproduce**
N/A. Upon entering Riften market, Brynjolf has BFB. 

**Expected behavior**
N/A

**Screenshots**
![ScreenShot270](https://user-images.githubusercontent.com/67465410/87033165-594cdf80-c1ab-11ea-9d87-89109b011348.jpg)

**Additional context**

**Comment by jokerstyle00** [comment]
Would also like to add that Mercer also has the BFB.

![ScreenShot288](https://user-images.githubusercontent.com/67298916/87098563-71991a80-c1fc-11ea-913f-2b4c064b3afc.png)
![ScreenShot289](https://user-images.githubusercontent.com/67298916/87098564-72ca4780-c1fc-11ea-9da2-5f58e9cb6570.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
