### ISSUE TITLE
Player Cannot Steal Argonian Ale

### ISSUE THREAD

**Issue by ScipioAsina** [ForgottenGlory/Living-Skyrim-2#261]
**LS Version**
v2.0.1

**Describe the bug**
The player cannot steal the Argonian Ale from The Bannered Mare in Whiterun, since: (1) the new sliding door on the cupboard blocks direct access to it; and (2) the "Order Meal" action seems to interfere with the player's ability to pick up the bottle, even when in no-clip mode.

**To Reproduce**
See above.

**Expected behavior**
In vanilla, the player can simply pick the Argonian Ale off the shelf.

**Screenshots**
![argonianale01](https://user-images.githubusercontent.com/68080473/87084147-98e2ee00-c1e2-11ea-898e-7e44b1a17f0f.jpg)
![argonianale02](https://user-images.githubusercontent.com/68080473/87084163-a009fc00-c1e2-11ea-9ad1-28c1d8e1c66d.jpg)

**Additional context**
N/A.

**Comment by JulesMarz** [comment]
You can get it, but its a pain in the arse

**Comment by ForgottenGlory** [comment]
All you have to do to pick it up is start sneaking and activate the ale.
