### ISSUE TITLE
Werewolf Companions are still invisible during their cutscenes

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#262]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Ver 2.01 

**Describe the bug**
During the Companions questline, there are two instances in which two Companions (Farkas and Aela) transform into werewolves. Both characters are invisible in their werewolf forms.

**To Reproduce**
In Proving Honor, I reloaded the scene where Farkas transforms three times, exiting to Desktop in between loads. Farkas is still invisible. When your character is prompted to meet at the Underforge to become a werewolf, Aela is invisible as well.

**Expected behavior**
Farkas and Aela to not be invisible werewolves.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

This is a documented issue with Diverse Werewolves interacting with NPC replacers that touch Farkas and Aela, or add "naked armor" to characters.

https://forums.nexusmods.com/index.php?/topic/918478-what-might-be-causing-werewolf-companion-to-be-invisible/

**Comment by ForgottenGlory** [comment]
Possibly fixed 2.0.2, followup on this
