### ISSUE TITLE
PC is invisible in 3rd person

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#263]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_7_7_14-36-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4899954/Crash_2020_7_7_14-36-5.txt)
[Crash_2020_7_7_19-18-59.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4899955/Crash_2020_7_7_19-18-59.txt)
(one of these is the crash log, but I don't recall which one was related to the bug.)

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Save23_219CE3B5_0_4D696E65727661_Tamriel_000333_20200709230237_5_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4899928/Save23_219CE3B5_0_4D696E65727661_Tamriel_000333_20200709230237_5_1.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1.

**Describe the bug**
Character is completely invisible when in 3rd person. The last time I checked I tried to remove a piece of armor to see if that would fix it but the game CTD instead. 1st person seems fine but the it looks like the PC is still carrying the sword instead of it being sheathed. I don't know if these two are related or not.

**To Reproduce**
Not quite sure how to reproduce, but I think there could be a connection with drawing and sheathing weapons.

**Expected behavior**
To be able to see my PC when in 3rd person

**Screenshots**
![ScreenShot272](https://user-images.githubusercontent.com/67993113/87099794-50422980-c210-11ea-9999-3c1af00445e3.png)
(This was me trying to zoom as far as possible while in third person.)

**Additional context**

**Comment by DrNomienom** [comment]
I was able to reproduce the bug three times. I had an Ancient Noridc Boradsword equipped on my right hand and the orcish shield on my left hand. If I go into 3rd person and unsheathe my weapon and resheathe it, the PC continues to hold the weapon. Then I go into 1st person and immediately after going into 3rd person the PC becomes invisible. Unequipping gear afterwards doesn't cause a CTD, but equipping any gear does.

**Comment by ixanza** [comment]
> I was able to reproduce the bug three times. I had an Ancient Noridc Boradsword equipped on my right hand and the orcish shield on my left hand. If I go into 3rd person and unsheathe my weapon and resheathe it, the PC continues to hold the weapon. Then I go into 1st person and immediately after going into 3rd person the PC becomes invisible. Unequipping gear afterwards doesn't cause a CTD, but equipping any gear afterward does.

This error seems to be related to Ultimate Combat and AllGUD somehow. I find that disabling the Swing Effect in Ultimate Combat makes this go away altogether

**Comment by ForgottenGlory** [comment]
As Xanza mentioned, this can be prevented by disabling the Swing Effects in Ultimate Combat. I'll be updating the MCM document to reflect this (with some other changes) for the 2.0.3 update.
