### ISSUE TITLE
Misplaced Door Dawnguard

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#264]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Misplaced Door Dawnguard

**To Reproduce**
Look at main dawnguard fortress door

**Expected behavior**
Correctly placed door.

**Screenshots**
![ScreenShot277](https://user-images.githubusercontent.com/62785432/87114742-f99c1600-c236-11ea-8571-c302223efa5f.png)
![ScreenShot278](https://user-images.githubusercontent.com/62785432/87114744-facd4300-c236-11ea-89b4-34ecafd8eb2d.png)

**Additional context**

**Comment by DutchGuyTom** [comment]
Experienced the same issue today. There is also a floating door outside on the rooftop area of Dawnguard.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
