### ISSUE TITLE
Golldir BFB

### ISSUE THREAD

**Issue by AwesomeJames2120** [ForgottenGlory/Living-Skyrim-2#266]
![image](https://user-images.githubusercontent.com/44416823/87133161-497fe900-c2da-11ea-9bbc-c0e3430533bb.png)
![image](https://user-images.githubusercontent.com/44416823/87133192-51d82400-c2da-11ea-860f-f2937df3dba3.png)
As you can see from the images provided, Golldir from the ancestral worship quests face is broken. This is an issue because he is very cute

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
