### ISSUE TITLE
Serana from Dawnguard teleports you after fast traveling away.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#267]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Serana from Dawnguard teleports you after fast traveling away after giving her to Harkon for the first time.

**To Reproduce**
Find serana, return her to Harkon and fast travel anywhere and she'll teleport to you.

**Expected behavior**
For her to remain at Castle Volkihar and not follow the PC when fast traveling.

**Screenshots**
![ScreenShot279](https://user-images.githubusercontent.com/62785432/87175582-76aea600-c29e-11ea-849e-5cd7b5f2c7dc.png)

**Additional context**
After fast traveling she will just start walking away (I would assume back towards castle volkihar)

**Comment by TwistedModding** [comment]
She seems to just teleport to you whenever you switch to a new cell.

**Comment by ForgottenGlory** [comment]
Does she continue to do it if you dismiss her from the Follower Framework?

**Comment by TwistedModding** [comment]
Haven't tested that yet, probably will fix it as I had that same suspicion while I was playing. Will give it a go once my list updates.

**Comment by TwistedModding** [comment]
Just started doing dawnguard again and removing her from the framework seemed to fix it. She longer teleports to me when she’s not suppose to.
