### ISSUE TITLE
Ravenscar Hollow is overtuned

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim-2#270]
**LS Version**
2.0.1

**Describe the bug**
Creatures in Ravenscar hollow are level 50-158  (Bandits are 50, Hagravens are 158) while the sabrecat guarding this place is level 9. There's a huge level disparity here

**To Reproduce**
Walk in

**Expected behavior**
Reasonably leveled

**Screenshots**
![ScreenShot272](https://user-images.githubusercontent.com/5535758/87214250-8f31c580-c35d-11ea-978c-4fb75db60a31.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
