### ISSUE TITLE
Lighting Issue

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-2#273]
seem to have lighting issues around certain areas, attached screenshots some with ENB turned off(to know its not an ENB fault) 
![20200711232835_1](https://user-images.githubusercontent.com/68168803/87236215-1de62700-c3de-11ea-8ed6-ab06ee946a0c.jpg)
![20200711232837_1](https://user-images.githubusercontent.com/68168803/87236216-1e7ebd80-c3de-11ea-804c-fe5ce8610e93.jpg)
![20200711230346_1](https://user-images.githubusercontent.com/68168803/87236218-30606080-c3de-11ea-915b-778015e4f716.jpg)
![20200711231549_1](https://user-images.githubusercontent.com/68168803/87236222-36eed800-c3de-11ea-82dc-8b66284f23bc.jpg)
![20200711231717_1](https://user-images.githubusercontent.com/68168803/87236223-37876e80-c3de-11ea-8663-489d11b624b4.jpg)

**Comment by daffodilian** [comment]
Fairly certain this is just the issue that SSE's engine has with too many lightsources.
