### ISSUE TITLE
BFB for Vorstag

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#276]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.01 

**Describe the bug**
Vorstag, a hireling at Silverblood Inn within Markarth has the BFB

**To Reproduce**
Go to Silverblood Inn and find Vorstag

**Expected behavior**
No BFB

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot294](https://user-images.githubusercontent.com/67298916/87243249-6820d580-c3e9-11ea-856b-abc895d65608.png)
![ScreenShot293](https://user-images.githubusercontent.com/67298916/87243250-68b96c00-c3e9-11ea-960a-6198c3a5a189.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
