### ISSUE TITLE
Odin Awakened Sword - mounting = crash

### ISSUE THREAD

**Issue by rb-evans** [ForgottenGlory/Living-Skyrim-2#277]
Getting a consistent crash when trying to mount my awoken odin's sword on a plaque. noticed crashes a few other times when equipping/unequipping.

**Comment by ForgottenGlory** [comment]
Fill out a proper bug report template.

**Comment by rb-evans** [comment]
Didn't realize there were templates, didn't see the tutorial. Will leave
you to it, was just trying to help.
