### ISSUE TITLE
Mirai follower gets stuck during her dating quest at Ivarstead

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#278]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Ver 2.01 

**Describe the bug**
After going through all of her dialogue during the date at Ivarstead, Mirai becomes unresponsive and any attempts to interact with her result in "This person is busy" popping up in the top left corner. 

**To Reproduce**
Take Mirai on her date to Ivarstead. Go through all of her options until she remarks "You're stuck with me now, got it?". She will then become unresponsive, and even using her debug book won't fix her.

**Expected behavior**
Mirai's quest to complete without her becoming unresponsive.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

Apparently it's an incompatibility with any mods that change the bridges in Ivarstead, as her date is supposed to end on the bridge, with Mirai looking at the distance.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
