### ISSUE TITLE
Afflicted Refugee has floating helmet

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#279]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.01

**Describe the bug**
A randomly encountered Afflicted (non-hostile, directs players to the starting point of the Spellbreaker quest), has a floating helment.

**To Reproduce**

**Expected behavior**
Helmet to stay on head

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot301](https://user-images.githubusercontent.com/67298916/87275699-893e0080-c493-11ea-86d9-f6df7dab4de4.png)
![ScreenShot302](https://user-images.githubusercontent.com/67298916/87275700-89d69700-c493-11ea-909d-318a1cf5e08c.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
