### ISSUE TITLE
No animation for enchant on Eltonbrand

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim-2#28]
Eltonbrand from Artifacts - The Tournament of the Ten Bloods [[SSE]](https://www.nexusmods.com/skyrimspecialedition/mods/15264?) , is just showing a static effect for its enchant, instead of being animated.

![ScreenShot189](https://user-images.githubusercontent.com/63564258/82371391-1b6fde00-99e8-11ea-8938-c16f3de78dfa.png)
![ScreenShot188](https://user-images.githubusercontent.com/63564258/82371394-1d39a180-99e8-11ea-94ec-e2bf0d29e699.png)

**Comment by ForgottenGlory** [comment]
I think this is just a minor bug with the item itself, as mentioned it tends to fix itself eventually.
