### ISSUE TITLE
Conjure Skeleton tome has huge wall of text and seems to do nothing

### ISSUE THREAD

**Issue by jokerstyle00** [ForgottenGlory/Living-Skyrim-2#280]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.01 

**Describe the bug**
The spell tome for Conjure Skeleton has a massive amount of text in its description and when cast, does absolutely nothing.

**To Reproduce**
Find the tome by the Ritual Stone

**Expected behavior**
The tome to have a normal description and to function

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot300](https://user-images.githubusercontent.com/67298916/87275805-c904e800-c493-11ea-9af1-8d0dd3bc13b3.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2, this book shouldn't have appeared.
