### ISSUE TITLE
BFB for Benor

### ISSUE THREAD

**Issue by jchritton** [ForgottenGlory/Living-Skyrim-2#281]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Benor (in Morthal) experiences blackface bug

**To Reproduce**
* Find Benor in Morthal

**Expected behavior**
NPC should not have blackface

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![benor-ingame](https://user-images.githubusercontent.com/18075641/87346542-710fc500-c517-11ea-8165-309f6d41fd05.png)

![benor-debug](https://user-images.githubusercontent.com/18075641/87346562-753be280-c517-11ea-9cc7-ea7161016459.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
