### ISSUE TITLE
BFB for Belrand

### ISSUE THREAD

**Issue by jchritton** [ForgottenGlory/Living-Skyrim-2#282]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
Belrand (Winking Skeever, Solitude) experiences blackface bug

**To Reproduce**
* Find Belrand in Solitude (usually the Winking Skeever)

**Expected behavior**
NPC should not have blackface

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![belrand-ingame](https://user-images.githubusercontent.com/18075641/87347205-6efa3600-c518-11ea-8acd-4ab686203442.png)

![belrand-debug](https://user-images.githubusercontent.com/18075641/87347213-74578080-c518-11ea-9808-8d669a99b191.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.2
