### ISSUE TITLE
Male Imperial Wearing Dragon Carved (Heavy Set) in Embershard Mine at Level 4

### ISSUE THREAD

**Issue by AronaxAE** [ForgottenGlory/Living-Skyrim-2#284]
**LS2 v2.0.2**

He spawned somewhere in Embershard Mine wearing the Helmet and the Armour from the "Dragon Carved" heavy set. The helmet is worth 800 gold and the armour itself is worth 1500 gold (I am level 4).

I restarted the save at the beginning of the mine and he is still there, wearing the same armour.

![Capture](https://user-images.githubusercontent.com/19594452/87471267-98e15480-c60d-11ea-94aa-1641a29d8165.PNG)

**Comment by ForgottenGlory** [comment]
Fixed 2.1.0
