### ISSUE TITLE
Bandit with no armor equipped (naked in game)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#285]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.2

**Describe the bug**
Bandit with no armor equipped (naked in game)

**To Reproduce**
Maybe find this type of bandit?

**Expected behavior**
Bandit to be wearing armor

**Screenshots**
![ScreenShot270](https://user-images.githubusercontent.com/62785432/87478011-b226d880-c5ee-11ea-9f72-3d02eb8387e6.png)
![ScreenShot271](https://user-images.githubusercontent.com/62785432/87478821-0088a700-c5f0-11ea-8748-32176f1c3f82.png)
![ScreenShot272](https://user-images.githubusercontent.com/62785432/87478832-02526a80-c5f0-11ea-8bd0-7c945f606eeb.png)
![ScreenShot270](https://user-images.githubusercontent.com/62785432/87739503-a5001a00-c7a5-11ea-9a0e-26b288c0aaed.png)
![ScreenShot272](https://user-images.githubusercontent.com/62785432/87842436-1c9b7b00-c872-11ea-9888-521f31d650d5.png)

Additional Context
I will be adding on to this periodically when I find more bandits that are naked with only the console ss so no nudity will be shown.

**Comment by TwistedModding** [comment]
Investigating this a little bit and I used the command "showinventory" on the most recent one I just posted (afflicted refugee) and he doesn't even have any armor on him except dragon carver boots.

**Comment by ForgottenGlory** [comment]
Fixed 2.0.3
