### ISSUE TITLE
wall blocking exit at blue palace

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#288]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.02

**Describe the bug**

**To Reproduce**
go by the entrance of the blue palace and looking to the right should be door frame and when you go to it should say to skyrim 
**Expected behavior**
the wall not be there
![ScreenShot273](https://user-images.githubusercontent.com/66355096/87517649-c5fd2980-c644-11ea-9ec7-79df003a5ca2.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
The object selected is the entire Blue Palace - normally I'd just disable a wall like this but I don't want to disable the entire palace. Need some testers on this one please.

**Comment by tjbassoon** [comment]
OK, so this appears to be a conflict between Palaces Castled Enhanced (which is where the door frame comes from) and Legacy of the Dragonborn (which puts the walls back in the palace there and also behind said door frame)
![ScreenShot271](https://user-images.githubusercontent.com/19911571/87855588-ff50c600-c8de-11ea-8708-1ec9132aad2c.png)


You can disable that wall and walk through it or console tcl and walk through. You will exit to Skyrim, but the doorway puts you in a totally nonsensical location outside the palace on the cliff. There's no way to safely actually go into the rest of the map from there. If you turn around and re-enter Solitude, there's no door to do so, but you can do it, and it puts you into a location between two buildings you cannot escape from without console tcl.

So I'm not even sure where that door is supposed to go, or how this is meant to work. There is no exit to Skyrim in that location in vanilla, so I would suggest just removing the "doorway" completely. The geography of Solitude and the location of the Blue Palace doesn't make sense to have a door there anyway.
![ScreenShot271](https://user-images.githubusercontent.com/19911571/87855611-20191b80-c8df-11ea-9687-d2e701193ec8.png)
![ScreenShot272](https://user-images.githubusercontent.com/19911571/87855614-21e2df00-c8df-11ea-9f4e-dc6f45131808.png)

**Comment by ForgottenGlory** [comment]
Thanks for looking into it TJ, fixed 2.1.0
