### ISSUE TITLE
BFB

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#290]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.02

**Describe the bug**
there is a black face

**To Reproduce*go to mandach or whatever his name is in markarth prison 

**Expected behavior**
no black face
![SkyrimSE 2020-07-15 03-21-45](https://user-images.githubusercontent.com/66355096/87569705-244dfa80-c68d-11ea-9385-44f0e2c00f0b.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.3
