### ISSUE TITLE
BFB for Erandur

### ISSUE THREAD

**Issue by masqueradex** [ForgottenGlory/Living-Skyrim-2#291]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.2

**Describe the bug**
BFB for Erandur who is in Dawnstar, Windpeak Inn. 

**To Reproduce**
Enter Dawnstar then enter Windpeak Inn to find him. 

**Expected behavior**
No Black face

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![Erandur BF](https://user-images.githubusercontent.com/68194592/87579507-e2bc5000-c68a-11ea-8c87-4fe0471de072.png)
![Erandur Blackface](https://user-images.githubusercontent.com/68194592/87579530-ebad2180-c68a-11ea-9120-624c0c0a8a5a.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.0.3
