### ISSUE TITLE
BFB for Elder Othreloth

### ISSUE THREAD

**Issue by pccd26** [ForgottenGlory/Living-Skyrim-2#292]
**LS Version**
2.0.2

**Describe the bug**
BFB for Elder Othreloth

**To Reproduce**
I left Raven Rock and was headed towards Skaal Village, when I ran into Othreloth on the road, although I'm sure he usually hangs out in the temple in town or whatever.

**Expected behavior**
No BFB

![enb2020_7_14_07_19_37](https://user-images.githubusercontent.com/63027659/87616704-8f69f200-c6ca-11ea-8817-acd2f8cd36a3.jpg)
![enb2020_7_14_07_19_32](https://user-images.githubusercontent.com/63027659/87616706-91cc4c00-c6ca-11ea-9b2f-5f5d4f4cf0da.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 2.0.3
