### ISSUE TITLE
Everything resets after loading a  save

### ISSUE THREAD

**Issue by Rookzs** [ForgottenGlory/Living-Skyrim-2#293]
**LS Version**
Current one off of Wabbajack

**Describe the bug**
So I just installed LS2 from wabbajack. After creating a new character leaving prison any time you load a save it resets like you are creating a new character. You end up with no armor on it removes items you previously had in your inventory and quest you had. I had the same issue after installing last night for the first time so I uninstalled everything and did a clean install this morning and am having the same issues. 

**To Reproduce**
Steps to reproduce the behavior: loading from any save 

**Expected behavior**
I expected it to pick up where I had previously saved. Not starting over again.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by Rookzs** [comment]
resolved

**Comment by Slynoks** [comment]
Hi, can you tell me how you resolve this bug?

**Comment by TwistedModding** [comment]
dont add anything

**Comment by Slynoks** [comment]
really ? that bad :(
