### ISSUE TITLE
Head/body discoloration on Saffir

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#296]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.2

**Describe the bug**
Head/body discoloration on Saffir

**To Reproduce**
Find Saffir

**Expected behavior**
Consistent colors between head and body

**Screenshots**
![ScreenShot273](https://user-images.githubusercontent.com/62785432/87843539-02b26600-c87b-11ea-9dec-e1a2870489a3.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.0.3
