### ISSUE TITLE
Alpha 9 - Riverwood Navmesh issue by alchemist shop.

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#3]
Seems to be a conflict with whatever adds the alchemist shop.  There should be a path there.

**Comment by pgdeaner** [comment]
![image](https://user-images.githubusercontent.com/11461193/83317529-aae86e80-a1ea-11ea-8f17-c712da455ae9.png)

Just to illustrate why this is an issue, NPCs try to walk up the path to the shop and get stuck.

**Comment by ForgottenGlory** [comment]
Can someone please check this once Beta 5 is out to see if it's still an issue?

**Comment by pgdeaner** [comment]
The path is no longer blocked and my follower and an NPC were able to approach the shop.  I believe it is fixed based on this testing.
