### ISSUE TITLE
Searching Bodies in Werewolf Form After Consuming Makes Them Nude

### ISSUE THREAD

**Issue by AronaxAE** [ForgottenGlory/Living-Skyrim-2#301]
**LS Version**
2.0.2 & 2.1.0 (tested on both)

**Describe the bug**
While in Werewolf form, when looting a body after "consuming" them, they instantly become nude. All the armour stays in their inventory, but it just all disappears off their body.

**To Reproduce**
Become a Werewolf, consume an enemy and open their inventory either while consuming, or even after the animation is done.

**Expected behavior**
Searching a body as a werewolf after feeding should keep the armour on their bodies unless you manually take it off them.

**Screenshots**
Not sure how to screenshot this, but here is a picture (covered) of a body I searched after I consumed which just went completely nude.
![Capture](https://user-images.githubusercontent.com/19594452/87869826-595e9380-c992-11ea-8a41-372ba483eaa3.PNG)

**Comment by jokerstyle00** [comment]
I also got this bug on 2.02.
