### ISSUE TITLE
Tree blocking entrance to tower in Silent Moons Camp

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim-2#302]
**LS Version**
2.1.0

**Describe the bug**
There's a tree from dave's trees thats blocking an entrace to the left tower in Silent Moons Camp

**Screenshots**
![ScreenShot286](https://user-images.githubusercontent.com/5535758/87877376-8fdaf380-ca10-11ea-8e87-cb8ca5ad5d52.png)

**Additional context**
You can still go in through the second entrance but this entrance is completely impossible

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
