### ISSUE TITLE
Armors and some misc items are easily spammable for Exp

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#303]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0

**Describe the bug**
Some pieces of the Eisen armor have a second recipe in the crafting menu that only require one iron ingot and leather strip to make and are worth way more smithing exp than the cost it takes to create them. Also the Hidden Helmet and NFF Ignore Token cost nothing to make and can be spammed endlessly for free exp.

**To Reproduce**
Go to any forge with a iron ingot and leather strip in inventory and find the secondary Eisen armor recipes and the NFF Ignore Token and Hide Helmet.

**Expected behavior**
Just one recipe for the armors pieces.

**Screenshots**
![ScreenShot280](https://user-images.githubusercontent.com/67993113/87880704-6b9ff800-c9b9-11ea-8136-e7083b6784ae.png)
![ScreenShot281](https://user-images.githubusercontent.com/67993113/87880705-6d69bb80-c9b9-11ea-9c02-6f2aebce4718.png)
![ScreenShot282](https://user-images.githubusercontent.com/67993113/87880707-6e9ae880-c9b9-11ea-98ac-e7534fcaf556.png)
![ScreenShot283](https://user-images.githubusercontent.com/67993113/87880708-6f337f00-c9b9-11ea-9d18-22c1e607ba79.png)
![ScreenShot279](https://user-images.githubusercontent.com/67993113/87880709-6fcc1580-c9b9-11ea-9da3-8514b9293d13.png)

**Additional context**
The bugged recipes won't show up on the crafting menu if you don't have the ingot and strip in inventory.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
