### ISSUE TITLE
Huge Tree Blocking House Outside Markarth

### ISSUE THREAD

**Issue by AronaxAE** [ForgottenGlory/Living-Skyrim-2#304]
**LS Version**
2.1.0

**Describe the bug**
The is a house just to the right of the front gates of Markarth which is blocked by a huge tree. You can actually get into the building by just clicking to the sides of said tree, but it is blocking most of the door.

**To Reproduce**
Go to said house outside Markarth and check.

**Expected behavior**
No tree should be there.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/19594452/87882896-f8b37300-c9f2-11ea-8a41-dd880f7dc7fb.PNG)

A simple disable command does the trick fine.

**Comment by ForgottenGlory** [comment]
Bug reports like this need to have a screenshot of the object/NPC selected in console so I can get the FormID. Will fix once I have that.

**Comment by baldone98** [comment]
![SkyrimSE 2020-08-01 23-38-41](https://user-images.githubusercontent.com/67993113/89115957-fe2da600-d453-11ea-8676-7ef31ab691d4.png)
