### ISSUE TITLE
Price of Ancient Falmer Coin Extremely Inflated

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim-2#305]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.1
**Describe the bug**
The Ancient Falmer Coins from the Carved Brink worldspace show a value of 1 in xedit. In Game the price has risen extremely high. I'm assuming Supply & Demand is causing this

**To Reproduce**
Obtain Ancient Falmer Coins (111C4C88) from Carved Brink and keep in inventory for some time, price will inflate.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot288](https://user-images.githubusercontent.com/63564258/87965711-344d4c00-ca8a-11ea-9da1-2644bdfdd850.png)
e description of what you expected to happen.
![ScreenShot289](https://user-images.githubusercontent.com/63564258/87965706-32838880-ca8a-11ea-9929-351efb37b657.png)
![Annotation 2020-07-20 131040](https://user-images.githubusercontent.com/63564258/87965872-7080ac80-ca8a-11ea-9867-39a5d8fb2896.png)

**Additional context**

**Comment by TwistedModding** [comment]
I’ll look at this once I get up, can you tell me where you found it?

**Comment by ForgottenGlory** [comment]
MCMs will be updated to help mitigate this for 2.2.0
