### ISSUE TITLE
2 Hedge Mage quests at the same time.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#306]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0

**Describe the bug**
2 Hedge Mage quests at the same time. There is also double of everything at the camp site.

**To Reproduce**
Go to rorikstead and you'll get 2 hedge mage quests.

**Expected behavior**
One quest and no duplicates of all the items.

**Screenshots**
I could give screenshots of the double items but I don't think it's necessary. I'll drop them if you need them though.

**Additional context**
So I'd imagine this is only happening because you might have merged hedge mage armor.esp and forgot to hide the original esp thus causing a duplicate of everything.

**Comment by AronaxAE** [comment]
Went out of my way to do this quest on both 2.0.2 and 2.1.0 and both times, this bug exists for me too.

**Comment by electraumatized** [comment]
I have this as well. LS 2.0.2

**Comment by TwistedModding** [comment]
Disabling the esp that’s enabled in the load order seems to fix this(or you can remove it from the merge).

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
