### ISSUE TITLE
Great town of ivarstead\3DNPC Building conflict

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim-2#308]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.1

**Describe the bug**
During the Idle Dreams quest from interesting NPCS, youre to go to two bedrolls in ivarstead, a house from the great town of ivarstead is placed here, preventing the NPC to walk to his bedroll. disabling the house allows the quest to continue
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot294](https://user-images.githubusercontent.com/63564258/87996916-9d9c8180-cac1-11ea-91b0-99a17ef86d8b.png)
![ScreenShot293](https://user-images.githubusercontent.com/63564258/87996918-9ecdae80-cac1-11ea-8b8a-60f94c7b2e86.png)
![ScreenShot292](https://user-images.githubusercontent.com/63564258/87996921-a0977200-cac1-11ea-953d-9f0dd9ebb2e7.png)

**Additional context**
House can be disabled to progress the quest, and then can be re enabled afterwards by using "EB00AA0B.enable" in the console until the next update

**Comment by Bubzeal** [comment]
![ScreenShot289](https://user-images.githubusercontent.com/49700530/88002567-b56f0800-cab7-11ea-8f4f-6187316546b8.png)
![ScreenShot285](https://user-images.githubusercontent.com/49700530/88002570-b7d16200-cab7-11ea-8332-5b8a80266ee2.png)
![ScreenShot283](https://user-images.githubusercontent.com/49700530/88002575-b99b2580-cab7-11ea-851e-ca7089dc6e3b.png)
![ScreenShot280](https://user-images.githubusercontent.com/49700530/88002579-bb64e900-cab7-11ea-8353-261f7a048599.png)
![ScreenShot279](https://user-images.githubusercontent.com/49700530/88002581-bd2eac80-cab7-11ea-8163-7010540355b8.png)
![ScreenShot310](https://user-images.githubusercontent.com/49700530/88002585-bef87000-cab7-11ea-8259-68390d86703e.png)
![ScreenShot309](https://user-images.githubusercontent.com/49700530/88002588-c0c23380-cab7-11ea-9c5f-bd3d374ff76a.png)
![ScreenShot308](https://user-images.githubusercontent.com/49700530/88002590-c15aca00-cab7-11ea-9ed6-8489a4d2c48d.png)
![ScreenShot307](https://user-images.githubusercontent.com/49700530/88002595-c3248d80-cab7-11ea-9907-83209137f94d.png)
![ScreenShot306](https://user-images.githubusercontent.com/49700530/88002598-c4ee5100-cab7-11ea-9f88-6b7ae331d09d.png)
![ScreenShot305](https://user-images.githubusercontent.com/49700530/88002601-c6b81480-cab7-11ea-89c6-4f0322e467fe.png)
![ScreenShot304](https://user-images.githubusercontent.com/49700530/88002607-c881d800-cab7-11ea-999f-723784573048.png)
![ScreenShot303](https://user-images.githubusercontent.com/49700530/88002609-c9b30500-cab7-11ea-813b-a3409890f383.png)
![ScreenShot302](https://user-images.githubusercontent.com/49700530/88002613-cb7cc880-cab7-11ea-846d-982a387c6148.png)
![ScreenShot301](https://user-images.githubusercontent.com/49700530/88002618-cc155f00-cab7-11ea-876a-ec1583c81b30.png)
![ScreenShot300](https://user-images.githubusercontent.com/49700530/88002620-cd468c00-cab7-11ea-986e-4607f352f223.png)
![ScreenShot299](https://user-images.githubusercontent.com/49700530/88002622-cf104f80-cab7-11ea-8e5e-5db144915ab1.png)
![ScreenShot298](https://user-images.githubusercontent.com/49700530/88002626-d0da1300-cab7-11ea-968d-9d1f033ea8fc.png)
![ScreenShot297](https://user-images.githubusercontent.com/49700530/88002629-d2a3d680-cab7-11ea-939d-ab399f182d0c.png)
![ScreenShot296](https://user-images.githubusercontent.com/49700530/88002632-d3d50380-cab7-11ea-8fc0-19c02ff143fc.png)
![ScreenShot295](https://user-images.githubusercontent.com/49700530/88002634-d5063080-cab7-11ea-9fe6-3cd849cffd60.png)
![ScreenShot294](https://user-images.githubusercontent.com/49700530/88002639-d59ec700-cab7-11ea-9c8d-a06956f60f20.png)
![ScreenShot293](https://user-images.githubusercontent.com/49700530/88002643-d7688a80-cab7-11ea-92be-e4cbcceb0832.png)
![ScreenShot292](https://user-images.githubusercontent.com/49700530/88002647-d899b780-cab7-11ea-930b-797026e10475.png)
![ScreenShot291](https://user-images.githubusercontent.com/49700530/88002649-da637b00-cab7-11ea-87cd-ef9a63940b6a.png)
![ScreenShot290](https://user-images.githubusercontent.com/49700530/88002651-db94a800-cab7-11ea-8157-255bf7f63f5a.png)

**Comment by Bubzeal** [comment]
I am on 2.1 and have these clipping issues in Ivarstead. Just thought I would add them to this one. I have the same one reported up there along with some others. Seems Jk's and the Great Town of Ivarstead are fighting for turf.

**Comment by ForgottenGlory** [comment]
Should be fixed 2.3.0
