### ISSUE TITLE
Conflict in Mixwater Mill, unsure what is conflicting

### ISSUE THREAD

**Issue by Bubzeal** [ForgottenGlory/Living-Skyrim-2#309]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1

**Describe the bug**
Clipping of objects and buildings in Mixwater Mill

**To Reproduce**
Travel to Mixwater Mill

**Expected behavior**
Stuff not to be clipping

Screenshots

![ScreenShot317](https://user-images.githubusercontent.com/49700530/88003850-a63d8980-caba-11ea-84cc-906d788286b1.png)
![ScreenShot316](https://user-images.githubusercontent.com/49700530/88003863-ab023d80-caba-11ea-8cdb-4d0c8d6887bf.png)
![ScreenShot315](https://user-images.githubusercontent.com/49700530/88003873-b2294b80-caba-11ea-8315-068740e629c4.png)
![ScreenShot314](https://user-images.githubusercontent.com/49700530/88003886-b9505980-caba-11ea-84fa-5f30aa01da0a.png)
![ScreenShot313](https://user-images.githubusercontent.com/49700530/88003890-bb1a1d00-caba-11ea-8aad-36f2561e0583.png)
![ScreenShot312](https://user-images.githubusercontent.com/49700530/88003894-bce3e080-caba-11ea-9aaa-56f923215271.png)

![ScreenShot311](https://user-images.githubusercontent.com/49700530/88003898-bf463a80-caba-11ea-9064-44800d913c22.png)
![ScreenShot326](https://user-images.githubusercontent.com/49700530/88003901-c1a89480-caba-11ea-876b-c6b5bbfad30d.png)

![ScreenShot319](https://user-images.githubusercontent.com/49700530/88003816-932ab980-caba-11ea-987e-c78d06decdf5.png)
![ScreenShot318](https://user-images.githubusercontent.com/49700530/88003838-a047a880-caba-11ea-94aa-96c45aba6089.png)

![ScreenShot320](https://user-images.githubusercontent.com/49700530/88003810-902fc900-caba-11ea-96fa-bc0afeff6e6a.png)

![ScreenShot321](https://user-images.githubusercontent.com/49700530/88003802-8c03ab80-caba-11ea-94cc-3f062bef0a98.png)

![ScreenShot322](https://user-images.githubusercontent.com/49700530/88003795-88702480-caba-11ea-9208-eb52ac80622e.png)

![ScreenShot325](https://user-images.githubusercontent.com/49700530/88003782-8017e980-caba-11ea-8b59-206acf752e69.png)
![ScreenShot324](https://user-images.githubusercontent.com/49700530/88003788-827a4380-caba-11ea-9341-c200256f0e1b.png)

![ScreenShot323](https://user-images.githubusercontent.com/49700530/88003791-85753400-caba-11ea-8295-954f18e8183a.png)

**Comment by jokerstyle00** [comment]
Would also like to note that the NPC Orc that's supposed to chase you down here to start Project AHO spawns inside one o the buildings, and is impossible to get to without using the tcl console command. I was unable to get the console code for said orc, because it's difficult to get close enough to select him without triggering the start of AHO.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
