### ISSUE TITLE
Low res(vanilla?) texture on Ebony Mail

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#310]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0

**Describe the bug**
Low res(vanilla?) texture on Ebony Mail

**To Reproduce**
Look at ebony mail

**Expected behavior**
High res ebony mail.

**Screenshots**
![ScreenShot275](https://user-images.githubusercontent.com/62785432/88012764-57a2e600-cae0-11ea-9c6e-8dd782b2b07a.png)
![ScreenShot276](https://user-images.githubusercontent.com/62785432/88012768-58d41300-cae0-11ea-8153-f652d3642b6e.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Note for not-tired FG:

https://www.nexusmods.com/skyrimspecialedition/mods/12905
https://www.nexusmods.com/skyrimspecialedition/mods/28700

both are bad convert this instead

https://www.nexusmods.com/skyrim/mods/37422

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
