### ISSUE TITLE
Attack Speed Bug

### ISSUE THREAD

**Issue by combatmaster1o3** [ForgottenGlory/Living-Skyrim-2#311]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v2.0.1

**Describe the bug**
Attack Speed is not calculating correctly with certain buffs.

**To Reproduce**
-Equip an offhand weapon with ranks in Ravage(One-handed Tree)
-Use the Elemental Fury Shout on an Unenchanted Weapon(It grants the Elemental Fury Enchantment)

**Expected behavior**
Weapon attack speed should either add or multiply weaponspeedmult. This is mostly done correctly by the attribute values mod.

**Screenshots**
This is about right as my Agility is 6(85% attack speed)
![image](https://user-images.githubusercontent.com/67399578/88017958-bf632c00-caf4-11ea-9b7d-69e425770342.png)
![image](https://user-images.githubusercontent.com/67399578/88018499-d6564e00-caf5-11ea-9bfd-547eef5483c2.png)

Now this is with Rank 1 Ravage
![image](https://user-images.githubusercontent.com/67399578/88018392-a6a74600-caf5-11ea-8e32-85080660458c.png)

As you can see, attribute values scales appropriately
![image](https://user-images.githubusercontent.com/67399578/88018650-29c89c00-caf6-11ea-904e-20ecb96a5131.png)
![image](https://user-images.githubusercontent.com/67399578/88018762-5bd9fe00-caf6-11ea-9ef4-f06b8f3b9fe3.png)

**Additional context**
This is most commonly an issue with the number added/multiplied to the weaponspeedmult. For example, if you type the command player.setav weaponspeedmult 1.0 and then try some swings, you will notice a massive boost in your attack speed. This is because your weaponspeedmult is actually 2.0. With Attribute Values changing the base appropriately, the previous command would actually result in a weaponspeedmult of 1.87 with the given agility of 6. 
It does lead to some confusion on how the value is being change in the example with Obliterate Rank 1(20% increase in speed). It isn't a simple fix or changing 1.2 to 0.2, as the increase is 1.08 and essentially double the base attack speed. 

In this case we have Obliterate Rank 1(20% increase) Top is base. Bottom is when Obliterate is active.
![image](https://user-images.githubusercontent.com/67399578/88022303-0ce39700-cafd-11ea-99e1-90c714aa6f26.png)

As we can see, the delta remains 1.08.

Obliterate Rank 2(35% increase) Top is base. Bottom is when Obliterate is active.
![image](https://user-images.githubusercontent.com/67399578/88021963-67c8be80-cafc-11ea-85a5-e0bb5caf7354.png)

Again we see odd numbers. The delta is 1.21, not the expected 1.35.

Shifting gears towards Elemental Fury, as far as I'm aware the first word of the shout improves attack speed by 50% with each subsequent word adding an additional 25%(50%, 75%, 100%). I'm not familiar with and changes from Thunder Child and this shout, but I don't believe it adjusts this aspect of the shout. Regardless we can see the values are odd. Only the first word is used here. 
![image](https://user-images.githubusercontent.com/67399578/88022709-c6426c80-cafd-11ea-9b0a-2c35d300cbae.png)

The av delta this time is 1.17, which is pretty radically different from .5. Thjs shout is a self buff, so it shouldn't be affected by Huricane Force(Perk: Shouts that affect others increase in power by 1% per point of speechcraft). My speechcraft is 93%, so even if it was then we should see a delta of 0.965 or something similar. 

I leave the rest up to you FG.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
