### ISSUE TITLE
Naked bandit still (nudity not shown in pictures)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#313]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0

**Describe the bug**
naked bandit

**To Reproduce**
Run around and search for bandits?

**Expected behavior**
No nude bandits

**Screenshots**
![ScreenShot277](https://user-images.githubusercontent.com/62785432/88100891-d50f3a80-cb62-11ea-91a4-fdf8a43e400d.png)

**Additional context**
I will be adding onto this report periodically as a comment when I find more examples. 

Something to note. This bandit didn't even have any armor in his inventory except a helmet and boots. The problem seems to b fixed for enemies that HAD armor in there inventory but just didn't equip it. Seems like something is wrong the way a mod is distributing armors.

**Comment by baldone98** [comment]
![ScreenShot284](https://user-images.githubusercontent.com/67993113/88140361-3660f900-cbb7-11ea-836c-f87e21f7a9a8.png)

Found a naked bandit as well.

**Comment by TwistedModding** [comment]
![ScreenShot278](https://user-images.githubusercontent.com/62785432/88340459-7d5b0580-cd01-11ea-90bf-f4dae4667bc6.png)

Another one. Spawned with no armor at all.

**Comment by Bubzeal** [comment]
I have an enemy WITH armor but was still naked version 2.1

![ScreenShot329](https://user-images.githubusercontent.com/49700530/88470344-0021c300-ceb0-11ea-8617-0dcef4904b54.png)

**Comment by TwistedModding** [comment]
You need to remove that screenshot and post a new one without nudity man

**Comment by Bubzeal** [comment]
My bad bro

**Comment by Bubzeal** [comment]
Is it alright if I just scribbled it out like this? I didn't even realize his business was visible

![InkedScreenShot329_LI](https://user-images.githubusercontent.com/49700530/88471196-ee91e880-ceba-11ea-9496-0bda1a58299e.jpg)

**Comment by TwistedModding** [comment]
That screenshot is fine I'd imagine

But for future reference, do what I do. Click on the npc in the console then look another direction without the body in your field of view, then reopen the console and take a screenshot.

**Comment by Bubzeal** [comment]
Will do my guy, sorry for fudging it up the first time.

**Comment by baldone98** [comment]
![SkyrimSE 2020-07-28 02-54-25](https://user-images.githubusercontent.com/67993113/88697904-f32ceb80-d0ca-11ea-9c47-49c300624dbb.png)

**Comment by ForgottenGlory** [comment]
Did another round of fixes on this. I've identified exactly what the problem is, just need help tracking down NPCs that have the issue. After 2.2.0 comes out, please continue to report these as they happen.
