### ISSUE TITLE
Massively inflated prices on Moonstone

### ISSUE THREAD

**Issue by combatmaster1o3** [ForgottenGlory/Living-Skyrim-2#314]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.0.1

**Describe the bug**
The price of Moonstone is massively inflated.

**To Reproduce**
Unclear, however considering other reports of similar items having inflated prices it might have to do with the supply and demand system.

**Expected behavior**
Moonstone to not be worth more than the armor you craft.

**Screenshots**
![image](https://user-images.githubusercontent.com/67399578/88101960-d0e81a80-cb6c-11ea-9e0c-9d4befd1f888.png)
![image](https://user-images.githubusercontent.com/67399578/88101932-c3329500-cb6c-11ea-99a2-c2da713819cd.png)

**Additional context**

**Comment by tjbassoon** [comment]
There are a lot of prices being totally screwed up by the Supply and Demand mod. I feel like it's more trouble than it's worth.... all items should have a min/max. Also apparently storing items in a chest will cause the supply to change so the prices change. It sounds like a good mod on paper, but not in practice. Not like you don't get rich as fuck in this game anyway.

**Comment by ForgottenGlory** [comment]
I may play around with the setting this mod has that resets prices to make it happen more frequently.

**Comment by combatmaster1o3** [comment]
In that case, I may know why Moonstone is inflated in price. I will have to double check, but I believe other crafting items will also be extremely inflated. In this save I have aggressively hoarded armors and weapons to break down, so I have 200+ ingots of everything except Dragon remains and perhaps a few rarer ingots like quicksilver.

**Comment by ForgottenGlory** [comment]
The MCM update for 2.2.0 should help mitigate this
