### ISSUE TITLE
Carpathian Inn Ledger adding non playable items to inventory

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim-2#316]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.1

**Describe the bug**
Using the Carpathian Inn Ledger to purchase supplies will add supplies with it's own form ids that do not appear in inventory. items with vanilla ids work fine for the ledger recipes though.

**To Reproduce**
Purchase iron ingots, dwarven metal ingots or sawn logs with an empty inventory. Your inventory will show to be empty, but youll have the weight of everything and using player.showinventory in the console will display these items 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot295](https://user-images.githubusercontent.com/63564258/88239530-ac666e00-cc52-11ea-9eb5-db40fc7010a1.png)
![ScreenShot296](https://user-images.githubusercontent.com/63564258/88239534-ae303180-cc52-11ea-9743-f2a4ccd9e8a6.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
I'm stumped on this one.

**Comment by jokerstyle00** [comment]
This happened to me on 2.0.2, although only Iron and Dwarven Ingots were affected for me, not sawn logs.
