### ISSUE TITLE
Battlemage Armor too common in lists

### ISSUE THREAD

**Issue by Cody-Spring** [ForgottenGlory/Living-Skyrim-2#317]
I found 'Battlemage Armor' at level 2 (in one of the dressers at the Inn in Riverwood), am now level 7 with only 3.5h playtime and I've found 3 more 'Battlemage Armor' in random dressers around inns and forts. Given that it's worth 3k-4k I'm assuming not intentional, or RNG is **really** blessing me lately.

**Comment by TwistedModding** [comment]
You'll have to give screenshots of the battlemage armor selected in the console and post them here.

Also take a screenshot of the dressers you got them from selected in the console.

**Comment by Cody-Spring** [comment]
> 
> 
> You'll have to give screenshots of the battlemage armor selected in the console and post them here.
> 
> Also take a screenshot of the dressers you got them from selected in the console.

Here's the most recent

![image](https://user-images.githubusercontent.com/32400573/88250363-05430000-cc6d-11ea-8132-8d13303742a1.png)
![image](https://user-images.githubusercontent.com/32400573/88250390-1b50c080-cc6d-11ea-9e3d-235af2ded02e.png)

**Comment by AronaxAE** [comment]
Speaking of really high tier armor, the entire Khajiiti Apex Armor Sets (which was worth about 3000 gold in my game) were dropping from enemies as low as level four or five for me (I used my set all the way up to level 35 because nothing else was better). Can't screenshot anymore but thought I should mention it anyway.

**Comment by Cody-Spring** [comment]
Along the lines of Leveled Lists, I got the quest item "Esbern's Potion" off of a "Bandit Warrior," don't have a screenshot of it so rather than a separate issue I'll post as a comment here as something to look out for

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
