### ISSUE TITLE
Hair floats above male heads

### ISSUE THREAD

**Issue by masqueradex** [ForgottenGlory/Living-Skyrim-2#318]
**LS Version**
2.1.0

**Describe the bug**
Virtually all hair from bodies and faces merged float above the heads of male PCs. 

**To Reproduce**
Pick a race then go to Hair slider scroll through hair.

**Expected behavior**
Hair not to be floating

**Screenshots**
![Hair Issue](https://user-images.githubusercontent.com/68194592/88307901-4cf37700-ccc1-11ea-99df-8fe3b538d56e.png)
![Hair Issue 2](https://user-images.githubusercontent.com/68194592/88307908-4fee6780-ccc1-11ea-867c-ca4623554112.png)
![Hair Issue 3](https://user-images.githubusercontent.com/68194592/88308378-ce4b0980-ccc1-11ea-829c-b31297bae2d6.jpg)

**Comment by jokerstyle00** [comment]
I made a post about this awhile go and tried the ENB ini fix FG posted, didn't work. Elves have particularly bad hair. I'm pretty sure it has to be an issue with the head mesh or something similar.

https://github.com/ForgottenGlory/Living-Skyrim-2/issues/225

**Comment by masqueradex** [comment]
> I made a post about this awhile go and tried the ENB ini fix FG posted, didn't work. Elves have particularly bad hair. I'm pretty sure it has to be an issue with the head mesh or something similar.
> 
> #225

Usually, I'd check the opened bugs, but not the closed ones lol.

**Comment by jokerstyle00** [comment]
I'm linking it for FG, since the original suggested fix didn't work.

**Comment by ForgottenGlory** [comment]
Open to suggestions on how to fix this one.
