### ISSUE TITLE
I'm Walkin Here (this should be marked as low priority)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#319]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

[Alduin.Save.Save.175.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4968107/Alduin.Save.Save.175.zip)

**Mod Name**
I'm Walkin Here

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/27742?tab=description

**Why?**
Its a major Quality of Life mod for people who like to have a lot of followers because when changing to a new cell all of your followers will spawn in front of you making it very difficult to get them out of the way in tight corridors.

**Additional context**
I believe this is just a skse plugin and has no esp so it should be compatible with everything and can be placed anywhere (I'd just put it at the quality of life separator or skse plugins)

I would leave this disabled by default as most people might find it unimmersive (specifically people who don't like to have a lot of followers). 

I also double checked in NFF to make sure there isn't an option related to this (unless I missed something very obvious)

**Comment by AronaxAE** [comment]
+1

No ESP, light-weight and just works.

**Comment by jokerstyle00** [comment]
+1

Kind of an unspoken necessity in this list, since followers can feel almost mandatory early game.

**Comment by KNGLogan** [comment]
please add this i have to click can you get behind me to get anywhere

**Comment by ForgottenGlory** [comment]
Added 2.2.0
