### ISSUE TITLE
Tears in ground

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#320]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0.

**Describe the bug**
Large tears are visible on the ground in different spots outside. You can see through them, but walking into the tear will teleport you on top of the tear.

**To Reproduce**
Go to these locations.

**Expected behavior**
No tears in the ground/ floor terrain is connected.

**Screenshots**
![ScreenShot289](https://user-images.githubusercontent.com/67993113/88335750-6c0dfb00-ccf9-11ea-9ca6-cff337d24758.png)
![ScreenShot292](https://user-images.githubusercontent.com/67993113/88335804-834ce880-ccf9-11ea-948e-6e8cf7d4e1de.png)
![ScreenShot293](https://user-images.githubusercontent.com/67993113/88335808-8516ac00-ccf9-11ea-86a9-b9ac999fabce.png)

**Additional context**
I'll update this list if I find anymore.

**Comment by TwistedModding** [comment]
*Note for glory* 
He said in the discord that he couldn't select the terrain in the console for whatever reason so I told him to just post the cords of the location.

**Comment by Bubzeal** [comment]
I have a tear in the ground as well

Screenshot
![ScreenShot327](https://user-images.githubusercontent.com/49700530/88470317-d072bb00-ceaf-11ea-84a9-10df1b4d0bb1.png)

**Comment by baldone98** [comment]
![SkyrimSE 2020-07-27 01-16-24](https://user-images.githubusercontent.com/67993113/88612757-87f30300-d051-11ea-8132-2125dc057a80.png)

Found another.

**Comment by ForgottenGlory** [comment]
Should be fixed 2.2.0
