### ISSUE TITLE
aetherial crown not working 

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#321]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.02

**Describe the bug**
the crown lets you have two stones and its only letting me have one

**To Reproduce**
get the crown and get two stones

**Expected behavior**
let me have two

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
This is a conflict between Glory's Scaling Standing Stones and the effect of the Aetherial Crown, I'll look into fixing it but am unsure if I can.
