### ISSUE TITLE
Floating Sword in Korvanjund

### ISSUE THREAD

**Issue by jchritton** [ForgottenGlory/Living-Skyrim-2#323]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

2.0.2

**Describe the bug**

In the entrance to Korvanjund Temple, there's a weapons rack with a warhammer (which works as expected), and a cutlass-looking sword that is floating in front of the rack and non-interactable.

**To Reproduce**

Enter Korvanjund Temple and find the first weapons rack. NOTE: I did confirm that on a new game using COC (didn't set up the MCM), there was an interactable Elven Battleaxe on the rack where I would expect the sword was intended to be, so possibly it was a fluke with my game, but just making sure it's reported in case it causes other issues.

**Expected behavior**

Either no sword should appear (seems a bit out of place where it is either way), or it should be non-floating and interactable.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![ScreenShot279](https://user-images.githubusercontent.com/18075641/88447840-5aae1700-cdfd-11ea-860b-32f5050999c7.png)

![ScreenShot280](https://user-images.githubusercontent.com/18075641/88447829-57b32680-cdfd-11ea-86c5-8d16941c4eb5.png)

![ScreenShot282](https://user-images.githubusercontent.com/18075641/88447835-597cea00-cdfd-11ea-90a3-1ee42cfeeaf6.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
