### ISSUE TITLE
Wand of Zombies 

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#324]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0

**Describe the bug**
There is a weird blue light emitting from part of the wand that is invisible.

**To Reproduce**
Find this wand or spawn it in and look at it

**Expected behavior**
The blue effects to be properly aligned with the rest of the wand 

**Screenshots**
![ScreenShot282](https://user-images.githubusercontent.com/62785432/88448677-dca23e00-ce05-11ea-8433-140821862f1b.png)
![ScreenShot281](https://user-images.githubusercontent.com/62785432/88448679-df049800-ce05-11ea-9ddf-36f1f95146b1.png) 
I will note it is kinda hard to see in the screenshot but if you look to the right of the staff while i'm holding it, you'll see the blue effects.

**Additional context**
Unsure if part of the wand is just invisible for some reason or if the blue effect is misplaced for the wand.

**Comment by TwistedModding** [comment]
Minor bug, no idea how to go about fixing this though unless it’s intentional.

**Comment by ForgottenGlory** [comment]
Yep, not sure I can fix this one. The wands from Fulcimentum are treated as staves so any effect on them gets rendered as if it's a staff. I'm open to suggestions on how to fix it.
