### ISSUE TITLE
Curator's Companion item icons don't show up [solution found]

### ISSUE THREAD

**Issue by phzhft** [ForgottenGlory/Living-Skyrim-2#326]
**LS Version**
2.1.1

**Describe the bug**
Curator's Companions item icons (the ones that indicate whether an item is already in the museum) don't show up. I fixed it by on my install by upgrading:

moreHUD to 3.8.0
moreHUD Inventory Edition to 1.0.17

as specified in https://www.nexusmods.com/skyrimspecialedition/mods/38529/?tab=posts (scroll down to the section "Icon support requires")

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
