### ISSUE TITLE
vampire lord cape inside body

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#327]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.02
**Describe the bug**
the cape is in the vampire lords body or just mostly gone

**To Reproduce**
become vampire lord get the very top perk sais equip royal crown

**Expected behavior**
cape to be fully there

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![ScreenShot276](https://user-images.githubusercontent.com/66355096/88471439-0a06ee80-cecf-11ea-988b-26ddecd73862.png)

**Additional context**
Light has the same issue

**Comment by daffodilian** [comment]
So did this only start happening after getting the 'very top perk'?

**Comment by KNGLogan** [comment]
yeah because without the perk you dont have a cape or crown

**Comment by ForgottenGlory** [comment]
I'll be honest, I have no idea where to even begin with fixing this. I'm open to suggestions.

**Comment by daffodilian** [comment]
Okay, I spent too much time messing with this before realizing what's going on. The cape is correct. It connects to the headdress and goes just down to the wings. No disabling of skeletons\body  mods has made any difference, this is just how the look is intended,
Where the Cape ends:
![ScreenShot280](https://user-images.githubusercontent.com/63564258/89105196-06062f80-d3ed-11ea-931d-94c53aa3ca80.png)
It makes sense that the cape wouldnt be covering the wings,

Where the cape is connected to the crown:
![ScreenShot279](https://user-images.githubusercontent.com/63564258/89105204-21713a80-d3ed-11ea-8c1f-f800bb26b52b.png)
