### ISSUE TITLE
Honor Among Thieves - Can't acquire Expensive Necklace

### ISSUE THREAD

**Issue by DrMaple** [ForgottenGlory/Living-Skyrim-2#328]
**LS Version**
v2.1.1

**Describe the bug**
During the quest 'Honor Among Thieves' from the mod 'Thieves Guild for Good Guys', you are tasked with stealing an 'Expensive Necklace' from the Blue Palace in Solitude. When entering the main hall of the palace, the location of the necklace is located inside your instance but out of bounds.

This most likely is happening because of the mod 'Palaces and Castles Enhanced'.

**To Reproduce**
1. Get Quest
2. Go to Blue Palace

**Expected behavior**
The necklace should be in bounds so I can grab it :)

**Screenshots**
https://gfycat.com/loathsomedelectablechameleon

![tC6vem9 1](https://user-images.githubusercontent.com/5175814/88482620-7239ec80-cf30-11ea-854e-79d3dea9fd9d.png)

**Comment by TwistedModding** [comment]
You need to post a screenshot with the necklace selected in the console

**Comment by DrMaple** [comment]
Added. Reading is hard, my bad.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
