### ISSUE TITLE
vanilla texture trees at ancestor glade

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#330]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.02

**Describe the bug**
the trees are butt looking

**To Reproduce**
go to the ancestor glade and look at the trees

**Expected behavior**
the tress be high quality 
![ScreenShot270](https://user-images.githubusercontent.com/66355096/88611662-22057c00-d04f-11ea-9142-6aac6e55a736.png)
![ScreenShot271](https://user-images.githubusercontent.com/66355096/88611673-2a5db700-d04f-11ea-99ac-580146d3ec28.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Looking at some posts online and I can't seem to find a retexture for specifically this tree.

https://www.nexusmods.com/skyrimspecialedition/mods/12371
This mod seems to make all vanilla trees 3d and improve their quality along with added trees (if I read it correctly)
It does seem to be incompatible with some of the mods already in the list looking at the mod page (possibly could just use this to replace them) unsure though.

**Comment by TwistedModding** [comment]
Wouldn’t spend too much time looking on this tbh, as you are normally in and out of that location, if volk or glory could mark this as low priority that would be nice.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0

**Comment by ForgottenGlory** [comment]
After further investigation, there doesn't appear to be a retexture for this and I don't want to disable the trees because they provide a quest item. Unfortunately doesn't look like I can fix this.
