### ISSUE TITLE
BFB Erik the Slayer (NOT Erik)

### ISSUE THREAD

**Issue by jchritton** [ForgottenGlory/Living-Skyrim-2#332]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

2.0.2 (Also checked on 2.1.1)

**Describe the bug**

Erik the Slayer has the black face bug (NOTE Erik does not, it only occurs after his short quest has been completed)

**To Reproduce**

Complete "Erik the Slayer" quest, find the character in Rorikstead (I found him in the Frostfruit Inn)

**Expected behavior**

No BFB

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![ScreenShot285](https://user-images.githubusercontent.com/18075641/88635493-52640f00-d07d-11ea-9371-25e0c2f035d6.png)

![ScreenShot286](https://user-images.githubusercontent.com/18075641/88635497-53953c00-d07d-11ea-85e9-b80fcc3d50ea.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
