### ISSUE TITLE
Floating door at Fort Dawnguard

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#334]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0.

**Describe the bug**
Going to a roof on Fort Dawnguard shows a door that is not connected to a wall. Entering the door leads you to the bottom floor as if you entered from the main entrance.

**To Reproduce**
Go to roof of Fort Dawnguard

**Expected behavior**
Door attached to a wall and for it to bring me to the correct spot inside the fort when I activate it.

**Screenshots**
![ScreenShot300](https://user-images.githubusercontent.com/67993113/88825795-9c3c1a80-d18d-11ea-8c64-11fd1f88bdb8.png)
![ScreenShot301](https://user-images.githubusercontent.com/67993113/88825819-9fcfa180-d18d-11ea-80c9-778ed7196766.png)

**Additional context**
The second screenshot is where I think the door was probably supposed to be.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
