### ISSUE TITLE
Silvershield of the Dragonblood requires too many resources to make

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#336]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.0.

**Describe the bug**
The Silvershields of the Dragonblood requires way too many resources to craft, especially considering the value and armor of the shields themselves.

**To Reproduce**
Look up the shields in the forge menu.

**Expected behavior**
A less demanding recipe.

**Screenshots**
![ScreenShot305](https://user-images.githubusercontent.com/67993113/88882079-c249d500-d1f6-11ea-851a-ff5588e66c7b.png)
![ScreenShot306](https://user-images.githubusercontent.com/67993113/88882086-c83fb600-d1f6-11ea-85fe-ab0c553cf836.png)
![ScreenShot303](https://user-images.githubusercontent.com/67993113/88882092-cbd33d00-d1f6-11ea-9b5a-3257d96b9079.png)
![ScreenShot304](https://user-images.githubusercontent.com/67993113/88882096-cd9d0080-d1f6-11ea-9378-4ebd54bcb30f.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.2.0
