### ISSUE TITLE
shield on back texture issue

### ISSUE THREAD

**Issue by bobjane01** [ForgottenGlory/Living-Skyrim-2#338]
When my shield is on my back , the texture doesn't 

![ScreenShot279](https://user-images.githubusercontent.com/69025964/88997078-2ae99c80-d332-11ea-9002-1a12e070028c.png)

**Comment by TwistedModding** [comment]
Which shield is it?

**Comment by bobjane01** [comment]
![ScreenShot280](https://user-images.githubusercontent.com/69025964/88997772-d6dfb780-d333-11ea-83c5-5254447ec059.png)
sorry i have attached a new screen shot showing the item

**Comment by TwistedModding** [comment]
Ok yeah thats what I thought the shield was anyway. This is a known bug and will be fixed next update.

**Comment by bobjane01** [comment]
cheers thanks

**Comment by TwistedModding** [comment]
Rest in piece viking shields
