### ISSUE TITLE
Jarl's stewards not giving rewards upon doing bounty quests for them.

### ISSUE THREAD

**Issue by Erokla** [ForgottenGlory/Living-Skyrim-2#339]
**LS Version**
2.1.1

**Describe the bug**
Jarl's stewards not giving rewards upon doing bounty quests for them.

**To Reproduce**
Get your bounty quest from an innkeeper/jarl's steward and claim your reward from the steward.

**Expected behavior**
Get rewarded (golds) upon quest completion.

**Comment by ForgottenGlory** [comment]
Duplicate of #294 (or at least, it's the same issue. Cause still unknown.)
