### ISSUE TITLE
Curators Companion Inventory icon doesn't show up [possible conflict found]

### ISSUE THREAD

**Issue by phzhft** [ForgottenGlory/Living-Skyrim-2#341]
**LS Version**
2.2.0

**Describe the bug**
Curator's Companion inventory icon (ie. when SkyUI inventory menu is open and item is highlighted - see screenshot below for how it should look when it works correctly) doesn't show up. 

The icon when aiming at an item in the "world" works fine though.

I might have found a workaround, removing the script AhzMoreHudIE.pex from iEquip fixes the issue. Found it by looking at Nexus Curator's Companion forums - here are some hints from Ic0nic0de the author:

> "They are for communicating with moreHUD, the scripts used to be packaged with iequip as it was the only mod supported by moreHUD, now that this mod has support the scripts are packaged in moreHUD directly and the version in iequip are out of date and don’t contain the code needed for this mod to work."
> 

**To Reproduce**
Pick up a museum item from the world that has the icon, then open inventory to see that there is no icon.

**Expected behavior**
Icon should be present 

**Screenshots**
![curatorscompanion_iequip](https://user-images.githubusercontent.com/68798112/89094598-745dda00-d37a-11ea-8d8f-3a717180c018.PNG)

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
