### ISSUE TITLE
BFB return on hadvar and belethor

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#343]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0

**Describe the bug**
bfb on hadvar and belethor

**To Reproduce**

**Expected behavior**
No bfb

**Screenshots**
![SkyrimSE 2020-08-01 10-52-01](https://user-images.githubusercontent.com/62785432/89105438-b9b7f100-d3e6-11ea-8fc1-cc466cd36183.png)

![Hadvar Selected](https://user-images.githubusercontent.com/62785432/89105443-cc322a80-d3e6-11ea-9ca1-ff328ad9843e.jpg)

**Additional context**
These bugs were re introduced in the most recent version of LS2

**Comment by TwistedModding** [comment]
Sent glory the fix for this.

To glory, close this whenever you incorporate the fixes.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
