### ISSUE TITLE
Bunch of crafting books spawned in the inventory upon creating a new character

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#344]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0

**Describe the bug**
Bunch of books spawned in the inventory upon creating a new character

**To Reproduce**
create a new character

**Expected behavior**
no crafting books spawned in with character

**Screenshots**
![SkyrimSE 2020-08-01 10-52-48](https://user-images.githubusercontent.com/62785432/89105478-12878980-d3e7-11ea-93d2-c648a43bff17.png)

**Additional context**
I noticed they were all from weapon merged.esp in the console so i didnt take a screenshot of all of them because I don't think it will be necessary. Just ping me on discord or comment here if you need all the books selected and I'll update this post with them.

**Comment by TwistedModding** [comment]
Sent glory the fix for this.

To glory, close this whenever you incorporate the fixes.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
