### ISSUE TITLE
Curators Storage Token Allows Spammable Smithing XP

### ISSUE THREAD

**Issue by CombatArcay** [ForgottenGlory/Living-Skyrim-2#346]
**LS Version 2.2.0**

**Describe the bug**
The Curators Storage Token has no required ingredients to craft, and thus allows easily obtained XP when it is created at any forge.

**To Reproduce**
Create a Curators Storage Token at a Forge, no prerequisite skills needed.

**Expected behavior**
The token requires a simple recipe (ie. 1 Gold Bar) to craft.

**Additional context**
~Taken from the LOTD Curator's Companion Nexus Page~

The mod comes with a spell to access a safe storage container called the "Relic Storage Container", this container can be used on your travels to store displayable relics and items you find in the world.
You can craft the Relic Storage Token from any forge located around Skyrim, drop the token into a container or follower to add them to the custom storage list, the token is destroyed and any items stored in these containers or followers will retain their “Found” status and behave like player inventory, to remove the container or follower simply add another token to them.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
