### ISSUE TITLE
Crash before entering Dragonsreach (Whiterun)... Other crashes noticed entering whiterun interior cells 

### ISSUE THREAD

**Issue by Jaynan35** [ForgottenGlory/Living-Skyrim-2#347]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Version 2.2.0

**Describe the bug**
Crashes every time before entering Dragonsreach. I've also experienced general crashing outside and entering smaller buildings so a larger issue is probably at play. 

**To Reproduce**
Load into my save file on the steps to dragonsreach... I try to enter the building and then the CTD to desktop happens

**Expected behavior**
Being able to enter the building. 

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
I've cleared all files out including Wabbajack, the Living Skyrim folder, Skyrim files in My Docs, and the Skyrim.exe folder with no success. Also installed latest drivers etc... No additional mods added. [
[Crash_2020_8_1_16-3-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5011179/Crash_2020_8_1_16-3-5.txt)
](url)

**Comment by TwistedModding** [comment]
This is a memory crash. Close this report and @ me on the discord for a fix.

**Comment by Jaynan35** [comment]
Don't use discord much. Adding you just consists of "add Friend"?
