### ISSUE TITLE
CFTO Halfmoon Mill - Ferryman Floating

### ISSUE THREAD

**Issue by macpherb** [ForgottenGlory/Living-Skyrim-2#348]
**LS Version**
Current version: 7/31/2020 2.2.0

**Describe the bug**
Carriage and Ferry Travel Overhaul Ferryman floating in Halfmoon Mill. There is a patch available on NexusMods - https://www.nexusmods.com/skyrimspecialedition/mods/38172?tab=description

**To Reproduce**
Travel to Halfmoon Mill and the Ferryman is floating there.

**Expected behavior**
I expected him to not be floating, but maybe sitting on the wall or dock or anywhere really.

**Screenshots**
I do not have a screenshot, but I can add one if needed. This is a known bug, hence the patch that is already on the Nexus. There is a screenshot there as well if you want to see what I am talking about.

**Additional context**
Thank you for this amazing list and all the work that you do! I am not trying to nitpick, but just let you know.

**Comment by macpherb** [comment]
![enb2020_8_1_16_54_16](https://user-images.githubusercontent.com/67929053/89111323-0ff25780-d41a-11ea-81f1-4706b5f0472c.png)
![enb2020_8_1_16_54_22](https://user-images.githubusercontent.com/67929053/89111325-12ed4800-d41a-11ea-8cac-1f58272fa1dd.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
