### ISSUE TITLE
Green Ship - Joy of Ships Odd Textures

### ISSUE THREAD

**Issue by macpherb** [ForgottenGlory/Living-Skyrim-2#349]
**LS Version**
Current version: 7/31/2020 2.2.0

**Describe the bug**
Not a bug per se, but the textures on the ship at the Solitude Docks looks really odd. It is a known situation and there is a fix on NexusMods - https://www.nexusmods.com/skyrimspecialedition/mods/31973

**To Reproduce**
Travel to the Solitude docks

**Expected behavior**
Ideally, the ship should look like the photos from Joy of Ships (with the green moss/algae), but if not, the fix linked above removes the green entirely.

**Screenshots**
Screenshots below

**Additional context**
Not sure if you want to know these sorts of things, but figured you can always close this bug report if you don't care about this kind of thing. Thanks again for this amazing modlist and all the work you do to make it so great!

![enb2020_8_1_16_53_11](https://user-images.githubusercontent.com/67929053/89111381-b5a5c680-d41a-11ea-8095-d1fb7d69b219.png)
![enb2020_8_1_16_53_15](https://user-images.githubusercontent.com/67929053/89111382-b9394d80-d41a-11ea-9a79-2213ed792b79.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
