### ISSUE TITLE
Boat Missing Textures in Winterhold

### ISSUE THREAD

**Issue by macpherb** [ForgottenGlory/Living-Skyrim-2#350]
**LS Version**
Current version: 7/31/2020 2.2.0

**Describe the bug**
There is a rowboat below Winterhold (added by JK's Skyrim, I believe) that seems to be missing textures (I think; I'm still learning a lot, so I could be mistaken, but something is definitely not right)

**To Reproduce**
Travel to Winterhold and walk down to the water below the bridge to the College.

**Expected behavior**
The boat should look like the rest of the boats in Skyrim.

**Screenshots**
Below

**Additional context**
Thanks!

![enb2020_8_1_17_22_51](https://user-images.githubusercontent.com/67929053/89111582-0e765e80-d41d-11ea-8cd4-c03c85b8fcd8.png)
![enb2020_8_1_17_22_57](https://user-images.githubusercontent.com/67929053/89111583-0fa78b80-d41d-11ea-866c-13ccdf60488d.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
