### ISSUE TITLE
Floating Archery Platform at Elysium Estate

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#351]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0.

**Describe the bug**
A wooden platform with an archery target is floating near a wall.

**To Reproduce**
Go to the archery range at Elysium Estate

**Expected behavior**
The platform probably connects to the half-wall it is next to.

**Screenshots**
![enb2020_8_1_23_58_32](https://user-images.githubusercontent.com/67993113/89115999-798f5780-d454-11ea-8bcb-665bc6b9b589.jpg)
![enb2020_8_1_23_58_37](https://user-images.githubusercontent.com/67993113/89116000-7c8a4800-d454-11ea-81bb-e9b97215e99f.jpg)
![SkyrimSE 2020-08-01 23-58-43](https://user-images.githubusercontent.com/67993113/89116008-8b70fa80-d454-11ea-8324-2b4c325fcdd3.png)
![enb2020_8_1_23_58_49](https://user-images.githubusercontent.com/67993113/89116015-94fa6280-d454-11ea-8e2f-66b3184fc85b.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
This seems relatively harmless in the grand scheme of things. If someone wants to make a fix for it I'll include it.
