### ISSUE TITLE
Incorrect or Duplicate Crafting Recipes

### ISSUE THREAD

**Issue by baldone98** [ForgottenGlory/Living-Skyrim-2#352]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0.

**Describe the bug**
Some items are either duplicated or have the recipes incorrect in the smithing menu.

**To Reproduce**
Go to a forge.

**Expected behavior**
Correct recipes and unduplicated items.

**Screenshots**
![SkyrimSE 2020-08-01 23-39-47](https://user-images.githubusercontent.com/67993113/89116115-0d155800-d456-11ea-9e8d-69265a9eef95.png)
Probably not any help but four items are listed as <Missing Name> and does not produce anything when crafted so I couldn't get the items in the console.

![enb2020_8_1_23_46_36](https://user-images.githubusercontent.com/67993113/89116143-6087a600-d456-11ea-93ab-cbe374e53c5e.jpg)

![enb2020_8_1_23_48_36](https://user-images.githubusercontent.com/67993113/89116152-7d23de00-d456-11ea-81d3-bbfcfdb4a7a0.jpg)

![enb2020_8_1_23_48_45](https://user-images.githubusercontent.com/67993113/89116163-92007180-d456-11ea-819e-4e2b21c9ffa3.jpg)

![enb2020_8_1_23_48_56](https://user-images.githubusercontent.com/67993113/89116166-9f1d6080-d456-11ea-8ac2-185bb1dcdfdb.jpg)
There is also a helmet that is duplicated with this armor set but it is an invisible helmet so I don't think you can pick it up once you drop it.

![enb2020_8_2_00_42_55](https://user-images.githubusercontent.com/67993113/89116984-92e9d100-d45f-11ea-9fab-32dc851e881e.jpg)
![enb2020_8_2_11_47_12](https://user-images.githubusercontent.com/67993113/89129447-112b8f00-d4c3-11ea-9d73-252916573797.jpg)
![enb2020_8_2_11_47_15](https://user-images.githubusercontent.com/67993113/89129450-138de900-d4c3-11ea-8eac-8fb30e611f38.jpg)
![enb2020_8_2_11_47_18](https://user-images.githubusercontent.com/67993113/89129453-14bf1600-d4c3-11ea-9b15-3a55cbe59d6c.jpg)

Either the recipe is wrong or the sword is valued too much. Can also be smelted into an ebony ingot despite not needing once for crafting. EDIT: Looks like the blacked steel armor set can be smelted into dwarven ingots despite not calling for it in the recipe.

![enb2020_8_2_00_44_15](https://user-images.githubusercontent.com/67993113/89117031-02f85700-d460-11ea-889c-c1e458fb1918.jpg)
![enb2020_8_2_00_44_19](https://user-images.githubusercontent.com/67993113/89117033-07bd0b00-d460-11ea-883a-2ec35cd36b98.jpg)
same sword but two different recipes and values

![enb2020_8_2_00_50_22](https://user-images.githubusercontent.com/67993113/89117701-7ea8d280-d465-11ea-9b19-94d5d8f6ecd4.jpg)
![enb2020_8_2_02_10_00](https://user-images.githubusercontent.com/67993113/89117703-82d4f000-d465-11ea-98a2-f8f651e71e85.jpg)
Recipes seem too resource hungry. Also the two handed version is valued much higher than the one handed version.

![enb2020_8_2_00_52_50](https://user-images.githubusercontent.com/67993113/89117987-d6e0d400-d467-11ea-8b1a-145576fbdc0a.jpg)
Two different recipes but one requires more resources. Swords have the same ID.

![enb2020_8_2_00_54_03](https://user-images.githubusercontent.com/67993113/89118014-30490300-d468-11ea-934d-b1f2a0bb3326.jpg)

![enb2020_8_2_00_54_59](https://user-images.githubusercontent.com/67993113/89118020-3ccd5b80-d468-11ea-82ae-220ee0477aa0.jpg)

![enb2020_8_2_00_56_08](https://user-images.githubusercontent.com/67993113/89118026-448d0000-d468-11ea-83b7-9978ca1ad38a.jpg)

![enb2020_8_2_00_57_05](https://user-images.githubusercontent.com/67993113/89118037-4f479500-d468-11ea-8d2b-89dca1c890ab.jpg)

![enb2020_8_2_00_58_26](https://user-images.githubusercontent.com/67993113/89118043-57073980-d468-11ea-8fc0-5aec8832373c.jpg)

![enb2020_8_2_00_59_25](https://user-images.githubusercontent.com/67993113/89118050-64bcbf00-d468-11ea-95bd-68b32ab9cdcd.jpg)

![enb2020_8_2_01_00_33](https://user-images.githubusercontent.com/67993113/89118057-6c7c6380-d468-11ea-9826-966bc2adc6c5.jpg)

![enb2020_8_2_01_03_29](https://user-images.githubusercontent.com/67993113/89118064-71411780-d468-11ea-8606-c29201d5a51a.jpg)

![enb2020_8_2_01_04_36](https://user-images.githubusercontent.com/67993113/89118070-7aca7f80-d468-11ea-8ecc-91de70d36bf4.jpg)

![enb2020_8_2_01_04_43](https://user-images.githubusercontent.com/67993113/89118075-828a2400-d468-11ea-8625-7abc46454599.jpg)

![enb2020_8_2_01_05_34](https://user-images.githubusercontent.com/67993113/89118079-8b7af580-d468-11ea-9a5d-fdaeb58fda39.jpg)

![enb2020_8_2_01_06_28](https://user-images.githubusercontent.com/67993113/89118081-90d84000-d468-11ea-8cd2-b47173f84781.jpg)

![enb2020_8_2_01_08_32](https://user-images.githubusercontent.com/67993113/89118086-a188b600-d468-11ea-8f85-6737ad9f12b2.jpg)

![enb2020_8_2_01_08_39](https://user-images.githubusercontent.com/67993113/89118090-a77e9700-d468-11ea-95fd-b94c5e62b43f.jpg)

![enb2020_8_2_01_10_01](https://user-images.githubusercontent.com/67993113/89118098-ad747800-d468-11ea-827e-a5d3dc2ca415.jpg)

![enb2020_8_2_01_10_43](https://user-images.githubusercontent.com/67993113/89118139-f3314080-d468-11ea-86f9-737c4a218dc5.jpg)

![enb2020_8_2_01_21_47](https://user-images.githubusercontent.com/67993113/89118144-f6c4c780-d468-11ea-8c55-b3f64e00bf67.jpg)

![enb2020_8_2_01_21_55](https://user-images.githubusercontent.com/67993113/89118150-fb897b80-d468-11ea-84f7-1ec6a8d20121.jpg)

![enb2020_8_2_01_22_04](https://user-images.githubusercontent.com/67993113/89118154-ffb59900-d468-11ea-882a-c1df26bbe341.jpg)

![enb2020_8_2_01_22_23](https://user-images.githubusercontent.com/67993113/89118158-0512e380-d469-11ea-887b-dac3ca8548fe.jpg)

![enb2020_8_2_01_22_30](https://user-images.githubusercontent.com/67993113/89118161-09d79780-d469-11ea-937e-391c855e7568.jpg)

![enb2020_8_2_01_22_37](https://user-images.githubusercontent.com/67993113/89118168-0d6b1e80-d469-11ea-9a28-c7be72ea33d1.jpg)

![enb2020_8_2_01_23_12](https://user-images.githubusercontent.com/67993113/89118173-1360ff80-d469-11ea-9a5b-01a767e113ad.jpg)

![enb2020_8_2_01_23_22](https://user-images.githubusercontent.com/67993113/89118175-178d1d00-d469-11ea-96e4-367aa5c0e1a7.jpg)

![enb2020_8_2_01_23_28](https://user-images.githubusercontent.com/67993113/89118182-1bb93a80-d469-11ea-8254-b243a9b64a49.jpg)

![enb2020_8_2_01_23_34](https://user-images.githubusercontent.com/67993113/89118187-22e04880-d469-11ea-83d1-a2a8329b9e43.jpg)

![enb2020_8_2_01_23_41](https://user-images.githubusercontent.com/67993113/89118190-296ec000-d469-11ea-9590-90f1f9e97e0c.jpg)

![enb2020_8_2_01_23_45](https://user-images.githubusercontent.com/67993113/89118193-2e337400-d469-11ea-87db-40b3e478ad90.jpg)

![enb2020_8_2_01_23_51](https://user-images.githubusercontent.com/67993113/89118201-32f82800-d469-11ea-9037-112788f79e97.jpg)
It seems like all the armors and weapons added by NordwarUA's Vanilla Armors and Weapons Expansion are being duplicated.
The Northern Banded Iron Shield, Iron Armor with Pauldrons and Reinforced Steel Armor only appear in the crafting menu when the PC has all the mats needed to craft it. 
Also the Northern Iron Sword, War Axe and Mace can all be smelted into an Ebony Ingot.

![enb2020_8_2_12_10_15](https://user-images.githubusercontent.com/67993113/89129536-ad559600-d4c3-11ea-86ce-c21303601b11.jpg)
Bow is more powerful than other bows from the same mod despite it having low-tier mats needed. 

![enb2020_8_2_12_16_10](https://user-images.githubusercontent.com/67993113/89129584-0b827900-d4c4-11ea-81b1-00ee9cea44e4.jpg)
![enb2020_8_2_12_16_08](https://user-images.githubusercontent.com/67993113/89129585-0b827900-d4c4-11ea-812b-e22a197c7976.jpg)
![enb2020_8_2_12_16_06](https://user-images.githubusercontent.com/67993113/89129586-0c1b0f80-d4c4-11ea-99b7-51effc5d4591.jpg)
![enb2020_8_2_12_16_03](https://user-images.githubusercontent.com/67993113/89129587-0c1b0f80-d4c4-11ea-8e57-4fcfa4a53d21.jpg)
![enb2020_8_2_12_16_17](https://user-images.githubusercontent.com/67993113/89129588-0cb3a600-d4c4-11ea-8af3-10c115d8a0b3.jpg)
![enb2020_8_2_12_16_15](https://user-images.githubusercontent.com/67993113/89129589-0cb3a600-d4c4-11ea-9737-fb2bb223fa65.jpg)
![enb2020_8_2_12_16_13](https://user-images.githubusercontent.com/67993113/89129590-0d4c3c80-d4c4-11ea-9111-01d3046ea2df.jpg)
Dupe sets that cost less resources, but only show up in the menu when having the mats to craft them.

**Additional context**
I'll update this issue when I find more instances.

**Comment by TwistedModding** [comment]
I believe the "missing armor" ones are a variant of ranger armor looking at the resources it requires to make them.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1, please continue to report these as you find them. Thanks!
