### ISSUE TITLE
Textures missing from shield, inconsistent though, not sure whats happening

### ISSUE THREAD

**Issue by irxsh** [ForgottenGlory/Living-Skyrim-2#354]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v2.2.0

**Describe the bug**
I've been experiencing a bug where some shields are purple, indicating missing textures. It seems to be the 'viking shields' that are the culprit. Also noticed it will unequip the 'Field Officer Armor'.

**To Reproduce**
Equipping the shield at times will put in on your back and have no texture, other times it will stay on your hand and have textures, if you equip it an unsheathe your weapons + shield, it will have textures.

**Expected behavior**
I expected the shield to have textures

**Screenshots**

[My most recent save and screenshots of the issue.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5012412/My.most.recent.save.and.screenshots.of.the.issue.zip)

**Comment by TwistedModding** [comment]
You need to have the items selected in the console for glory to fix and post them here. No point to make them a zip file.

**Comment by irxsh** [comment]
@TwistedModding, it wouldn't let me attach the save file because it wasn't a file they accepted, so I zipped all of it together instead. I will post another SS if i can of the item selected in console.

**Comment by irxsh** [comment]
![enb2020_8_2_17_27_43](https://user-images.githubusercontent.com/69116845/89127489-565cba80-d4dd-11ea-91bc-cd2cdc72edae.jpg)

**Comment by irxsh** [comment]
I see one hour ago Glory opened an issue for vanilla start on ASLAL, I actually chose vanilla start for this playthrough, if that means anything.

**Comment by TwistedModding** [comment]
Its a problem with allgud and these viking shields. Has been here for a while.

**Comment by irxsh** [comment]
I haven't had any real issues besides this and the hadvar bug which is known, so hopefully I don't have anything more to worry about. Thanks for the info also.

**Comment by MysticDaedra** [comment]
Ah, was just coming here to post this. Having the same problem... although the textures are only missing when the shield is displayed on my characters back. When on the arm in "combat mode", or on the ground/in SkyUI, the textures are visible.

**Comment by vaderdog23** [comment]
Same as MysticDaedra

**Comment by ForgottenGlory** [comment]
Kind-of fixed 2.2.1
