### ISSUE TITLE
Forgotten Magic not working with Sustained Magic?

### ISSUE THREAD

**Issue by Erokla** [ForgottenGlory/Living-Skyrim-2#355]
**LS Version**
2.2

**Describe the bug**
Magic buffs that last only a minute.

**To Reproduce**
Buy Frost armor, Divine armor etc.. from a Forgotten Magic seller and use the spell.

**Expected behavior**
Instead of a min I expect it to last a day like other buff spells.

**Screenshots**
![enb2020_8_2_18_41_59](https://user-images.githubusercontent.com/69058497/89127799-dfc9b800-d4f0-11ea-9056-a290ffc95645.jpg)

**Additional context**
I only tried Frost Armor since I couldn't find any other and I don't know their ids so maybe the rest works.

**Comment by baldone98** [comment]
That is probably intended because with sustained magic those spells would be broken powerful.

**Comment by ForgottenGlory** [comment]
Intended, Forgotten Magic would be way too powerful if Sustained affected it.
