### ISSUE TITLE
Mercer and Brynjolf BFB

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#356]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0

**Describe the bug**
BFB on Mercer and Brynjolf

**To Reproduce**
find them

**Expected behavior**
no bfb

**Screenshots**

![brynjolf](https://user-images.githubusercontent.com/62785432/89128595-58fae800-d4bc-11ea-9195-864396b3ec8e.png)
![mercer](https://user-images.githubusercontent.com/62785432/89128598-5ac4ab80-d4bc-11ea-8ceb-c239d182ddb1.png)

**Additional context**

**Comment by tjbassoon** [comment]
Confirmed in my install as well.

**Comment by TwistedModding** [comment]
Sent glory the fix for this.

To glory, close this whenever you incorporate the fixes.

**Comment by WonkyDialup** [comment]
Same issue here, as well as random CTD inside the Thieves Den.

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
