### ISSUE TITLE
Forgotten City, Looter Bug(no spawns)

### ISSUE THREAD

**Issue by Hoplite1** [ForgottenGlory/Living-Skyrim-2#357]
**LS Version**
Version 2.1.3.3

**Describe the bug**
During the main quest of forgotten city, just after you finish meeting the Jarl, you leave the citadel, and a woman near the main entrance to the city, says that looters are breaking in to the city, and that they have to be stopped before they break the dwarf law. A script then makes all the villagers flee, and go hide in buildings until they are taken care of. So I went looking for these looters in the entrance passage, but apparently they never spawned. I am not sure if this quest is required to finish this mods main quest, but the music is stuck in this dramatic combat music, and all the townspeople are cowering in their homes, with no looters to be found. I found on the modpage someone suggested typing this.... "setstage FCQuest02 700" into console. it did not work

**To Reproduce**
Do the main quest of Forgotten City

**Expected behavior**
The quest script should spawn some looters. I think. 

**Screenshots**

**Additional context**
Someone else in discord was having the exact same issue, so I am not a unique case!
![ScreenShot280](https://user-images.githubusercontent.com/69118114/89129293-68168000-d526-11ea-91d8-caa262724f88.png)

**Comment by ForgottenGlory** [comment]
The correct console command is "setstage 000FCQuest02 700". I am unsure what could be causing this - possibly script lag, the entire quest is scripted so there's an enormous amount of things happening while this quest is going on. I'm open to hearing about possible fixes for this.

**Comment by Ghtshrine** [comment]
I ran the entire forgotten city with most of the different endings on 2.2.0 I did not have any issues with the looters spawning. 
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5044614/saves.zip) Save provided right as she runs up to the player to give the quest. The only thing issues I came across throughout the mod was one type of looter did not have any weapons equipped and you get no xp for any of the optional objectives so you get hardly any xp for this.

This quest also doesn't really stop the main quest and you can get most of the endings without it. Only stops you from one accusation. But doesn't stop you from getting the true ending or really the other main endings/bad endings.
