### ISSUE TITLE
Readme update? - Can't choose your path when you get the message to choose your path.

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#36]
![ScreenShot188](https://user-images.githubusercontent.com/11461193/82402647-33605580-9a1a-11ea-9e3b-93b09bfcd7ee.png)
 Get the following message.

**Comment by pgdeaner** [comment]
Did someone update the readme?  It's kind of confusing when the mod prompts you to choose your path and then you get told that your skills are not high enough.  You never get prompted again.

**Comment by ForgottenGlory** [comment]
You can use the power from your magic menu to select your class at any time to check the status of being able to select a path.
