### ISSUE TITLE
CTD when entering Redspire Manor

### ISSUE THREAD

**Issue by JWRaven** [ForgottenGlory/Living-Skyrim-2#360]
Thank you soooo much for this Awesome modlist!

LS Version: 2.20 - Reporting a CTD when entering Redspire Manor for the first time.  Crash log attached.  Any suggestions for a fix would be appreciated.  Thank you!

[Crash_2020_8_2_15-21-12.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5013211/Crash_2020_8_2_15-21-12.txt)

**Comment by TwistedModding** [comment]
You are missing plugins from your load order.

Rule 11. If you make modifications to these Modlists, you do so at your own risk. Unless otherwise specified, no support will be provided.

**Comment by JWRaven** [comment]
I have not made any changes to the Modlist.  Since I am not familiar with the crash reports, I would appreciate if you could tell me which plugins are missing.

**Comment by ForgottenGlory** [comment]
It does appear that you're missing mods, I'd recommend re-installing the modlist.

**Comment by JWRaven** [comment]
Thank you!  I reinstalled and everything is fine now.  Great work on the Modlist - MUCH Appreciated!
