### ISSUE TITLE
[2.2.0] Hunterborn Field Dress - QuickLoot Interaction

### ISSUE THREAD

**Issue by Jefferoni-Maloni** [ForgottenGlory/Living-Skyrim-2#362]
**LS Version**
2.2.0

**Describe the bug**
After field dressing an animal using Hunterborn, QuickLoot will show a "Cleaned Carcass Token" as an item you can take out. This token is not normally visible in the animal's inventory. If you take the token out using QuickLoot, Hunterborn will think the animal hasn't been field dressed yet.

**To Reproduce**
1. Field dress animal
2. Look in its inventory using QuickLoot

**Expected behavior**
QuickLoot should not show the Cleaned Carcass Token.

**Screenshots**
![enb2020_8_3_18_52_01](https://user-images.githubusercontent.com/26368662/89238126-a9f10600-d5ba-11ea-971c-470d78c3a945.png)

**Comment by Exoticusgaming** [comment]
I found a possible solution to the issue: https://www.reddit.com/r/skyrimmods/comments/ajrsd4/i_using_both_hunterborn_se_and_quick_loot_re_and/ef8ao13?utm_source=share&utm_medium=web2x

**Comment by TwistedModding** [comment]
Its not an option in the new version of quickloot, that "fix" will not work.

**Comment by ForgottenGlory** [comment]
The author of QuickLoot seems to be aware of this issue, it likely will be fixed in a future update of QuickLoot.
