### ISSUE TITLE
Weird lighting affect on Mirai companion

### ISSUE THREAD

**Issue by bobjane01** [ForgottenGlory/Living-Skyrim-2#363]
![enb2020_8_5_12_31_58](https://user-images.githubusercontent.com/69025964/89365410-e38b5380-d717-11ea-9ff1-a7b5676f4b5b.jpg)

Hey all,

I getting odd lighting effects  on Mirai, anyone has having the same issue? 

cheers

**Comment by jokerstyle00** [comment]
Is she using Oakflesh? The -flesh spells all have different shaders now.

**Comment by combatmaster1o3** [comment]
Unless you are sure she didn't cast Oakflesh, that's Oakflesh's visual effect.

**Comment by bobjane01** [comment]
Ah that makes sense , sorry to bother yous.
