### ISSUE TITLE
Small text

### ISSUE THREAD

**Issue by SoulSorrow** [ForgottenGlory/Living-Skyrim-2#364]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Downloaded it yesterdat

**Describe the bug**
The text is while playing (Info (E), subtitles, info in upper left corner) is very small.

**To Reproduce**
Reloaded the game a few times, tried a new save.

**Expected behavior**
I expected the text to be large enough to read comfortably.

**Screenshots**
Apparently I can't take screenshots either. Some text appears in the upper left corner but it's too small to read.
Took a picture with my phone, it'll have to do.
![IMG_20200806_073742](https://user-images.githubusercontent.com/69292114/89495162-f9505580-d7b7-11ea-8851-862dac95af12.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Unsure what's up with this, you can adjust the size of the text using SkyUI or SkyHUD.
