### ISSUE TITLE
Mega-Expensive Fruits and Veggies?

### ISSUE THREAD

**Issue by TornadoWatch** [ForgottenGlory/Living-Skyrim-2#365]
On my new game, certain consumable vegetables (Like potatoes, lettuce, apples, and carrots--But not cheese, mead, or gourds) are absurdly expensive.

I noticed this after picking a field of vegetables and turning them in for pay, then realizing that I had made over **two thousand gold.**

Is this intended?

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
