### ISSUE TITLE
Depths of Skyrim - Mod Suggestion

### ISSUE THREAD

**Issue by jchritton** [ForgottenGlory/Living-Skyrim-2#366]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**To submit a mod for consideration, you must attach a copy of your save game where you have defeated Alduin using an unmodified LS installation. Any suggestions without this attached will be automatically rejected. This is not a guarantee that the mod will be included.**

[Save310_8522519E_0_4B617465204C696C69656E7468616C_Tamriel_021009_20200802020225_26_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5039531/Save310_8522519E_0_4B617465204C696C69656E7468616C_Tamriel_021009_20200802020225_26_1.zip)

**Mod Name**
The name of the mod.

Depths of Skyrim - An Underwater Overhaul SSE

**Mod Link**
A link to the mod's webpage.

https://www.nexusmods.com/skyrimspecialedition/mods/26913

**Why?**
Why do you think this mod should be included in LS?

All of the areas and landscape of LS2 feel alive and vibrant, so it's even more jarring when you go under the water and see basically a complete void. This mod has been really the only competitor that I've seen in making the underwater areas feel more fulfilling, and it seems to require fairly minimal patching (I set it up with LS 2.2.0 and everything seems to work fine with tiny patches for ELE and RW2, though I didn't go through with a fine-toothed comb).

**Additional context**

**Comment by ForgottenGlory** [comment]
I'd be curious to know what this accomplishes that Sea of Spirits doesn't. Genuine curiosity here, I'm not familiar with Depths of Skyrim.

**Comment by jchritton** [comment]
@ForgottenGlory Sea of Spirits looks like it's only adding new aquatic animals to that zone, Depths of Skyrim adds plant life (so like seaweed, algae, etc) to the bottoms of rivers/ocean areas, in addition to some explorable places from what I've seen (treasure chests in a little underwater hole). I haven't thoroughly explored the Sea of Ghosts, but I know the difference is huge for rivers especially.

**Comment by ForgottenGlory** [comment]
Added 2.4.0
