### ISSUE TITLE
Tree growing directly in front of Missives board in Whiterun.

### ISSUE THREAD

**Issue by LunarDelta** [ForgottenGlory/Living-Skyrim-2#367]
Currently using version 2.2.0

**Describe the bug**
A tree is growing *right* in front of the Missives board in Whiterun. The board still works, but damn does it look awkward.

**To Reproduce**
Go to Whiterun and look at the Missives board.

**Expected behavior**
No trees blocking the Missives board.

**Screenshots**
![SkyrimSE 2020-08-07 06-56-53](https://user-images.githubusercontent.com/29786040/89640103-df2c7b00-d87c-11ea-9d87-8fa7553aff04.png)
![SkyrimSE 2020-08-07 06-57-25](https://user-images.githubusercontent.com/29786040/89640123-e9e71000-d87c-11ea-9938-f6264d1bf380.png)
![TreePNG](https://user-images.githubusercontent.com/29786040/89675377-d0af8500-d8b7-11ea-9771-4953eea0f416.png)

**Comment by ForgottenGlory** [comment]
Fixed 2.2.1
