### ISSUE TITLE
Ravage dual wielding from ordinator affecting swing speed in unintended ways

### ISSUE THREAD

**Issue by AstridCone** [ForgottenGlory/Living-Skyrim-2#369]
**LS Version**
Put the version of the list you are on here.
v2.2.0

**Describe the bug**
The ravage perk doesnt work as intended, instead of/in addition to speeding up dual wield attack (Left and right attack at the same time), it makes the weaponspeedmult outrageously fast. So your right hand attacks and dual wield power attacks are sped up by a crazy amount

**To Reproduce**
aquire the Ravage perk in the one handed perk tree, then try attacking

**Expected behavior**
Make dual wield attacks, ordinary and power attacks, 20%/35% faster depending on rank

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
I guess I would recommend some kind of weapon speed fix mod, i dont usually try dual wield builds, but this also seems to also affect dual wielding enemies who have the perk. I was under the impression someone already put this up on the github since someone on the discord told me so, but i guess i was wrong?

**Comment by AstridCone** [comment]
Im not very experienced writing bug reports

**Comment by ForgottenGlory** [comment]
This is intended, a recent inclusion of https://www.nexusmods.com/skyrimspecialedition/mods/27677 made it so that attack speed changes get added together. It definitely can make your character attack extremely quickly.
