### ISSUE TITLE
Broken MCM Translations

### ISSUE THREAD

**Issue by electraumatized** [ForgottenGlory/Living-Skyrim-2#370]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.1

**Describe the bug**
Translations for MCMs are broken for some mods: Achieve That, Timing is Everything, and Thieves Guild Requirements

**To Reproduce**
Start a new game and open the MCM menu

**Expected behavior**
Translations should not be broken.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![enb2020_8_8_02_27_10](https://user-images.githubusercontent.com/66895387/89705009-0fc4f100-d91f-11ea-8ae6-92f19a01f83c.jpg)

**Additional context**
Possibly from Merge rebuild I saw in stream before the update?

**Comment by electraumatized** [comment]
Does come from the Gameplay merge, I have posted a temporary fix in community-additions in discord.

**Comment by TwistedModding** [comment]
You only need to rebuild the merge for it to fix.

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
