### ISSUE TITLE
Widescreen not working

### ISSUE THREAD

**Issue by arcadayn** [ForgottenGlory/Living-Skyrim-2#373]
**LS Version**
2.2

**Describe the bug**
I initially started the game without enabling the Complete Widescreen fix. I was initially trying to run at 3440x1440.  After experiencing the widescreen issue with title screen menus and the race creation menu, I quit the game, found the Complete Widescreen enabler, and restarted the game. Unfortunately, the issue persists. I did check the skyrimprefs.ini to make sure it had the proper values entered.

**Expected behavior**
Widescreen fix to apply and allow me to see menus fully.

**Comment by ForgottenGlory** [comment]
Sounds like possibly the resolution wasn't set correctly, make sure it's set using BethINI. If not, screenshots please and feel free to hop into the LS Discord to get further help - I think several people have had a similar issue and should be able to help.
