### ISSUE TITLE
Logging = 1 in CBPCsystem.ini but it should be = 0

### ISSUE THREAD

**Issue by Flopsy007** [ForgottenGlory/Living-Skyrim-2#377]
Not really a bug, but if I understand it correctly I think this ini-file setting is supposed to be changed from 1 to 0 to avoid unessesary use of disk space and to increase performance:

In CBPCSystem.ini logging is set to 1.
In the ini-file it is stated:   #Set this to 1 to enable logging. This decreases performance, so don't play with this on. Also the file generated will be huge if played long.

In LS2 discord a few folks report huge log files and some have changed it and report performance gains.

In CBPC forums on Nexus this is also mentioned and someone reported an 18 fps gain (which may not be as much in LS2 of course)

**Comment by TwistedModding** [comment]
I would also recommend changing UseParallelProcessing = 0 to UseParallelProcessing = 2 in the CBPCsystem.ini. Has a chance to greatly increase performance when there are a lot of npcs that have physics enabled.

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
