### ISSUE TITLE
Bug texture boat morthal

### ISSUE THREAD

**Issue by PizzaSodebo** [ForgottenGlory/Living-Skyrim-2#379]
I’m telling you about texture problems on morthal boats
Screen here :
https://cdn.discordapp.com/attachments/690613668836016178/743133958262489208/The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2020.08.12_-_17.47.55.78.png

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
