### ISSUE TITLE
Dawnguard Map Markers

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#380]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**To submit a mod for consideration, you must attach a copy of your save game where you have defeated Alduin using an unmodified LS installation. Any suggestions without this attached will be automatically rejected. This is not a guarantee that the mod will be included.**

**Mod Name**
Dawnguard Map Markers

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/20931?tab=files

**Why?**
Gives map markers for the Soul Cairn, thought this should be included as there are other mods in the list that make the map more "complete" with map markers.

**Additional context**

**Comment by ForgottenGlory** [comment]
Added 2.3.0
