### ISSUE TITLE
Old Hroldan inn services unavailable due to out of bounds innkeeper & more

### ISSUE THREAD

**Issue by AstridCone** [ForgottenGlory/Living-Skyrim-2#382]
**LS Version**
Put the version of the list you are on here.
2.2.1

**Describe the bug**
Serveral things inside the inn are inaccessible including the innkeeper as they are outside of where the player can interact without turning off collision, basically they are "outside". This includes the cellar (Skyrim Underground im guessing), a unique treasures beverage and as i mentioned the innkeeper. there is also a Museum flyer floating in the hallway but thats not the issue here.

**To Reproduce**
Enter the inn i guess

**Expected behavior**
I expected the contents of the interior to be in line with the old hroldan revamp mod, whatever it was called

Im going to lay off doing the quest with the ghost guy and resting here for now, did tcl grab the drink though

**Comment by Arathrax** [comment]
Just saw this too.

**Comment by ForgottenGlory** [comment]
Possibly fixed 2.3.0, followup on this.
