### ISSUE TITLE
adding undeath remastered 

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#383]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**To submit a mod for consideration, you must attach a copy of your save game where you have defeated Alduin using an unmodified LS installation. Any suggestions without this attached will be automatically rejected. This is not a guarantee that the mod will be included.**

**Mod Name**
undeath remastered

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/6180
**Why?**
this adds a decent of content that is interesting for evil builds and good builds alike. adds three new dungeons and a couple of new spells and a bit more. Also adds a new type of transformation that is mage centered, a lich. plus it mainly uses vanilla textures so a lot less bugs   

**Additional context**
Add any other context or screenshots about the
[Logan's alduin save.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5072453/Logan.s.alduin.save.zip)

**Comment by bthames** [comment]
What patches are you running with Undeath? I know there are quite a few.

**Comment by KNGLogan** [comment]
i have none most are for different languages

**Comment by KNGLogan** [comment]
moon and star patch
