### ISSUE TITLE
Bonemold Helmet is from improved closed face, but the head is invisible

### ISSUE THREAD

**Issue by bthames** [ForgottenGlory/Living-Skyrim-2#384]
**LS Version**
2.2.1

**Describe the bug**
The head is hidden for the Bonemold helmet.

**To Reproduce**
Visit Raven Rock

**Expected behavior**
The head to be visible through the eye visor.

**Comment by TwistedModding** [comment]
You need to post a screenshot of the item in question selected in the console for it to be fixed.

**Comment by bthames** [comment]
![enb2020_8_15_22_23_06](https://user-images.githubusercontent.com/43176390/90325177-7c0aaa80-df46-11ea-8e7e-b52224ef562b.jpg)

**Comment by TwistedModding** [comment]
needs to be a picture of the helmet selected in the console

**Comment by bthames** [comment]
I tried to kill him and loot it but he was marked as essential, not sure which helmet he's using. When I searched the console there were dozens of bonemold helmets :(

**Comment by Day7-J** [comment]
I don't have the game open, but it's the ordinator version for guards or whatever, so if you can find that one it should be it

**Comment by ForgottenGlory** [comment]
Should be fixed 2.3.0
