### ISSUE TITLE
Hunterborn bugs out skyrim with quickloot

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-2#388]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.1

**Describe the bug**
while trying to skin the animal, i accidentally looted the "cleared carcass token" which suddenly bugged out skyrim, i couldn't save, or move my camera up and down, only left to right

**To Reproduce**
looting the token off the animal before you've fully cleaned it

**Expected behavior**
doing a full hunterborn, clean corpse, harvest ingredients etc without glitching the game out

**Screenshots**
![20200816234242_1](https://user-images.githubusercontent.com/68168803/90345660-78e0ee80-e01a-11ea-86c7-15ccf48ed1d1.jpg)
![20200816234254_1](https://user-images.githubusercontent.com/68168803/90345661-7a121b80-e01a-11ea-9c98-edc50a03b5f6.jpg)

**Additional context**

**Comment by TwistedModding** [comment]
yes its known, nothing we can do about it until quickloot gets updated to fix it.

**Comment by ForgottenGlory** [comment]
The QuickLoot author is aware of the issue, hopefully it will be fixed at some point.
