### ISSUE TITLE
Black Face bug Erandur

### ISSUE THREAD

**Issue by combatmaster1o3** [ForgottenGlory/Living-Skyrim-2#389]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.1

**Describe the bug**
Black Face bug on Erandur

**To Reproduce**
Look at Erandur

**Expected behavior**
Erandur to look cool

**Screenshots**
![enb2020_8_16_21_32_33](https://user-images.githubusercontent.com/67399578/90349830-2945f700-e009-11ea-9961-62b014683245.png)
![enb2020_8_16_21_32_21](https://user-images.githubusercontent.com/67399578/90349837-2d721480-e009-11ea-873d-a606720a2895.png)

**Additional context**

**Comment by cepritchard** [comment]
I've got the same issue.

**Comment by JaxomofRuatha** [comment]
Just figured I'd put as an FYI all the 2.2.1 BFBs I found for my patch, didn't change anything that I'm aware of with my other mods:

Golldir - 00019FE8
Erandur - 0002427D
Vorstag - 000B997F
Madanach - 000133A7
Benor - 000135E8
Marcurio - 000B9980
Belrand - 000B9981
Stenvar - 000B9983

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
