### ISSUE TITLE
Floating bed stuck to door on other side of river in Ivarstead

### ISSUE THREAD

**Issue by jordan0422** [ForgottenGlory/Living-Skyrim-2#394]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0

**Describe the bug**
Floating bed that is stuck to the door of a house in Ivarstead. The location is where Narfi used to be. Bed is needed for Interesting NPCs quest (3DNPC). Interferes with ending of 3DNPCs quest "Idle Dreams" if not addressed.

**To Reproduce**
1) Go to Ivarstead
2) Go to the other side of the river where Narfi usually hangs out
3) Look at the front door of the house and you'll see the stuck floating door.

**Expected behavior**
Will interfere with ending of Interesting NPCs quest "Idle Dreams" if not addressed as NPC Amicus and also bed will be stuck inside the house. The only way to complete the quest is to TCL through the house in order to speak to Amicus.
![ScreenShot281](https://user-images.githubusercontent.com/69283337/90579861-20296700-e17c-11ea-8524-24726d504518.png)

Bed stuck inside house:

![ScreenShot282](https://user-images.githubusercontent.com/69283337/90702679-adce8a80-e240-11ea-80a7-ed22df22b9a7.png)
![ScreenShot283](https://user-images.githubusercontent.com/69283337/90702684-b45d0200-e240-11ea-8dbe-2784898efcb0.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
