### ISSUE TITLE
Rift Mountain Pass SouthWall Gate stuck in ground.

### ISSUE THREAD

**Issue by Asellia** [ForgottenGlory/Living-Skyrim-2#396]
**LS Version**
2.2.1

**Describe the bug**
The RTSouthGate01.nif is sunken into ground, seemingly. Loading and reloading does not fix this. I also, once, experienced freezes when saving in the area- however, I could not gather a crash log as I had left it open overnight when it completely froze, and it never unfroze/closed. Closing it via task manager after 8 hours did not save the crash log.

**To Reproduce**
Goto this location, I think? It's always there for me!

**Expected behavior**
I assume this should be above ground

**Screenshots**
![SkyrimSE 2020-08-20 17-14-58](https://user-images.githubusercontent.com/5147623/90827912-171ad000-e30b-11ea-9bd3-b2f2a65e8fcf.png)
![SkyrimSE 2020-08-20 17-25-26](https://user-images.githubusercontent.com/5147623/90827921-18e49380-e30b-11ea-9f37-ec1a1bbf1621.png)
![SkyrimSE 2020-08-20 17-26-15](https://user-images.githubusercontent.com/5147623/90827923-1aae5700-e30b-11ea-8e56-44203bc95cdd.png)

**Additional context**
As a note, I am running on a standard HDD as I cannot yet afford a better SSD. The rest of my computer is fine, and the list runs great other than loading times. If this has to do with it, my apologies- I can check when I do afford the SSD if it fixes it, of course!

**Comment by ForgottenGlory** [comment]
This looks correct to me, are there areas that are inaccessible at this location?

**Comment by Asellia** [comment]
Oh, no, it's accessible. I was just assuming it was off-- people on horseback barely fit underneath it at all, and so I just assumed it was sunken into the ground. My apologies.
