### ISSUE TITLE
Fort Dawnguard floating/missing door issues

### ISSUE THREAD

**Issue by jordan0422** [ForgottenGlory/Living-Skyrim-2#398]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0

**Describe the bug**
Floating door located on the roof of Fort Dawnguard. See picture.
Missing door that leads to a staircase going nowhere. See picture.

**To Reproduce**
For floating door:
1) Go to the roof of Fort Dawnguard.
2) Look around until you see the floating door (roof area is fairly small so shouldn't take long)

For missing door:
1) Enter and then exit one of the side doors leading to Dayspring Canyon on the 1st floor of Fort Dawnguard (don't use the main entrance). May need to test out both doors on the 1st floor.

**Expected behavior**
Door not floating and attached to wall.

**Screenshots**
Roof door:
![ScreenShot287](https://user-images.githubusercontent.com/69283337/90967014-270eed00-e48e-11ea-87d3-309b50b6cef2.png)
![ScreenShot288](https://user-images.githubusercontent.com/69283337/90967019-3b52ea00-e48e-11ea-8ea1-63dcb7c179bc.png)

Missing door:
![ScreenShot289](https://user-images.githubusercontent.com/69283337/90967026-5a517c00-e48e-11ea-94dd-d5ca275cbed2.png)

**Comment by ForgottenGlory** [comment]
Should be fixed 2.3.0
