### ISSUE TITLE
Guard outside of Embershard was headless, naked, dead

### ISSUE THREAD

**Issue by Arathrax** [ForgottenGlory/Living-Skyrim-2#403]
**LS Version**
2.2.1

**Describe the bug**
The guard (Male Orc) outside was dead, naked and headless (meaning no head mesh was in place, not beheaded).
Inventory was still on him when I checked: Great Shield/Great Sword, Northern Kilt) guessing this is something to do with OBIS since it was named a Bandit Doomraider?
Important: After quitting and restarting game the head mesh was back in place however the guard was still dead.

**To Reproduce**
Started new game, walked to Embershard Mine entrance from Sleeping Giant Inn. Dead guard.

**Expected behavior**
Guard should not have been dead, fully clothed and had a head mesh? :)

**Comment by ForgottenGlory** [comment]
Most likely was killed by an animal or another NPC before you arrived.
