### ISSUE TITLE
Start of game: Cougar spawned infront of Sleeping Giant Inn (Riverwood)

### ISSUE THREAD

**Issue by Arathrax** [ForgottenGlory/Living-Skyrim-2#404]
**LS Version**
2.2.1

**Describe the bug**
Started a new game. There was a cougar right outside of Sleeping Giant Inn, started attacking townspeople.

**To Reproduce**
Start a new game, spawn in Sleeping Giant Inn. Exit Sleeping Giant Inn, it was to the immediate right.

**Expected behavior**
No predator creatures inside town for a new player.

**Additional context**
Bug probably related to Skytest or Animallica.

**Comment by ForgottenGlory** [comment]
Not a bug, unfortunately. Between SkyTEST and Animallica there are a lot more animals than normal so this sort of thing happens on occasion.
