### ISSUE TITLE
Clockwork display in LOTD  having problems

### ISSUE THREAD

**Issue by MsIllusiveGG** [ForgottenGlory/Living-Skyrim-2#406]
**LS Version**
2.21

**Describe the bug**
The Clockwork display is showing on the LOTD Checklist in the MCM as all but two of them items have been collected on a brand new game. No effort made to start Clockwork. Later, when Clockwork is completed, display objects are not displaying at all, or are half appearing such as Amalgam's breastplate is showing but nothing else of the statue. Objects collected are not displayed in the museum and not removed from inventory.

**To Reproduce**
Restarted the game twice, issue persists. Checked with additional individuals, all reporting the same issue.

**Expected behavior**
Please fix so the museum objects are taken from the inventory and displayed properly on the Clockwork display.

**Comment by MsIllusiveGG** [comment]
Issue can be fixed by moving DBM_Clockwork_Patch.esp and LOTD_TCC_Clockwork.esp underneath Clockwork.esp, which they are currently not.

**Comment by TwistedModding** [comment]
keep this open so glory sees it when he is updating the list.

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
