### ISSUE TITLE
Book reading Bug

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-2#407]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v2.2.1

**Describe the bug**
when trying to read a book, it makes a noise like unable to pick up and in stealth it auto loots it into inventory, sometimes if its not for the LoTD needed i dont want to pick it up,

**To Reproduce**
Steps to reproduce the behavior: try reading a lot of books in dragonsreach place

**Expected behavior**
read and have the option to steal it

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by JaxomofRuatha** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/11304 Isn't that the expected way for "Sometimes Pick Up Books" to work? Or am I misunderstanding what the issue is?

**Comment by Ashensakar** [comment]
> https://www.nexusmods.com/skyrimspecialedition/mods/11304 Isn't that the expected way for "Sometimes Pick Up Books" to work? Or am I misunderstanding what the issue is?

when im just trying to read it though it makes a sound basically that it cant do it

**Comment by KNGLogan** [comment]
that is how the mod works
gotta read it in your inventory

**Comment by Ashensakar** [comment]
> that is how the mod works
> gotta read it in your inventory

sometimes i just want to read it though and not pick it up

**Comment by WinterdrakeX** [comment]
You probably have your weapons drawn. Did you try reading with weapons sheathed?

**Comment by Ashensakar** [comment]
Not a bug, just had to learn how the mod works
