### ISSUE TITLE
Brown face bug on Benor in Morthal

### ISSUE THREAD

**Issue by LegitRob95** [ForgottenGlory/Living-Skyrim-2#408]
**LS Version**
v2.2.1

**Describe the bug**
A NPC in Morthal called Benor has the brown face bug.

**Expected behavior**
It to not happen and have the same color as his skin on his arms.

**Screenshots**
https://i.gyazo.com/8574bc3573724f495d00f1c517b8b033.png
https://i.gyazo.com/cb93f65248f5a3e5a5e307785ede2a26.jpg

**Additional context**
None

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
