### ISSUE TITLE
adding JS septims and coin purse

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#411]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**To submit a mod for consideration, you must attach a copy of your save game where you have defeated Alduin using an unmodified LS installation. Any suggestions without this attached will be automatically rejected. This is not a guarantee that the mod will be included.**

**Mod Name**
JS Purses and Septims SE

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/37306

**Why?**
LS has decent looking coins and purses but could be looking better

**Additional context**
requires no patching has no plugin, just put it into there and have excellent looking coins
[Logan's alduin save.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5140344/Logan.s.alduin.save.zip)

**Comment by ForgottenGlory** [comment]
Added 2.3.0
