### ISSUE TITLE
Many Staves only do a fraction of their listed damage. maybe only 10% of their damage rating

### ISSUE THREAD

**Issue by kevinsmith1212** [ForgottenGlory/Living-Skyrim-2#412]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.1.1

**Describe the bug**
Staffs / Staves many of the vanilla/modded ones especially do not do any damage e.g. Staff of Firebolts

**To Reproduce**
Start new game, do MCM, console in a staff, fire it at something and watch it do only 10% of posted damage. e.g. Staff of Firebolts seems to do only 1 damage to armoured guards, and only 1 damage to Bunny Rabbits or anything else. 

**Expected behaviour**
Staves to deliver listed damage

**Comment by ForgottenGlory** [comment]
Related to #413, most likely same cause for both.
