### ISSUE TITLE
BFB on certain characters (Marcurio, Erandur, Belrand, probably more.)

### ISSUE THREAD

**Issue by Cajohl** [ForgottenGlory/Living-Skyrim-2#416]
**LS Version**
2.2.1

**Describe the bug**
Certain characters such as Marcurio, Belrand and Erandur have black faces when they shouldn't.

**To Reproduce**
Just enter the Bee and Barb in Riften and look for Marcurio.

**Expected behavior**
The characters would have the appropriate skin tones.

**Screenshots**
https://i.gyazo.com/59db9521619a9e3d8805aea53c278783.jpg

**Additional context**
None.

**Comment by Cajohl** [comment]
More screenshots:
https://i.gyazo.com/8d4bd19d10f7db6f2431453623e2b444.jpg
https://i.gyazo.com/3a9354f9577defb6658346cfbfb8dee1.png
https://i.gyazo.com/bcbd29429183c729dae65a44dd722fec.jpg

**Comment by KNGLogan** [comment]
known bug fixed in latest

**Comment by KNGLogan** [comment]
wait im high nvm

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0
