### ISSUE TITLE
ETaC conflict in Riverwood

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-2#417]
There's a terrain conflict in Riverwood right near the apothecary's shop. NPCs cannot climb the stairs because they're under the terrain. Also, still getting random stuttering when looking at certain areas in Riverwood with this build (Alvor's home has a few of these 'hotspots), although otherwise the performance has improved.   

Using build 2.3.0.

![enb2020_9_4_07_00_13](https://user-images.githubusercontent.com/67465410/92239125-1a23cd80-ee80-11ea-8e34-da8ad16d2fb5.jpg)
![enb2020_9_4_07_17_02](https://user-images.githubusercontent.com/67465410/92239136-1c862780-ee80-11ea-8647-0cb7d9aa8d19.jpg)
![enb2020_9_4_07_16_43](https://user-images.githubusercontent.com/67465410/92239142-1ee88180-ee80-11ea-9158-f1b14b888f03.jpg)

EDIT: Almost certain this is a conflict with the JK Patches merge but I can't for the life of me find out which record to tweak; I can patch out the terrain issue by copying over ETaC's record, but that creates a huge seam in the land by the pile of logs near the river's edge.

**Comment by seanpbelcher** [comment]
And another conflict in Riverwood. Stairs on the side of the Sleeping Giant Inn, next to the horse stable, clip with the gate there. 

![enb2020_9_4_09_08_42](https://user-images.githubusercontent.com/67465410/92248763-c371c000-ee8e-11ea-91b0-224f1ebceccb.jpg)
![enb2020_9_4_09_07_51](https://user-images.githubusercontent.com/67465410/92248766-c5d41a00-ee8e-11ea-843a-425937342bda.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
