### ISSUE TITLE
Bad blood textures

### ISSUE THREAD

**Issue by Cajohl** [ForgottenGlory/Living-Skyrim-2#418]
**LS Version**
2.3.0

**Describe the bug**
Semi-transparent red squares where there should be blood.

**To Reproduce**
Kill something.

**Expected behavior**
Blood would look like blood (pools, spatters, etc.)

**Screenshots**
https://i.gyazo.com/ec1f406735d61c35c158c71b60408b08.jpg

**Additional context**
This may only occur in snow?

**Comment by Cajohl** [comment]
An especially bad example: https://i.gyazo.com/4c3d86d191202fe20aa93d6a1d647cc9.png

**Comment by TwistedModding** [comment]
which enb are you

**Comment by Cajohl** [comment]
> which enb are you using

Silent Horizons

**Comment by TwistedModding** [comment]
thought so, thats a bug in that enb.
