### ISSUE TITLE
Conjure Familiar Doesn't Work

### ISSUE THREAD

**Issue by sai0025** [ForgottenGlory/Living-Skyrim-2#419]
**LS Version**
2.3.0

**Describe the bug**
The Conjure Familiar spell has no effect. It does not use any magicka, does not add an effect, and does not conjure the familiar.

**To Reproduce**
Use the conjure familiar spell.

**Expected behavior**
The spell is meant to conjure a familiar.

**Screenshots**

**Additional context**

**Comment by TwistedModding** [comment]
https://discord.com/channels/605449136870916175/688593507966779453/752384735300419604 <--- Link to the fix.

**Comment by slymon99** [comment]
For those who haven't used xEdit (i.e. me) here's the detailed instructions (thanks to xomulus#5966 https://discord.com/channels/605449136870916175/688593507966779453/752651591152304209)

Open SSEEdit and select SkyRem - Grace.esp -> expand Spell -> select ConjureFamiliar entry -> on the right side of the window, expand Effects -> expand Effect #0 -> expand Conditions -> notice the 2 conditions where one Comparison Value is 0 and the other is 1? Change them both to be 1. -> close SSEEdit and save SkyRem - Grace.esp

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
