### ISSUE TITLE
NPC with dark faces.

### ISSUE THREAD

**Issue by b34nco** [ForgottenGlory/Living-Skyrim-2#420]
**LS Version**
2.3.0

**Describe the bug**
NPC dark faces

**To Reproduce**
I found Eorlund Gray-Mane and a Witerun Guard with the problem, did not check other places.

**Expected behavior**
-

**Screenshots**
![enb2020_9_4_20_31_05](https://user-images.githubusercontent.com/70782403/92291406-e59b2a80-eeee-11ea-9c61-6d4a47da6bb6.jpg)
![enb2020_9_4_20_32_19](https://user-images.githubusercontent.com/70782403/92291408-e764ee00-eeee-11ea-80c2-75f21df8e222.jpg)

**Additional context**
-

**Comment by Cajohl** [comment]
https://i.gyazo.com/577b5f529ba203368a64fc042bef0f1d.jpg

**Comment by KNGLogan** [comment]
![ScreenShot281](https://user-images.githubusercontent.com/66355096/92295918-e8991980-eef4-11ea-8eab-dbd3eb09295f.png)

**Comment by KNGLogan** [comment]
sorry for delete cant report already altered my playthrough

**Comment by TwistedModding** [comment]
sent the fixes to glory, also posted them in community additions for anyone else not wanting to wait for an update.

**Comment by b34nco** [comment]
Grey-Mane fixed, Whiterun Guard with the problem.

![enb2020_9_5_12_53_08](https://user-images.githubusercontent.com/70782403/92309145-52f39d80-ef79-11ea-8f33-7804251395b9.jpg)

**Comment by TwistedModding** [comment]
everything looks fine in xedit for this guy, not sure what's wrong.

**Comment by KNGLogan** [comment]
![SkyrimSE 2020-09-06 15-35-33](https://user-images.githubusercontent.com/66355096/92334798-c6b7a800-f056-11ea-9ab7-0aa430baf58f.png)

**Comment by KNGLogan** [comment]
![20200907232348_1](https://user-images.githubusercontent.com/66355096/92430566-d15b6580-f15a-11ea-86e0-31aad99ed14b.jpg)
thanks to bubba

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
