### ISSUE TITLE
NPCs with purple skin.

### ISSUE THREAD

**Issue by b34nco** [ForgottenGlory/Living-Skyrim-2#421]
**LS Version**
2.3.0

**Describe the bug**
Purple skin NPCs

**To Reproduce**
Bandits at Lost Knife Hideout

**Screenshots**
![SkyrimSE 2020-09-05 23-39-33](https://user-images.githubusercontent.com/70782403/92317121-94b13200-efd3-11ea-91cb-6f14167fb50f.png)
![SkyrimSE 2020-09-05 23-39-28](https://user-images.githubusercontent.com/70782403/92317122-95e25f00-efd3-11ea-8581-87db8587fdf7.png)

**Comment by TwistedModding** [comment]
this is not a bug. this is from the mod FEC you can change it in the mcm menu.
