### ISSUE TITLE
Invisible werewolves (The Companions questline)

### ISSUE THREAD

**Issue by b34nco** [ForgottenGlory/Living-Skyrim-2#422]
**LS Version**
2.3.0

**Describe the bug**
When The Companions turn into werewolves, they become invisible.

**Screenshots**
![enb2020_9_6_00_13_27](https://user-images.githubusercontent.com/70782403/92317497-86fdab80-efd7-11ea-95b5-8aabcd2030ca.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
