### ISSUE TITLE
Black Face Bug - Eorlund Gray-Mane

### ISSUE THREAD

**Issue by TheRavenGames** [ForgottenGlory/Living-Skyrim-2#423]
The only person who seems to have this issue as far as I have found is just Eorlund Gray-Mane with the black face bug, rest of body is fine.
![blackfacebug](https://user-images.githubusercontent.com/70855260/92330717-012a4080-f069-11ea-8b15-7c614a40c6dc.PNG)

**Comment by TwistedModding** [comment]
repeat of #420 you can close this.
