### ISSUE TITLE
Bearclaw Lodge - Floating Land / Consumed By Land / The Chest of Lag

### ISSUE THREAD

**Issue by TheRavenGames** [ForgottenGlory/Living-Skyrim-2#424]
**Bearclaw Lodge**

This place through my exploration to it and reloading / revisiting the area appears to have this location engulfed with the nearby terrain as it appears most of it is either consumed by another mod, also some parts of the buildings are floating and a specific chest next to the forge there outside if stared at  with drastically drop your FPS.
![bearclaw2](https://user-images.githubusercontent.com/70855260/92333814-53c32700-f080-11ea-9643-108dcf8f667e.PNG)
![bearclaw3](https://user-images.githubusercontent.com/70855260/92333815-56258100-f080-11ea-8fd1-8cbdbfb7a9fc.png)
![bearclaw](https://user-images.githubusercontent.com/70855260/92333816-5887db00-f080-11ea-938c-a5d18db31e48.PNG)

**Comment by TwistedModding** [comment]
take a screenshot of the objects in question selected in the console.

**Comment by ForgottenGlory** [comment]
Should be fixed 2.4.0
