### ISSUE TITLE
Statics and Intersecting Buildings in Ivarstead and Solitude

### ISSUE THREAD

**Issue by ObscuraArcana** [ForgottenGlory/Living-Skyrim-2#426]
Playing version 2.3.0

I'm not sure the steps to reproduce this bug. It was encountered after updating to the latest version. It seems to be minor issues with the world statics such as windows and buildings. For instance, on the side of the Winking Skeever facing Solitude's walls there are floating copies of the windows about a foot away from the actual windows. More seriously, in Ivarstead there is a large temple that isn't playing nice with one of the town overhaul mods. It's intersecting walkways, there are floating benches, and terrain objects clipping through the building. This isn't the most severe issue, but it is immersion breaking so I thought you should know about it.

**Comment by TwistedModding** [comment]
I know it may sound tedious, but your gonna have to select anything having problems in the console, take a screenshot of it and post it back on this.

**Comment by alexjoe9** [comment]
may be best to simplify and use just one very compatible towns and villages mod that has that hashed out. jk skyrim and arthormoor. I''m using this playlist to take notes on what I would want to include in my own build.

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
