### ISSUE TITLE
ELE not applying its lighting effects. (fix is in the report)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#428]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.0

**Describe the bug**
ELE not applying its lighting effects.

**To Reproduce**
load up a new game

**Expected behavior**
for the lights to apply properly.

I rearranged the ele_sse.esp and bfbr_ele_patch.esp to 329 on the plugin list (right before the bashed patch.) and the lights get applied properly now.

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
