### ISSUE TITLE
LS2 2.3.0 CTD when loading 2.2.1 save (w/ possible fix?)

### ISSUE THREAD

**Issue by SKGuru00** [ForgottenGlory/Living-Skyrim-2#429]
**LS Version**
2.3.0

**Describe the bug**
The upgrade from LS2 2.2.1 to 2.3.0 resulted in a CTD when loading my 2.2.1 save.  The crash log from \Living Skyrim\overwrite\NetScriptFramework\Crash\ hinted at LOTD being a potential issue.  Looking at the changelog of LS2 2.3.0, LOTD Patches was updated to 2.2, so I started there.

A couple pages into the comments section (https://forums.nexusmods.com/index.php?/topic/8230898-legacy-of-the-dragonborn-se-official-patches/page-175#entry84346448) I see someone else has a similar issue, and the mod author recommends updating LOTD Curators Companion.  Seeing as how Curators Companion 2.0.0 requires a new save, I decided to update to the previous version 1.1.3 (also making sure to follow the mod author's update instructions to clean RN_Utility_PrepStation from your save using Re-Saver).  Much to my surprise, I am now able to load my save without any crashing.

Note:  Ic0nIc0de recommends not using any of the new patches in the Curators Companion mod i.e. Skyrim Sewers & 3DNPC unless you plan on making a new save (which I did not intend to), so I deselected them during the fomod installer.

**To Reproduce**
Load any save from Living Skyrim 2.2.1.

**Expected behavior**
No CTD as a result of loading aforementioned save(s).

**Additional context**
Admittedly I've added mods to LS2, so I understand if this post is considered unsupported.  However if anyone else has this same issue, perhaps it's unrelated to my changes.

**Comment by TwistedModding** [comment]
The saves are incompatible, please close this post.
