### ISSUE TITLE
Harsh Orange Glows Around Roadside Lanterns (Night)

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-2#430]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.0

**Describe the bug**
Ongoing issue with strong orange-colored glows around roadside lanterns, which for me seems to be a bit worse on this build. 

**To Reproduce**
Traveling the road at night. Issue is intermittent, with some lamps exhibiting normal expected radiance and others the harsher glow. 

**Expected behavior**
N/A

**Screenshots**
![enb2020_9_8_05_34_35](https://user-images.githubusercontent.com/67465410/92468975-aba18100-f199-11ea-902e-349dde7fb740.jpg)

and a comparison...1st w/ my ENB and 2nd w/o ENB
![enb2020_9_8_05_33_34](https://user-images.githubusercontent.com/67465410/92469052-c4119b80-f199-11ea-8cd3-92753f898d2b.jpg)
![enb2020_9_8_05_33_55](https://user-images.githubusercontent.com/67465410/92469067-ca077c80-f199-11ea-822e-b286f0c88ffd.jpg)

**Additional context**
While this has been a reported issue, it seems be worse for me on 2.3.0, but another poster on Discord reported it was better for them on this build vs. 2.2.0.  Not sure what to make of that.

**Comment by KNGLogan** [comment]
known bug, nothing we can do about it until a patch is made

**Comment by seanpbelcher** [comment]
If you don't mind me asking, a patch for what mod(s) exactly? What is conflicting?

**Comment by KNGLogan** [comment]
dynlod and lanterns of skyrim I think

**Comment by seanpbelcher** [comment]
Gotcha. Thanks.

**Comment by seanpbelcher** [comment]
Looks like WhizKid's been working on a DynDOLOD patch for a while (last update on their progress was months ago); feel free to close this one out since there's nothing that can be done re: this.
