### ISSUE TITLE
Spiders Spawn in Four Shields Tavern

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-2#431]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.0

**Describe the bug**
Giant Frostbite Spiders have a random chance of spawning in the Four Shields Tavern in Dragon Bridge. Both myself and another player have experienced the event. 

**To Reproduce**
Seems to be random, but there's a chance upon entering the Inn or even after hanging about for a little while that the spiders will spawn and attack. And they don't even kill Skjarn, which just makes them useless. 

**Expected behavior**
To have a pint in a warm, safe place without threat from a Giant Spider Invasion. 

**Screenshots**
![20200909193205_1](https://user-images.githubusercontent.com/67465410/92634960-ad9f3900-f29a-11ea-94b2-98eee6c8f240.jpg)

**Additional context**
I ran into this same issue on the build prior to this one, but didn't report it because it might have been due to my mucking with the list. 

Discord user Johnnie.it took the above screen shot and added this one in case it might help narrow it down:
![20200909195305_1](https://user-images.githubusercontent.com/67465410/92635591-b5aba880-f29b-11ea-8c0b-c0a8923025fe.jpg)

**Comment by KNGLogan** [comment]
does not seem to happen anymore
