### ISSUE TITLE
camera zoom, widescreen??

### ISSUE THREAD

**Issue by moreschi2020** [ForgottenGlory/Living-Skyrim-2#432]
I checked the problems:

my monitor is cutting letters and parts of the screen, as if the camera has a focused zoom.

'' complete widescreen fix '' has not changed at all. not changing resolution either.

in the character creation menu there is the option to change the camera positions. it seems to me that it improves a little, but when closing the game and opening / loading the save the problem returns.

I didn't use loot or another program to load load order or clean plugins. I didn't try to update the mods to the latest version. I didn't install mods outside of living skyrim 2

my specifications: notebook, gtx1660ti max-q, 6gb vraw, i7 9750h, 16gb raw.

my maximum resolution is 1920x1080, 16: 9.

I attach some photos
![IMG_20200909_224144240](https://user-images.githubusercontent.com/71050778/92675485-e7515d80-f2f5-11ea-940d-d74890593f57.jpg)
![IMG_20200909_224208405](https://user-images.githubusercontent.com/71050778/92675489-e8828a80-f2f5-11ea-976d-033f104ea01d.jpg)
![IMG_20200909_224740193](https://user-images.githubusercontent.com/71050778/92675490-e8828a80-f2f5-11ea-9a32-a048efcd04ba.jpg)
![IMG_20200909_224802892](https://user-images.githubusercontent.com/71050778/92675491-e91b2100-f2f5-11ea-8f69-9481e89f1092.jpg)
![IMG_20200909_225003867](https://user-images.githubusercontent.com/71050778/92675492-ea4c4e00-f2f5-11ea-9add-b15cd7cb1385.jpg)
![IMG_20200909_225014258](https://user-images.githubusercontent.com/71050778/92675493-eae4e480-f2f5-11ea-958c-36483f25c5e2.jpg)
![IMG_20200909_230658121](https://user-images.githubusercontent.com/71050778/92675494-eae4e480-f2f5-11ea-82bc-92b573536213.jpg)
![IMG_20200909_230824315](https://user-images.githubusercontent.com/71050778/92675498-eb7d7b00-f2f5-11ea-91be-7377eb913db7.jpg)
![IMG_20200909_230834578](https://user-images.githubusercontent.com/71050778/92675499-eb7d7b00-f2f5-11ea-89c1-84021aa887fc.jpg)

**Comment by KNGLogan** [comment]
whats your curreent zoom in settings
and you dont need the fix

**Comment by KNGLogan** [comment]
ask in discord before posting issue
