### ISSUE TITLE
CTD caused by Helarchen creek

### ISSUE THREAD

**Issue by jaroslavburi** [ForgottenGlory/Living-Skyrim-2#434]
Reproduce:
Leave Dawnstar and head to Helarchen, on the way the game crashes.

In the SSEEdit I have found out that there is conflict between Helarchen Creek and Majestic Mountains.

[Crash_2020_9_13_22-57-24.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5215124/Crash_2020_9_13_22-57-24.txt)

[Save18_BEB31A12_0_5370656C6C53776F7264_Tamriel_000113_20200913111027_3_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5215126/Save18_BEB31A12_0_5370656C6C53776F7264_Tamriel_000113_20200913111027_3_1.zip)

**Comment by ForgottenGlory** [comment]
Should be fixed 2.4.0
