### ISSUE TITLE
Dragonbone Hatchet appears very early

### ISSUE THREAD

**Issue by zimeron** [ForgottenGlory/Living-Skyrim-2#435]
LS Version: 2.3.0

Description: The Dragonbone Hatchet seems to appear very early in the vendor and enemy levelled lists, I have seen it in two sub-level 10 playthroughs now.

Reproduction: Play the game, check enemies (bandits) and vendors.

Expect: Find Dragonbone Hatchet (1H axe) on low level enemies despite low player level.

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
