### ISSUE TITLE
CTD's around Rorikstead

### ISSUE THREAD

**Issue by cloumb** [ForgottenGlory/Living-Skyrim-2#436]
[Crash_2020_9_16_7-59-16.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5233002/Crash_2020_9_16_7-59-16.txt)

[Save23_C3852134_0_507269736F6E65724572616C64_Tamriel_000143_20200916145744_4_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5233089/Save23_C3852134_0_507269736F6E65724572616C64_Tamriel_000143_20200916145744_4_1.zip)

**LS Version**
2.3.0
**Describe the bug**
The game runs smoothly but crashes every few minutes. It seems to be when my character starts moving somewhere.

**To Reproduce**
Steps to reproduce the behavior: Walk around for a bit

**Expected behavior**
Game CTDs

**Screenshots**
I'm not sure if the bug has anything to do with how I downloaded these mods. I downloaded them separate of the Living Skyrim Wabbajack installer per instructions in Rudy's ENB
![Mod extras](https://user-images.githubusercontent.com/71395107/93358082-ec327780-f7f5-11ea-9bf0-955845ea084a.PNG)

**Additional context**
My computer exceeds the specs, so I don't think that's the issue. I can supply more crash logs or saves if that provides clarity.

**Comment by TwistedModding** [comment]
Dont post bug reports with mods added. 

You void all support when adding or changing anything.

**Comment by cloumb** [comment]
Gotcha, thank you. I'll try running an install with no ENB mods
