### ISSUE TITLE
LS needs a solid Healer

### ISSUE THREAD

**Issue by Dscot401** [ForgottenGlory/Living-Skyrim-2#438]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**To submit a mod for consideration, you must attach a copy of your save game where you have defeated Alduin using an unmodified LS installation. Any suggestions without this attached will be automatically rejected. This is not a guarantee that the mod will be included.**

**Mod Name**
Toccata Follower SE (With Elisif Replacer Option)

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/12713

**Why?**
There are few healers in LS2.  Granted, with NFF you can "make one", but they don't seem to perform well (at least, mine didn't),  Toccata is built to heal and the mod is solid.  I used her through almost every playthrough before this one. Do not include the replacer option.  She looks awesome, but it's kinda creepy when you have Toccata with you (twins) 

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5246219/saves.zip)

**Comment by ForgottenGlory** [comment]
Added 2.4.0
