### ISSUE TITLE
Viola Giadorno doesn't exist

### ISSUE THREAD

**Issue by shaye1444** [ForgottenGlory/Living-Skyrim-2#441]
If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.0

**Describe the bug**
For the Quest Blood on Ice, Viola Giadorno doesn't exist. Her posters never showed up and the first butcher book doesn't exist in the chest in the house either. I cannot teleport her to me and when I teleport to her it just puts me in her house.

**Expected behavior**
She should've have started the conversation with the sailor and I shoudl have overheard it. Morevoer, the butcher book 1 needs to exist and I have to talk with her to progress the quest but she doesn't exist. 

**Additional context**
I'm around level 22 and just started th eempire quest. Also, when i prid her name it says her base reference was replaced by a homes mod.

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0

**Comment by shaye1444** [comment]
I don't see this update and if I do update is this a "new save" update?

**Comment by TwistedModding** [comment]
update isnt out yet and yes it will require a new save.
