### ISSUE TITLE
Onmund Black Face Bug

### ISSUE THREAD

**Issue by darkpeep** [ForgottenGlory/Living-Skyrim-2#443]
**LS Version**
Put the version of the list you are on here.
2.4.0
**Describe the bug**
Onmund has a black face bug at college of winterhold

**To Reproduce**
Join college of winterhold and look for Onmund

**Expected behavior**
The normal face for Onmund to be there

**Screenshots**
Two screenshots, one without him clicked in console, and one with him clicked in console.
![Onmund](https://user-images.githubusercontent.com/68132832/93769526-e61f0b00-fbe8-11ea-9e7c-d472b4c4fb0e.png)
![Onmund Console](https://user-images.githubusercontent.com/68132832/93769543-ec14ec00-fbe8-11ea-8db4-fed6fa8e1db2.png)

**Additional context**
That's about it.

**Comment by TwistedModding** [comment]
ill fix this and post the esp in community additions and send it to glory.

**Comment by darkpeep** [comment]
> ill fix this and post the esp in community additions and send it to glory.

Alrighty, thank you c:

**Comment by ForgottenGlory** [comment]
Should be fixed 2.4.1
