### ISSUE TITLE
Cooking pot outside Riverwood

### ISSUE THREAD

**Issue by TheMapzor** [ForgottenGlory/Living-Skyrim-2#444]
**LS Version**
2.4.0

**Describe the bug**
A floating cooking pot can be found outside the Riverwood entrance coming from Helgen, where a camp used to be in 2.3.0

**To Reproduce**
New save in 2.4.0

**Expected behavior**
For that cooking pot not to be there i guess.

**Screenshots**
![enb2020_9_21_23_54_06](https://user-images.githubusercontent.com/71673308/93833585-4cec0500-fc79-11ea-9477-de9b643f0545.jpg)

**Comment by ForgottenGlory** [comment]
Should be fixed 2.4.1
