### ISSUE TITLE
Window shadows

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#445]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**To submit a mod for consideration, you must attach a copy of your save game where you have defeated Alduin using an unmodified LS installation. Any suggestions without this attached will be automatically rejected. This is not a guarantee that the mod will be included.**

**Mod Name**
Window Shadows by HHaleyy

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/37831

**Why?**
makes you feel a bit more immersed 

**Additional context**
using it now works fine, only conflicts with reduced glow fx
[Logan's alduin save.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5264902/Logan.s.alduin.save.zip)

**Comment by seanpbelcher** [comment]
Just FYI, I had some issues using this, but I have tweaked the modlist quite a bit so someone with a pristine LS2 install should test this one (specifically fire pit lighting in the Bannered Mare was goofed and Castle Dour in Solitude was a real mess with misplaced lights and light assets, randomly placed interior walls, etc). I used the very latest Windows Shadows (version 6.0 I believe?)

**Comment by ForgottenGlory** [comment]
Added 2.4.1
