### ISSUE TITLE
Floating textures outside of Whiterun

### ISSUE THREAD

**Issue by PlUmPaSsChIcKeN** [ForgottenGlory/Living-Skyrim-2#447]
In the Whiterun plains above the giant's camp there are some floating rock textures along with a door that is interactable but does nothing when opened. Not able to select the textures at all but was able to select the door, as you should see in the screenshots.

![enb2020_9_24_14_58_47](https://user-images.githubusercontent.com/71852185/94202721-cce5bb00-fe83-11ea-911f-870098222bde.png)
![enb2020_9_24_15_00_05](https://user-images.githubusercontent.com/71852185/94202727-cf481500-fe83-11ea-860a-3c2f55b36288.png)
![enb2020_9_24_15_00_37](https://user-images.githubusercontent.com/71852185/94202730-d1aa6f00-fe83-11ea-9fac-59b702fd29ef.png)
![enb2020_9_24_16_10_37](https://user-images.githubusercontent.com/71852185/94202732-d2db9c00-fe83-11ea-9048-f658c659bf9a.png)
![enb2020_9_24_16_10_55](https://user-images.githubusercontent.com/71852185/94202737-d4a55f80-fe83-11ea-8d8f-4844baf79d88.png)
![enb2020_9_24_16_10_59](https://user-images.githubusercontent.com/71852185/94202741-d66f2300-fe83-11ea-8479-7234fa1f5499.png)
![enb2020_9_24_16_11_30](https://user-images.githubusercontent.com/71852185/94202743-d7a05000-fe83-11ea-84f6-55ce2a4a1dfd.png)

**Comment by TwistedModding** [comment]
select the items in the console and post the screenshot. if you cant select them, post your cords (you can find it in your dyndolod mcm

**Comment by PlUmPaSsChIcKeN** [comment]
As stated the textures are not selectable. The door is selected and shown above in screenshot that is second from the bottom. Here are the coordinates.
![enb2020_9_24_16_44_17](https://user-images.githubusercontent.com/71852185/94203793-ad4f9200-fe85-11ea-9664-5cba21f8a566.png)

**Comment by seanpbelcher** [comment]
I have the ref ID for the floating rocks...
![enb2020_9_25_04_19_20](https://user-images.githubusercontent.com/67465410/94250330-b290f900-fee6-11ea-9b17-ac7a1d4a190a.jpg)

It took a little bit of trial and error. Had to turn clipping back on and walk around on top of the darn thing for a few mintus before finding a sweet spot that I could select. Pretty confident this is the right Ref though.

**Comment by PlUmPaSsChIcKeN** [comment]
Good to know we found the issue. Should I close this now?

**Comment by KNGLogan** [comment]
no glory needs it when he fixes

**Comment by ForgottenGlory** [comment]
Should be fixed 2.4.1
