### ISSUE TITLE
can't save 

### ISSUE THREAD

**Issue by CGDannim** [ForgottenGlory/Living-Skyrim-2#450]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save842_1DBF690B_0_416E75626973_LabyrinthianWorld04_082214_20200924194635_37_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5286696/Save842_1DBF690B_0_416E75626973_LabyrinthianWorld04_082214_20200924194635_37_1.zip)

[Crash_2020_9_20_4-23-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5286693/Crash_2020_9_20_4-23-14.txt)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.0

**Describe the bug**
I can no longer save.
[tmpsaves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5286699/tmpsaves.zip)

0 byte .tmp files are generated, but nothing else and Skyrim itself CTDs instantly on trying to save.  No issue loading from any saves, but cannot then save from any.

I can Fast travel and move in and out of any cities/dungeons without issues.

**To Reproduce**
Any save will CTD.  

**Expected behavior**
I expected to be able to save as I have 841 times before.  ;)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
![image](https://user-images.githubusercontent.com/71931198/94341636-f82dee80-ffd8-11ea-89cd-f4c2ca374550.png)

I've noticed that my skse files are 0k up until entering Labyrinthian when they then jump to 2.4MB.  My issue occurred after that.  As mentioned above though reverting to an earlier save with a matching 0kb skse still results in a CTD when saving.

**Comment by CGDannim** [comment]
Was being too lazy I guess; looked at the log and tracked the issue to a Vitality mod item.  Since I wasn't using that mod at all I disabled and have since been able to save.

The skse co-save files are still an 'issue' though.  Sticking at ~2.4MB so far.

Any advice/recommendations?

**Comment by ForgottenGlory** [comment]
Fixed 2.4.1

**Comment by CGDannim** [comment]
Hi,

I understand that the bug is fixed with Vitality, but is there any recommendation for the co-save size (now 3MB)?  It causes a significant delay (couple seconds/per) and likely won't get better without intervention.  And I'd rather not try save cleaners and the like as they're not recommended and void support - unless told otherwise.
