### ISSUE TITLE
Activating the Shadow Stone grants the Serpent Stone power

### ISSUE THREAD

**Issue by nperanzi** [ForgottenGlory/Living-Skyrim-2#456]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
9/4/2020 2.3.0

**Describe the bug**
Activating the Shadow Stone (Fortify Sneak) grants the Serpent Stone power (Fortify Melee) instead.

**To Reproduce**
Steps to reproduce the behavior: Activate the Shadow Stone.

**Expected behavior**
Shadow stone power granted.

**Screenshots**
![enb2020_9_29_19_02_46](https://user-images.githubusercontent.com/7450800/94625294-69de9480-0286-11eb-9656-f7f0400ff659.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 2.4.1
