### ISSUE TITLE
Can't Save...

### ISSUE THREAD

**Issue by shaye1444** [ForgottenGlory/Living-Skyrim-2#457]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_10_1_0-7-43.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5309602/Crash_2020_10_1_0-7-43.txt)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3

**Describe the bug**
I can't save.

**To Reproduce**
Try to save.

**Expected behavior**
The game to actually save.

**Additional context**
Everything else works normally. I just can't save it CTD's immediately after hitting the save button.

**Comment by CGDannim** [comment]
The Vitality mod is causing it.  If you're not using it you can disable (ModOrganizer) and then be able to save.

**Comment by shaye1444** [comment]
Okay thanks that worked!

**Comment by ForgottenGlory** [comment]
Fixed 2.4.1
