### ISSUE TITLE
Looted bodies turn Purple

### ISSUE THREAD

**Issue by billyb77** [ForgottenGlory/Living-Skyrim-2#458]
The bodies of enemies turn to a shade of purple and their skin has cracks in it like an old porcelain doll.  This happens a little while after killing them ,but sometimes immediately after looting. 

 version is living skyrim 2 with rudy enb for obsidian 
i included a pic without nudity
![157](https://user-images.githubusercontent.com/72187773/94780946-cb8a2600-038e-11eb-8ed7-f6c5d9c53c61.jpg)

Thanks

**Comment by LunarDelta** [comment]
I can also confirm this happens. At first I thought they were sick or poisoned, but it kept happening over and over.

**Comment by seanpbelcher** [comment]
This is FEC. In the MCM menu, turn off decomposition. Should fix it.
