### ISSUE TITLE
Missing textures in Bleak Falls Barrow

### ISSUE THREAD

**Issue by MrCamo** [ForgottenGlory/Living-Skyrim-2#462]
**LS Version**
2.4.0.

**Describe the bug**
Some textures in Bleak Falls Barrow are not being shown depending on your position.

**To Reproduce**
This starts when you go down the first steps after the two bandits and then turn around the right corner. When you move towards the wall which is not being shown correctly, eventually it will just pop in, but now if you turn around the textures somewhere else are missing.

**Expected behavior**
I expected the textures to load and be shown correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/72318060/95002139-1f844d00-05d1-11eb-8cbf-12086c019529.png)
This screenshot shows the space after you turn right the first time. Since I was testing, ENB was turned off and MCM was not configured.

**Additional context**
This problem did not occur back in LS 2.3.0.
After a clean install with 2.4.0. however this started to happen, which prompted me to delete everything and reinstall it all over again. This is still happening. In other locations with similar textures like ysgramors tomb I could not reproduce this bug.

**Comment by TwistedModding** [comment]
Pretty easy fix: Move BleakFallsBarrowRevisited.esp to priority 340 in the right pane of MO2.

**Comment by MrCamo** [comment]
Thank you. That worked.
It's been a long time since I felt that dumb.
