### ISSUE TITLE
Critical Game Breaking Story Bug: Dragon Rising mission not starting.

### ISSUE THREAD

**Issue by primethief147** [ForgottenGlory/Living-Skyrim-2#463]
Living Skyrim 2.4.0

**Describe the bug**
After finishing the second main story quest (Before the Storm) the Whiterun Jarl sends you to talk to his court Mage Farengar Secret-Fire  who then gives you the quest Bleak Falls Barrow where you are supposed to retrieve a dragon stone for him. After getting the stone you return to him and he will thank you for retrieving it and then the dialogue ends with the notification that you can now buy a house in Whiterun. Also Irileth (the Jarls bodyguard) who is supposed to help start the next quest disappears from dragonsreach and cannot be found.

**To Reproduce**
It shouldn't be hard to reproduce i did this mission on 4 different characters: One who was given the mission to retrieve the stone and then returned it after getting it, another had the stone before being given the mission and was able to give it right there, then i made a third character who i specifically didn't do any other missions besides the main missions, and then finally a forth character just using the base game without living skyrim doing only the main missions. That forth character actually was able to activate Irileth which then started the quest Dragon Rising an i was able to finish the quest with no problems. For added context all the characters were Redguards one which started with the thieves guild, another started with the Empire, and then the last one (while using Living Skyrim) was a barhand at Riverwood Inn. I also have Skyrim Together also installed in mod organizer.

**Expected behavior**
Now normally what's supposed to happen after giving Farengar the dragons stone is the dailgue automatically pops back up and your allowed to ask him about your reward in which he says to find the Jarl. Irileth then appears talking about how a dragon has been spotted which activates the quest Dragon Rising. Then you and Irileth both go up to the Jarl he tells you to go deal with the Dragon in which you can ether follow Irileth to the location the dragon was spotted or you can fast travel there. If you follow Irileth she will travel down to Whiteruns main gate where she meets 4 unique looking Whiterun guards. She gives a short speech and then together you go to the location, fight/kill the dragon, absorb its soul one of the unique guards starts talking to you claiming your a dragonborn. You test out "shouting" and then are told to go back the Jarl then the quest completes. 

**Screenshots**

**Additional context**
I've done a few hours of research on this bug and from what i can gather it was a bug that used to happen in the base game (shouldn't be to hard to find just search Irileth not showing up) with a variety of solutions offered with all failing for me except one which... solved a little bit of the problem: Basically you start by using the console to despawn Irileith, manually finish Bleak Rocks Barrow, starting dragon rising, and then respawning Irilelth. That actually causes the questline to work as intended you go to the the Jarl who tells you to kill the Dragon and then your given the quest markers to ether follow Irileth or fast travel to the location to meet her there. Here's the main problem: the 4 guards that Irileth is supposed to meet at the gate don't spawn, the area you're supposed to go to isn't destroyed by the dragon, and when Irileth arrives at the area nothing happens and if you try to talk to Irileth she says to meet her at the location where the dragon was spotted (aka where she currently is). 

Hope this is helpful unfortunately wasn't able to find any other people to test if this bug repeated in their game and to see if this happened with their main quests or if this was just an issue with only my living skyrim game.

**Comment by TwistedModding** [comment]
read the readme and close this post.

**Comment by TwistedModding** [comment]
actually im feeling nice so ill just tell you because of how much testing you did before making this report.
https://www.nexusmods.com/skyrimspecialedition/mods/2475

Wait 1 week (7 days) and the storyline will progress.
