### ISSUE TITLE
Update Hedge Mage Armor to No Camp version

### ISSUE THREAD

**Issue by JaxomofRuatha** [ForgottenGlory/Living-Skyrim-2#464]
This was mentioned as an option previously to avoid some of the CTD and other issues around the Worldspace edits.

**Link:** https://www.nexusmods.com/skyrimspecialedition/mods/5269 (Hedge Mage Armor - No Camp)

Hedge Mage Armor - No Camp.esp should be opened in Creation Kit and re-saved as a Form 44 plugin (just open it as the active mod, then save)

**Comment by ForgottenGlory** [comment]
Done 2.4.1
