### ISSUE TITLE
rugs keep spawning when riding horses and leaving buildings

### ISSUE THREAD

**Issue by SpookyAzizi** [ForgottenGlory/Living-Skyrim-2#465]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by SpookyAzizi** [comment]
![unknown](https://user-images.githubusercontent.com/72271571/95174118-3a94bf80-077f-11eb-86be-2a1e783fd479.png)

**Comment by ForgottenGlory** [comment]
By chance, do any of your followers have a bandolier equipped?

**Comment by ForgottenGlory** [comment]
Also putting this here so I don't forget it and can ask TJBassoon about it later https://www.reddit.com/r/skyrimmods/comments/4qfybs/a_random_carpet_spawns_when_i_trade_items_with/

**Comment by SpookyAzizi** [comment]
No none of my followers has a backpack equipped however I used to have a backpack, but I eventually sold it for money. I do have a camping thing in my inventory. Maybe removing that would help? Testing that out since I know that camping thing attaches to backpacks , n I’ll check the link out

**Comment by SpookyAzizi** [comment]
Been trying everything I’ve looked up and seen nothing has changed or worked

**Comment by SpookyAzizi** [comment]
However I see that this happens around city mainly and riding horses, but far from city’s it doesn’t spawn as much till every 5 min or so

**Comment by TwistedModding** [comment]
"Yeah the carpet spawning bug! Just saw that. Definitely related to campfire.
One of the player created items from Campfire is causing it. Advice is to unequip everything and stash it in a chest or something. Equip the items created by Campfire one at a time and find out which one causes the spawn. Drop that item and delete it from the game.
At least, that's what I suspect, based on my past experience. That was before SSE was even a thing."

From tjbassoon in the discord
link to convo: https://discordapp.com/channels/690583538210308106/690616522032545812/763246128534650930

**Comment by SpookyAzizi** [comment]
I tried removing all items that could’ve been related to campfire from both my inventory and followers, even went as far as disabling campfire, or trying a new save without campfire, still encountering this bug, maybe I’m not doing something right :(
