### ISSUE TITLE
LS SSELODGen Output 2.1.0.zip and LS2 DynDOLOD Output 2.4.0.zip dont exist online anymore

### ISSUE THREAD

**Issue by LogeeBare** [ForgottenGlory/Living-Skyrim-2#475]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Trying to install LS 2.5.0

**Describe the bug**
LS SSELODGen Output 2.1.0.zip and LS2 DynDOLOD Output 2.4.0.zip fail to download through Wabbajack.
When trying to download them manually, I get a 404 error on Mega. 

**To Reproduce**
https://wabbajack.b-cdn.net/LS2%20SSELODGen%20Output%202.1.0.zip_38791b5f-ec8c-4198-9ebe-9589b1125616 gets a 404 error. 

https://wabbajack.b-cdn.net/LS2%20DynDOLOD%20Output%202.4.0.zip_6d2943a8-b862-4cb2-96e1-1fc027e13c4d also gets a 404 error. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Close this. They arent meant to be downloaded manually. Have to get them from a mirror if someone mirrored it already.

**Comment by LogeeBare** [comment]
LS SSELODGen Output 2.1.0.zip and LS2 DynDOLOD Output 2.4.0.zip **fail to download through Wabbajack.**

**Comment by ForgottenGlory** [comment]
Get them from one of the mirrors. They can't be downloaded using the links you posted. The mirrors are pinned in multiple places on Discord.

**Comment by LogeeBare** [comment]
Apologies, Thank you for the amazing modlist. Donating
