### ISSUE TITLE
Zephyr Redone & Male NPC OverhauL compatibility patches

### ISSUE THREAD

**Issue by efonte** [ForgottenGlory/Living-Skyrim-2#481]
Mods:
https://www.nexusmods.com/skyrimspecialedition/mods/25450?tab=files
https://www.nexusmods.com/skyrimspecialedition/mods/13816?tab=files

Required versions:
![image](https://user-images.githubusercontent.com/3957463/96804898-94001e00-1410-11eb-9ecb-3525ce3593a7.png)

New versions:
compatibility patches-25450-4-02-1602791125
Zephyr Redone-13816-1-8-1602785598

**Comment by efonte** [comment]
@ForgottenGlory I'm sorry if I did something wrong but there is a bug that does not allow installing the pack since the required versions are not available in nexus

**Comment by ForgottenGlory** [comment]
No, you need to download the latest version using the Wabbajack Browse Modlists page. You're trying to install an old version.

**Comment by efonte** [comment]
![image](https://user-images.githubusercontent.com/3957463/96805348-ba728900-1411-11eb-8adb-0c1802d187b3.png)
okay, I'll wait for it to be available to download. Thank you very much
