### ISSUE TITLE
First time instaling, failing at Bijin AIO2020 and mesh overhaul download

### ISSUE THREAD

**Issue by agentmith** [ForgottenGlory/Living-Skyrim-2#482]
Hi, just started setting this up for the first time and it fails at this mod:

https://www.nexusmods.com/skyrimspecialedition/mods/11/

Looks like the author has hidden it. Are there plans to replace this? Sorry I don't see any debug logs that capture more helpful text
![CropperCapture 5](https://user-images.githubusercontent.com/9688832/96939615-65229000-1482-11eb-90da-6a669fc0dff2.jpg)

**Comment by TwistedModding** [comment]
It'll get fixed when it gets fixed. Please dont use the github to post that the list is down. Glory knows when its down.
