### ISSUE TITLE
Desktop crash at White Run

### ISSUE THREAD

**Issue by Epicreactor** [ForgottenGlory/Living-Skyrim-2#493]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_11_4_12-14-35.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5489518/Crash_2020_11_4_12-14-35.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.5.2
**Describe the bug**
Went to white run, walked into the market game then crashed to desktop 
**To Reproduce**
Go to White Run market, wait awhile,
**Expected behavior**
Expected game not to crash to desktop
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
You have a lot of mods either disabled or removed or added. Please remove this post. Thanks
