### ISSUE TITLE
White Run desktop crash

### ISSUE THREAD

**Issue by Epicreactor** [ForgottenGlory/Living-Skyrim-2#494]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_11_4_12-14-35.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5489579/Crash_2020_11_4_12-14-35.txt)
[Crash_2020_11_4_12-38-33.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5489580/Crash_2020_11_4_12-38-33.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
2.5.2
**Describe the bug**
When going to white run at night, everyone walks out of the local inn, then crashes
**To Reproduce**
go the white run at night when everyone walks out of the local inn, near the market
**Expected behavior**
The game not to crash when near the market in white run at night 
**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
What are you doing. Take these two reports down for the reason i said on the other, if not you'll be denied access from reporting on the github.

**Comment by Epicreactor** [comment]
I'm unsure how to remove the reports truth be told
