### ISSUE TITLE
[Alpha 6] Floating Lanterns in Riverwood

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#53]
![ScreenShot197](https://user-images.githubusercontent.com/49283855/82695542-8ad11200-9c22-11ea-85d5-30036030b575.png)
![ScreenShot194](https://user-images.githubusercontent.com/49283855/82695558-9290b680-9c22-11ea-8714-fb2adcbe2bec.png)
![ScreenShot195](https://user-images.githubusercontent.com/49283855/82695577-9a505b00-9c22-11ea-837b-73abb169ad87.png)
![ScreenShot196](https://user-images.githubusercontent.com/49283855/82695603-a20fff80-9c22-11ea-82cd-93c027ab7634.png)

**Comment by ForgottenGlory** [comment]
This should be fixed, feel free to reopen if it's not
