### ISSUE TITLE
[Alpha 6] Lighting Glitches in Lakeview Manor

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#54]
![ScreenShot191](https://user-images.githubusercontent.com/49283855/82697446-329c0f00-9c26-11ea-8785-4667a76da6d6.png)
![ScreenShot192](https://user-images.githubusercontent.com/49283855/82697452-34fe6900-9c26-11ea-9da0-14e6d863b4dc.png)

**Comment by ForgottenGlory** [comment]
This looks like the "too many light sources" engine limit.
