### ISSUE TITLE
[Alpha 6] Upon leaving Lakeview Manor, a dead conjurer falls out of the sky

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#56]
![ScreenShot201](https://user-images.githubusercontent.com/49283855/82697855-f5844c80-9c26-11ea-8cd7-57aee0bbea23.png)
This happened 2/2 times, but the first time it was a male Altmer and had different stuff, the second time it was a female Breton.

**Comment by JaceVenture** [comment]
![ScreenShot245](https://user-images.githubusercontent.com/49283855/84063819-e1f31880-a97e-11ea-846a-5b5d83b788a0.png)
Still something that happens as of Beta 3.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
