### ISSUE TITLE
[Alpha 5] These two are stuck in this area in Riverwood after completing Vilja's starting quest

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#57]
![ScreenShot225](https://user-images.githubusercontent.com/49283855/82698048-53b12f80-9c27-11ea-89e4-15d1ea924176.png)
![ScreenShot226](https://user-images.githubusercontent.com/49283855/82698053-56138980-9c27-11ea-914b-b772da7ba64f.png)
After getting Vilja's magic bottle from the thieves, they are stuck in Riverwood outside Lucan's shop. I waited many, many ingame hours and they never left a 3ft by 3ft square, even at 3AM.
I encountered this in Alpha 5, and haven't tried again in Alpha 6 yet.

**Comment by ForgottenGlory** [comment]
Is this still an issue?
