### ISSUE TITLE
A myriad of problems with Settlements Merged at Castle Dawnguard

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#58]
![ScreenShot281](https://user-images.githubusercontent.com/49283855/82698345-d76b1c00-9c27-11ea-9aea-050a4b9c5517.png)
![ScreenShot282](https://user-images.githubusercontent.com/49283855/82698349-d9cd7600-9c27-11ea-828c-f0f566324438.png)
![ScreenShot283](https://user-images.githubusercontent.com/49283855/82698355-db973980-9c27-11ea-9bf6-c3a1a4fb3e59.png)
![ScreenShot284](https://user-images.githubusercontent.com/49283855/82698365-df2ac080-9c27-11ea-9760-4924b70a65f3.png)
![ScreenShot287](https://user-images.githubusercontent.com/49283855/82698370-e0f48400-9c27-11ea-9238-2dc7350954e0.png)
![ScreenShot292](https://user-images.githubusercontent.com/49283855/82698377-e2be4780-9c27-11ea-99a6-d2ed82145ee4.png)
![ScreenShot289](https://user-images.githubusercontent.com/49283855/82698414-f1a4fa00-9c27-11ea-92c6-cee215b41bf3.png)
![ScreenShot290](https://user-images.githubusercontent.com/49283855/82698432-fd90bc00-9c27-11ea-9877-53518cfcd2e4.png)

Yup, lots of fun :)

**Comment by ForgottenGlory** [comment]
Possibly fixed Beta 4, followup on this
