### ISSUE TITLE
Armors Rendering in Vanilla Texture/mesh

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#60]
Savior's Hide
Ebony Mail
Skaal Coat
Archmages Robes
Entire Psijic and Mythic Dawn Sets
Temple Priest Robes
Falmer
Stormcloak
Stormcloak Officer
High Hrothgar Robes
Sheogorath's outfit
Example Pics:
![ScreenShot213](https://user-images.githubusercontent.com/49283855/82834663-03340f00-9e7f-11ea-8c33-9b9e7568b0da.png)
![ScreenShot207](https://user-images.githubusercontent.com/49283855/82834681-0cbd7700-9e7f-11ea-9fa8-a5edfaac255c.png)
For some of them, the rest of the armor renders nicely. But for these ones, they did not render with any upgraded textures. And it wasn't my video card taking its sweet time, I don't believe, because when I would switch to another armor it was immediately 4k or 2k or whatever.

**Comment by ForgottenGlory** [comment]
Fixed some of these Beta 4, some of these armors just don't have any retextures though.
