### ISSUE TITLE
Many Helmets do not render

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#62]
![ScreenShot203](https://user-images.githubusercontent.com/49283855/82834840-89505580-9e7f-11ea-8b56-4743f4f8f491.png)
![ScreenShot204](https://user-images.githubusercontent.com/49283855/82834847-8d7c7300-9e7f-11ea-95b8-c96597aee0d1.png)
![ScreenShot205](https://user-images.githubusercontent.com/49283855/82834856-92412700-9e7f-11ea-94cc-aede3c3d2075.png)
![ScreenShot208](https://user-images.githubusercontent.com/49283855/82834877-9c632580-9e7f-11ea-8eec-ad820e374304.png)
![ScreenShot209](https://user-images.githubusercontent.com/49283855/82834884-a08f4300-9e7f-11ea-9d25-5ae4424cb5b1.png)
Daedric, Dwarven, Ebony with my testing. The Dragonpriest mask Otar does not render as it looks like it will in the preview window.

**Comment by ForgottenGlory** [comment]
Need some FormIDs please :)

**Comment by tjbassoon** [comment]
Confirming. Does not effect Argonian or Khajiit races, does affect both male and female genders.
Tested by adding items from qasmoke to inventory and equipping.
Four helmets are affected. Form IDS:
0000396D, 0001394F, 00013963, 0001395E
I did not encounter the problem with the Otar mask as described.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
