### ISSUE TITLE
[Alpha 8] Hunting in Skyrim Major Clipping Problems

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#63]
Both at Bearclaw Lodge and Amberleaf Den.
![ScreenShot229](https://user-images.githubusercontent.com/49283855/83175189-c4999100-a0d8-11ea-84e3-8ccf99ce2281.png)
![ScreenShot230](https://user-images.githubusercontent.com/49283855/83175196-c6fbeb00-a0d8-11ea-8045-782022b9933e.png)
![ScreenShot231](https://user-images.githubusercontent.com/49283855/83175204-c8c5ae80-a0d8-11ea-9816-589d7bc513d1.png)
![ScreenShot232](https://user-images.githubusercontent.com/49283855/83175212-cb280880-a0d8-11ea-90cd-53056755152e.png)
![ScreenShot233](https://user-images.githubusercontent.com/49283855/83175215-cc593580-a0d8-11ea-9226-94d0359dff09.png)
![ScreenShot234](https://user-images.githubusercontent.com/49283855/83175219-cebb8f80-a0d8-11ea-9ba5-b4b4934b86d3.png)
![ScreenShot235](https://user-images.githubusercontent.com/49283855/83175224-d11de980-a0d8-11ea-8aef-c4e49950d1ec.png)
![ScreenShot236](https://user-images.githubusercontent.com/49283855/83175230-d2e7ad00-a0d8-11ea-8945-7af5d63b6244.png)
![ScreenShot237](https://user-images.githubusercontent.com/49283855/83175239-d54a0700-a0d8-11ea-99bc-008d98d5f1a4.png)
![ScreenShot238](https://user-images.githubusercontent.com/49283855/83175248-d7ac6100-a0d8-11ea-85ba-5f4da44f07b9.png)

**Comment by ForgottenGlory** [comment]
Should be mostly fixed Beta 3
