### ISSUE TITLE
[Alpha 8] Some people are running around naked

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#64]
Due to removing the BattleMage Cuirass? But I have seen a male or two chilling naked.
![ScreenShot206](https://user-images.githubusercontent.com/49283855/83175460-2823be80-a0d9-11ea-9d64-1eb6a7f564b9.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 1. For some reason one of the items in the leveled list for her clothes was a COBJ, which obviously can't be equipped. Keep an eye out for these and report them please so I can find other similar instances.

**Comment by ForgottenGlory** [comment]
Double-checked the Leveled Lists, this should be 100% resolved for Beta 1
