### ISSUE TITLE
alpha 9 - need to yeet tree patch

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#66]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
a9

**Describe the bug**
missing mod error in MO

**To Reproduce**
launch MO

**Expected behavior**
no missing mod error

![image](https://user-images.githubusercontent.com/11461193/83315472-6b675580-a1dd-11ea-93f3-8fa363c072ae.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 1
