### ISSUE TITLE
Alpha 9 - Ralof still has BFB

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#67]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
A9

**Describe the bug**
Ralof - BFB

**To Reproduce**
meet ralof below helgen

**Expected behavior**
not black

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
![image](https://user-images.githubusercontent.com/11461193/83317063-52fc3880-a1e7-11ea-9613-7dc871d7c156.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 1
