### ISSUE TITLE
Alpha 9 - Navmesh issue near Riverwood - Ralof gets stuck

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim-2#68]
If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
a9

**Describe the bug**
After getting Ralof the healing potion, he gets stuck here on his way to talk to Gerdur.

**To Reproduce**
Have Ralof follow you to Riverwood.

**Expected behavior**
He should follow you to talk to Gerdur.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**
![image](https://user-images.githubusercontent.com/11461193/83317608-2fd38800-a1eb-11ea-916d-470b6eccaee2.png)
![image](https://user-images.githubusercontent.com/11461193/83317619-3e21a400-a1eb-11ea-8f72-e07dee968a6c.png)
![image](https://user-images.githubusercontent.com/11461193/83317630-4843a280-a1eb-11ea-9554-89d7549dc213.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Skyrim AI gonna derp, without re-navmeshing the whole area I don't think this can be fixed. If someone is willing and able to tackle that let me know, but for now, I don't think it's worth the hassle.

**Comment by TwistedModding** [comment]
Maybe as a fix if others run into this issue just disable the rock and re-enable it once he's passed.
