### ISSUE TITLE
Install Error Due to Symbol in Rayek's End Filenames

### ISSUE THREAD

**Issue by Sederien** [ForgottenGlory/Living-Skyrim-2#69]
**LS Version**
LS2 Beta 1

**Describe the bug**
During install, the installer may fail due to Rayek's End having a degree symbol in one of its filenames.

**To Reproduce**
Have a Japanese version of Windows, likely. (I run in English and so does the OS, but the degree symbol named mesh in Meshes\Oaristys\Clutter\Mirror・nif has a Japanese dot when extracted rather than the Mirror°.nif Wabbajack is expecting.

**Expected behavior**
It doesn't do that. 😝 

**Additional context**
Suggest nixing mod since there were comments from you about liking the place but not being happy there's no price and it's just a free house. There's plenty of housing in the list as is and this mod likely causes issues for anyone on the other side of the globe with Asian fonts installed as part of their OS. (Assumption.)

**Comment by Sederien** [comment]
Yup. Second confirmation of the same bug from Day7 on discord. Also happened to have Japanese language in addition to English installed.

https://discordapp.com/channels/605449136870916175/688593507966779453/717195925067399240

**Comment by Sederien** [comment]
Final comment: Was requested to and reposted this report in the WJ GitHub, so it may be solved prior to needing to change if you like and want to keep Rayek's End.

**Comment by ForgottenGlory** [comment]
As far as I can tell this only affects users with Japanese as a language on their computers, there is a workaround here:
![image](https://user-images.githubusercontent.com/25124348/84573603-9326f380-ad6f-11ea-8c82-9174e5680a9b.png)

We can refer people to this fix as it comes up.
