### ISSUE TITLE
Some stuff you wanna take a look at

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim-2#70]
**LS Version**
LS 2 Beta 1

**Describe the bug**
1) Don't need to WABBAJACK_INCLUDE Cleaned ESMs, 
I think doing it this way is not okay. You're not meant to redistribute the esms. Wabbajack can detect cleaned esms and binary patch.
2) Relic Notifications - This mod doesn't fully function when LOTD Patches is merged, only things like books get notifications, armors, weapons will not produce notifications when LOTD Patches is Merged.

Small stuff
3) AGO and Experience incompatibility, Killing caused by bleedout does not grant XP
4) AddItemMenuSE is still installed (unsure if thats meant to be there)
5) Why does it snow in Whiterun?  (see screenshots)
6) QuickLoot and SkyREM Mia, Quickloot shows you npcs names on sneaking  which kinda breaks immersion (see screenshots)
7) Aldavinur in Riverwood wants to hump the giant tree (navmesh issue) (see screenshots)
8) Npcs sellling dragonbone stuff at level 1? is this intended (see screenshots)

**Screenshots**
![ScreenShot222](https://user-images.githubusercontent.com/5535758/83396713-fbe8a480-a42e-11ea-9282-b7a083dbb6cc.png)
![ScreenShot219](https://user-images.githubusercontent.com/5535758/83396739-05720c80-a42f-11ea-834b-bb5bf8b3ff41.png)
![ScreenShot220](https://user-images.githubusercontent.com/5535758/83396761-0efb7480-a42f-11ea-9535-5b483bc9b623.png)
![ScreenShot221](https://user-images.githubusercontent.com/5535758/83396771-115dce80-a42f-11ea-97ac-9e7edbbd48c8.png)
![ScreenShot224](https://user-images.githubusercontent.com/5535758/83396785-1753af80-a42f-11ea-80e4-844aff86527d.png)

**Comment by ForgottenGlory** [comment]
1) fixed Beta 2
2) fixed Beta 2
3) Intended, Kills XP is turned off by default.
4) Intended for testing purposes during the Beta
5) Need to do some digging on this one.
6) Not sure I can fix this one, but will investigate.
7) Will fix in Beta 3
8) Fixed Beta 2
