### ISSUE TITLE
[LS2 beta 1] CTD upon entering the Blue Palace

### ISSUE THREAD

**Issue by FeyKingParks** [ForgottenGlory/Living-Skyrim-2#71]
Simple, just a ctd upon loading into the blue palace. CTD occurs immediately after loading screen fade's out.
[Crash_2020_6_1_13-7-27.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4712538/Crash_2020_6_1_13-7-27.txt)

**Comment by Vyktory** [comment]
Still in Beta 2.
[Crash_2020_6_3_20-1-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4722481/Crash_2020_6_3_20-1-6.txt)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4722490/saves.zip)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
