### ISSUE TITLE
Floating Campfire 

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#72]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0 beta 1

**Describe the bug**
Floating Campfire when choosing "I am camping in the woods" option from alternate start.

**To Reproduce**
Select the option "I am camping in the woods" option from alternate start.

**Expected behavior**
Nothing should be floating in the area.

**Screenshots**

![enb2020_6_1_12_10_19](https://user-images.githubusercontent.com/62785432/83435326-a1851f00-a401-11ea-9ef5-ef57b157f821.jpg)
![enb2020_6_1_12_16_41](https://user-images.githubusercontent.com/62785432/83435412-cbd6dc80-a401-11ea-899f-e28b3b8292b3.jpg)

![enb2020_6_1_12_14_22](https://user-images.githubusercontent.com/62785432/83435336-a649d300-a401-11ea-9704-c789ac396fa7.jpg)

**Additional context**

**Comment by JaceVenture** [comment]
Already a known bug, and is being worked on. Read the announcements page more fully, please. :)
