### ISSUE TITLE
Existentialism 

### ISSUE THREAD

**Issue by LivelyDismay** [ForgottenGlory/Living-Skyrim-2#73]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
0.0.0

**Describe the bug**
My life

**To Reproduce**
Give birth to me 

**Expected behavior**
Success and prosperity 

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
plz fix

**Comment by JaceVenture** [comment]
While funny, this is not an actual issue for LS2 Beta. Please refrain from submitting false bug reports. You are in fact a wonderful person, no fix needed.
