### ISSUE TITLE
Sword floating under character after unequiping.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#74]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0 beta 1

**Describe the bug**
Items floating under character after unequiping

**To Reproduce**
EDIT*** It happens on every equip-able item as long as it is a favorite.

STEPS: Pick up any equip-able item and favorite it in your inventory. Then equip it with iequip and equip something else(ie: unarmed) the item will then float under you and follow you until equipped again or un-Favorited

**Expected behavior**
not float under character 

**Screenshots**
![ScreenShot222](https://user-images.githubusercontent.com/62785432/83437486-78668d80-a405-11ea-9e0d-412c0172484e.png)

![ScreenShot219](https://user-images.githubusercontent.com/62785432/83437542-8ae0c700-a405-11ea-92b7-31365ac90f5b.png)
![ScreenShot218](https://user-images.githubusercontent.com/62785432/83437546-8caa8a80-a405-11ea-8561-91a1f1b37ed0.png)

![ScreenShot221](https://user-images.githubusercontent.com/62785432/83437511-81575f00-a405-11ea-9c16-f249ca5fead3.png)
![ScreenShot220](https://user-images.githubusercontent.com/62785432/83437522-84eae600-a405-11ea-822a-89143a9e4446.png)

**Additional context**
No, I have not tested all the items in the game but i have tested about 6 random weapons that ive picked up and they all give the same result. Common sense would tell me it will happen for every weapon.

**Comment by TwistedModding** [comment]
Hi, an update to this, I have just found out that it also happens to npcs, although im not sure the cause of it happening to them, it might be a conflict between iequip and all geared up?

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
