### ISSUE TITLE
Most UI components broken or clunky for 3440x1440

### ISSUE THREAD

**Issue by Bocephus** [ForgottenGlory/Living-Skyrim-2#75]
**LS Version**
LS2 Beta 1

**Describe the bug**
Complete Widescreen Fix is missing several of the fixes for specific components included in this Mod List.

Better Dialogue Control Widescreen Fix
Better MessageBox Control Widescreen Fix
Experience - Widescreen Fix
Race Menu SE - Widescreen Fix
SkyHud - High Resolution Widescreen Fix
SkyUI SE - Flashing Savegames Fix - Widescreen Fix
Wider MCM Menu for SkyUI - Widescreen Fix

**To Reproduce**
Enable Complete Widescreen Fix in MO2, and launch the game.  Most menu's are clunky, save game screen tends to flicker/flash.  Some menus are not navigable via wasd, and some menu actions are not selectable with the action button.

**Expected behavior**
Save screen shouldn't flicker/flash
I should be able to navigate most menus with wasd, and select highlighted component with e

**Screenshots**
![SkyrimSE_7ghO9XGM2L](https://user-images.githubusercontent.com/1078466/83437613-ab108600-a405-11ea-819d-42af3c88e5c9.jpg)
![SkyrimSE_wmC13i1RKn](https://user-images.githubusercontent.com/1078466/83437617-ad72e000-a405-11ea-8ef0-e30ffc7c9a19.png)

**Additional context**
Happy to add additional images if needed.  As for the save flicker/flash, it does not happen every time your at the save menu, but during a game play once it starts, its there for the duration of that session.  When it does happen I'm more than happy to fire up OBS, and either stream or capture and post on youtube.

Added two screenshots. The first one is with only the included Complete Widescreen Fix enabled.  The second is with all the fixes mentioned above enabled.

**Comment by ForgottenGlory** [comment]
Fixed Beta 7, missing mods included.
