### ISSUE TITLE
Few minor bugs

### ISSUE THREAD

**Issue by Fjodik** [ForgottenGlory/Living-Skyrim-2#77]
**LS2 version Beta 1**

1.)

**Describe the bug**
When creating the new character, a Khajiit race seems to be missing SkyRem - RAE features

**To Reproduce**
Try to create a new Khajiit character

**Expected behavior**
Sneak should be 9, Lockpicking and Pickpocket should be 6, Alchemy, Archery and One-handed should be 3

2.)

**Describe the bug**
When selecting Redguard's Leki deity (Wintersun mod) the description of Tenets is not finished.

**To Reproduce**
Try to create a redguard character and select Leki deity at the beginning of the game.

**Expected behavior**
The description should be as follows:
_**Bring the Civil War to a conclusion. Make and improve weapons. Master the skills of the Warrior.**_

**Comment by ForgottenGlory** [comment]
First one is fixed Beta 3

The second one is an unfortunate side effect of the font replacer being used, I'll look but I don't know if I can fix it.
