### ISSUE TITLE
Elysium Estate floating trees

### ISSUE THREAD

**Issue by Vyktory** [ForgottenGlory/Living-Skyrim-2#78]
**LS Version**
Beta 1

**Describe the bug**
Trees are floating and blocking things in Elysium Estate outside Whiterun.

**To Reproduce**
Go to Elysium Estate and look around the gardens.

**Expected behavior**
Trees to be on the ground and not blocking things,

**Screenshots**
![ScreenShot218](https://user-images.githubusercontent.com/46320349/83461688-e1c3bc00-a458-11ea-9e2b-d7a9941beccf.png)

**Additional context**
It appears that Whiterun Borealis may be making weird edits.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
