### ISSUE TITLE
CTD from vendors that have "Blooded Aim" in inventory

### ISSUE THREAD

**Issue by JaceVenture** [ForgottenGlory/Living-Skyrim-2#79]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_6_1_13-51-53.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4713893/Crash_2020_6_1_13-51-53.txt)
[Crash_2020_6_1_17-24-52.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4713894/Crash_2020_6_1_17-24-52.txt)

[Save25_52F0F9BE_0_4B656C73696572_WhiterunWorld_000310_20200601231752_3_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4713895/Save25_52F0F9BE_0_4B656C73696572_WhiterunWorld_000310_20200601231752_3_1.zip)
In this particular save, I went to Belethor. This also happened with Lucan at an earlier point, hence the two crash logs. It's a problem with either Armors Merged or Weapons Merged. I don't remember which.

**LS Version**
Beta 1

**Describe the bug**
Every time a vendor has an item called "Blooded Aim" in their store, you will CTD when you ask what is for sale. Blooded Aim is an item with a value of one and a weight of 0.

**To Reproduce**
RNG a vendor having "Blooded Aim" in their store, CTD, repeat.

**Expected behavior**
Well, not CTDing?

**Comment by Vyktory** [comment]
Also happens on random dead bodies IME... not fun. Here's my log, but considering it's random dead bodies in my case, I'm unable to do much with saves.
[Crash_2020_6_2_9-40-1.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4713944/Crash_2020_6_2_9-40-1.txt)

**Comment by Vyktory** [comment]
I can reproduce on dead bodies by highlighting Blooded Aim. Crash logs seem to mention the 3D Model.
[Crash_2020_6_2_11-14-39.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4714213/Crash_2020_6_2_11-14-39.txt)

[Save31_5E4022BD_0_4A616D65732050616C6164696E_Tamriel_000650_20200602011435_7_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4714223/Save31_5E4022BD_0_4A616D65732050616C6164696E_Tamriel_000650_20200602011435_7_1.zip)
The nude woman slightly above mouse aim has all available items taken off the quickloot menu. Only Blooded Aim and an extra item should remain.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
