### ISSUE TITLE
Blackreach rooms broken?

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#80]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS 2

**Describe the bug**
Alternate areas besides the Necromancer spawning zone when picking Alternate life and the Skyrim outworld exit, lead to a single cell room. Leaving one of those made Blackreach into Brightreach.

**To Reproduce**
Start as Necromancer with Live another Life, tgm? Falmer spawn constantly in this room

**Expected behavior**
Entering other dwemer zones loads into a single cell blocked room, nowhere to go but to exit back out.

**Screenshots**
Did not take any

**Additional context**

**Comment by ForgottenGlory** [comment]
I'll need a screenshot with the DynDOLOD "Where Am I" screen open in one of these rooms to be able to test and fix this.

**Comment by ForgottenGlory** [comment]
No further information received, closing
