### ISSUE TITLE
Summoned minions/followers with loaded transitions.

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#81]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2

**Describe the bug**
Summoning or conjuring a follower, "Wolf pet" will not transition with you in newly loaded zones, *Moving from overworld Skyrim into Solitude ie.*

**To Reproduce**
Have a summoned/conjured creature and move to a new cell.

**Expected behavior**
Minion will not follow with you, the buff remains in the active buffs screen however it will not be with you.

**Screenshots**
None

**Additional context**

**Comment by ForgottenGlory** [comment]
Need some extra eyes on this one, unsure what's causing it. Maybe Nether's Follower Framework related? Unsure.

**Comment by Konsetsuki** [comment]
I read into it a bit and learned that the AI package for the familiar is similar to a normal wolf, so I don't think it's kitted to follow you, however I have the same issue with the avenging wraith summon and reanimated dead, the weaker spell "raise zombie"

**Comment by ForgottenGlory** [comment]
Some FormIDs for the summons that don't follow you would be helpful, just a screenshot of them selected with console please.
