### ISSUE TITLE
Lamp Post clipping through ramp

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#82]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
A Lamp Post is clipping through ramp outside whiterun

**To Reproduce**
Go outside whiterun to all the stalls right next to the sign directing you to the cities.
**Expected behavior**
no clipping lamp post (probably)

**Screenshots**
![ScreenShot235](https://user-images.githubusercontent.com/62785432/83478865-927f8a80-a45c-11ea-825d-b179afbbe2c7.png)
![ScreenShot236](https://user-images.githubusercontent.com/62785432/83478869-94494e00-a45c-11ea-97c6-94a7cc66e18e.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
