### ISSUE TITLE
"cannot access because its in use by another process"

### ISSUE THREAD

**Issue by KaiRoman** [ForgottenGlory/Living-Skyrim-2#83]
Didnt even get to load into the game, files included below

What Happened : https://i.imgur.com/vHr9Hfq.png

[Wabbajack 2020-06-01 23_09_36.log](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4714730/Wabbajack.2020-06-01.23_09_36.log)

https://i.imgur.com/ULGpUCv.png : Message found in logs

**Comment by JaceVenture** [comment]
As this is not a bug related to Living Skyrim 2, and appears to potentially have something to do with your WJ install, please direct this to the Living Skyrim and Wabbajack support channels respectively. 🙂
