### ISSUE TITLE
CTD Hunterborn-related

### ISSUE THREAD

**Issue by Sederien** [ForgottenGlory/Living-Skyrim-2#84]
**LS Version**
LS2 Beta 1

**Describe the bug**
CTD upon interacting with a wolf corpse and choosing skin or harvest after field dressing. Repeated 3x all three CTD'd.

**To Reproduce**
Kill wolf, field dress (before or after quickloot), interact once more either skin or harvest. If skin works, harvest will crash.

**Expected behavior**
Not CTD during hunterborn interaction.

**Logs x3**
[Crash_2020_6_2_22-22-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4717414/Crash_2020_6_2_22-22-47.txt)
[Crash_2020_6_2_22-27-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4717416/Crash_2020_6_2_22-27-14.txt)
[Crash_2020_6_2_22-9-48.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4717417/Crash_2020_6_2_22-9-48.txt)

**Save right in front of wolf pre-field dress**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4717424/saves.zip)

**Comment by daffodilian** [comment]
Can't replicate the CTD, but Hunterborn and Quickloot need some serious attention.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
