### ISSUE TITLE
Can see the void in bleak falls barrow(save file attached)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#85]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save50_3BBE5561_0_486F6C6C6965_BleakFallsBarrow01_000344_20200602174613_7_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4718831/Save50_3BBE5561_0_486F6C6C6965_BleakFallsBarrow01_000344_20200602174613_7_1.zip)

**LS Version**
2.0.0 beta 1

**Describe the bug**
When panning the camera a certain direction, you will see into the void in bleak falls barrow.
**To Reproduce**
Go to location provided in bleak falls barrow then pan the camera around and you will see into the void.

**Expected behavior**
No visible void

**Screenshots**
![ScreenShot245](https://user-images.githubusercontent.com/62785432/83552140-e9be4300-a4ce-11ea-9aeb-0333b4255c3a.png)
![ScreenShot246](https://user-images.githubusercontent.com/62785432/83552146-ec209d00-a4ce-11ea-9be7-7ddc34b8f3b3.png)
![ScreenShot243](https://user-images.githubusercontent.com/62785432/83552150-ed51ca00-a4ce-11ea-9442-638116cb0e0d.png)
![ScreenShot244](https://user-images.githubusercontent.com/62785432/83552154-ee82f700-a4ce-11ea-93cf-d30b1e0b5900.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
