### ISSUE TITLE
Honed Metal

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#86]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
LS2 Beta

**Describe the bug**
Every time I pay a smith to create me a weapon or armor and I go to pick them up from the smith who tells me they’re ready but nothing appears for me to take.

**To Reproduce**
Purchase an item from a smith via Honed Metal and wait the appropriate amount of time. 

To receive you new equipment after the correct amount of time. 

**Additional context**
Not sure if this could cause an issue but I did console in the gold and stood outside the smith and waited multiple days before a courier arrived and told me my gear was ready. This is the second time it happened on this save and if you talk to Belrand next to you when loading in he says he has the gear ready. 
 
Sorry I can't upload save directory to Github so I made a Google drive upload for the ess and Skse file.

https://drive.google.com/file/d/1odtcxeyGzKOq9V62obnzxnvEmZvqyC3S/view?usp=sharing

https://drive.google.com/file/d/1jUPL2OvKCLnro-X3-KszmlQQJbunXRuD/view?usp=sharing

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
