### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by WhoIsDamir** [ForgottenGlory/Living-Skyrim-2#87]
**LS Version**
LS 2 Beta

1.  **Describe the bug**
Animation problem with war axe/mace and shield. War axe/mace is on the right hip but sheathing/unsheathing animation plays as if it's on the left.

**To Reproduce**
Equip shield and war axe/mace, sheath and unsheath couple of times

**Expected behavior**
Correct animation

**Video showcase**
https://www.youtube.com/watch?v=r2vDT_LtiNc

2.  **Describe the bug**
Field Guard Shield stays both on arm and back

**To Reproduce**
Equip Field Guard Shield

**Expected behavior**
Correct shield position

**Screenshots**
![ScreenShot215](https://user-images.githubusercontent.com/49757615/83562406-53743680-a53b-11ea-8b72-898d13ecc5c8.png)
![ScreenShot216](https://user-images.githubusercontent.com/49757615/83562411-553dfa00-a53b-11ea-9886-475b3d86b477.png)

**Comment by ForgottenGlory** [comment]
I've not been able to replicate this.
