### ISSUE TITLE
NPC woodcutting bug. (save file attached)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#88]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Save65_3BBE5561_0_486F6C6C6965_WhiterunWorld_000458_20200602213107_9_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4719818/Save65_3BBE5561_0_486F6C6C6965_WhiterunWorld_000458_20200602213107_9_1.zip)
**LS Version**
2.0.0 beta 1

**Describe the bug**
NPC is wood cutting extremely fast and has chopped wood stuck on his ax.

**To Reproduce**
Not sure if others will be able to replicate but all I did was load into whiterun and I noticed some stuck firewood on his ax and he was chopping very fast. Save file is attached

**Expected behavior**
Normal chopping speed and no stuck firewood.

**Screenshots**
![ScreenShot250](https://user-images.githubusercontent.com/62785432/83572342-04a0af80-a4ef-11ea-8ee0-f8c0d64f1899.png)
![ScreenShot251](https://user-images.githubusercontent.com/62785432/83572350-07030980-a4ef-11ea-9ff2-9082683b72c1.png)

**Additional context**

**Comment by Sederien** [comment]
I can also chime in that the Khajiit caravan in Whiterun also shows faster than expected chopping animation. Seems to be a generic issue with this particular animation speed?

**Comment by ForgottenGlory** [comment]
The animation speed is caused by the mod Faster Wood Chopping, so it's intended. The wood being stuck on the axe is not intended however. I'll investigate.

**Comment by daffodilian** [comment]
The animation is meant to be faster. Mainly for the character to be able to chop faster, but that means everyone will have the animation

**Comment by ForgottenGlory** [comment]
I haven't been able to replicate the wood stuck on axe issue
