### ISSUE TITLE
Bad  shield 

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-2#89]
![ScreenShot218](https://user-images.githubusercontent.com/66355096/83658908-7416ad80-a588-11ea-99f9-e20c241e54e2.png)
![SkyrimSE 2020-06-03 02-59-51](https://user-images.githubusercontent.com/66355096/83611301-67716580-a546-11ea-85ce-a76bb19f9cdb.png)
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Living Skyrim 2.0.0 Beta 2

**Describe the bug**
the shield is all purple

**To Reproduce**
do alternate start vampire probably random tho

**Expected behavior**
for the shield not to be purple 

If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
![SkyrimSE 2020-06-03 02-28-34](https://user-images.githubusercontent.com/66355096/83609155-7a366b00-a543-11ea-982e-43391502ef20.png)
seems to only appear like that when favorited

**Comment by JaceVenture** [comment]
Please provide the FormID for the shield. To do so, with the shield in front of you, open the console, click on the shield, and take a screenshot of the shield.

**Comment by KNGLogan** [comment]
did it

**Comment by Ajexais** [comment]
I also have this issue, strangely, it is only purple when it is NOT equipped. When you use it in combat it is fully textured as normal

Somthing todo with a missing mesh for the back equip maybe?

**Comment by tHiNgXX9** [comment]
Yes seems to only happen on their backs.
![20200603174428_1](https://user-images.githubusercontent.com/62521502/83703163-8bbf5780-a5c3-11ea-923c-f091942470bd.jpg)

**Comment by ForgottenGlory** [comment]
I'm unsure what's causing this, everything looks correct for the shield in xEdit.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
