### ISSUE TITLE
Waiting/Sleeping repeatedly CTD

### ISSUE THREAD

**Issue by CentralSmith** [ForgottenGlory/Living-Skyrim-2#90]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.
[Crash_2020_6_3_9-16-21.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4724150/Crash_2020_6_3_9-16-21.txt)
[Crash_2020_6_3_9-25-58.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4724151/Crash_2020_6_3_9-25-58.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta

**Describe the bug**
When waiting repeatedly/for long periods (in this case, waiting for the College quest to continue), a CTD will occur.

**To Reproduce**
Sleep/Wait for 24 hours more than 2 times.

**Expected behavior**
Waiting completing successfully

**Screenshots**
N/A

**Additional context**
N/A

**Comment by daffodilian** [comment]
Did you update to Beta 2?

**Comment by CentralSmith** [comment]
Yes, this is the most recent beta.

**Comment by daffodilian** [comment]
![image](https://user-images.githubusercontent.com/63564258/83656195-3d8f6180-a58d-11ea-82f5-449798be148a.png)
See rule 11 in discord. And please, absolutely do not post an issue here if you have extra mods installed.
