### ISSUE TITLE
FLOATING TREE IN IVARSTEAD i am ultimate tree finder glory >:)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#91]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1 

**Describe the bug**
floating tree

**To Reproduce**
go to ivarstead look at tree

**Expected behavior**
no floating tree

**Screenshots**
![ScreenShot255](https://user-images.githubusercontent.com/62785432/83690337-2fa20680-a5b6-11ea-98f1-791aa7826c57.png)
![ScreenShot256](https://user-images.githubusercontent.com/62785432/83690344-329cf700-a5b6-11ea-936e-f5d5797d9e77.png)
![ScreenShot257](https://user-images.githubusercontent.com/62785432/83690348-34ff5100-a5b6-11ea-944f-5c8dd9124f12.png)

**Additional context**
tree

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
