### ISSUE TITLE
micmou's shennanigans in Beta 2

### ISSUE THREAD

**Issue by micmou** [ForgottenGlory/Living-Skyrim-2#92]
Here are the images from todays play session sadly I forgot we can grab console info.

The terrain between the danty sload and the solitude lighthouse has some misc terrain problems.
https://imgur.com/7nh4qfW

Auryen from LOTD has some black voids around his neck line and costume
https://imgur.com/4G2v1Xf

And very sorry about not grabbing the console info on this one but bandoits seems to have weird loot
https://imgur.com/zQI7MXV

**Comment by ForgottenGlory** [comment]
Define "weird loot" please.

**Comment by micmou** [comment]
Dragon Carved gauntlets and Field Guard armor. I only played for about a hour today I have to go do some things. But tommorow I will have more time to play the game and as Volk told me to do it will include console info shots aswell

So as to not fill a bunch of issues I will document what I come across in this issue in my coming play sessions.

**Comment by ForgottenGlory** [comment]
The items in the loot screenshot posted are correct, these items have been rebalanced and are on the leveled lists for bandits so it's fine. Nothing is changing Auryen so most like that's either intended or a possible bug with LOTD, which I can't fix.
