### ISSUE TITLE
CTD in mountains between Riverwood and Whiterun

### ISSUE THREAD

**Issue by WhoIsDamir** [ForgottenGlory/Living-Skyrim-2#93]
**LS Version**
LS2 Beta 2

**Crash logs**
[Crash_2020_6_4_3-23-13.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4726314/Crash_2020_6_4_3-23-13.txt)
[Crash_2020_6_4_4-27-2.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4726511/Crash_2020_6_4_4-27-2.txt)

**Describe the bug**
Repeatable CTD in mountains between Riverwood and Whiterun

**To Reproduce**
Run around the area provided in screenshot

**Expected behavior**
No CTD

**Screenshots**
![ScreenShot215](https://user-images.githubusercontent.com/49757615/83691419-ef717100-a613-11ea-901c-9abf92704f63.png)

**Comment by ForgottenGlory** [comment]
Seems related to 000B6336, need some testers on this one

**Comment by daffodilian** [comment]
Can you upload your saves? I have been actively trying to replicate this CTD but can't for the life of me. I've been running around the area and the surrounding cells spawning larger than normal amounts of NPCs. I've visited every instance of 000b6336 in those cells, and the shrine mentioned in the crash log.

**Comment by WhoIsDamir** [comment]
Those crashes were in playthrough with a bit tweaked mcm settings (LS2 mcm config as a base). So I decided to start a new game, follow LS2 mcm settings to the letter but still got a CTD.

**Tweaked mcm saves**
[tweaked mcm saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4735748/tweaked.mcm.saves.zip)

**LS2 mcm saves**
[LS2 mcm saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4735758/LS2.mcm.saves.zip)

**New CTD log**
[Crash_2020_6_5_17-10-1.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/4735760/Crash_2020_6_5_17-10-1.txt)

CTD usually happens if you run from this place towards Whiterun, but sometimes you have to run around a bit to get it

![ScreenShot218](https://user-images.githubusercontent.com/49757615/83871643-3cf3f800-a752-11ea-9fae-bb7687929fd0.png)
![ScreenShot220](https://user-images.githubusercontent.com/49757615/83871645-3e252500-a752-11ea-85de-391d496cdb28.png)

**Comment by WhoIsDamir** [comment]
In case if it has something to do with PC here are my specs

- Ryzen 5 3600
- RTX 2070 Super
- 16 GB RAM (3800MHz CL 16)
- 1 TB NVMe SSD

**Comment by ForgottenGlory** [comment]
I'm not able to replicate this under any circumstances, something may be wrong with your install. Try again after Beta 3 releases.
