### ISSUE TITLE
Vanilla textures at sky haven temple.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#94]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
Vanilla textures at the blood sealed doorway

**To Reproduce**
go to skyhaven temple and look at doorway

**Expected behavior**
no vanilla textures

**Screenshots**
![ScreenShot259](https://user-images.githubusercontent.com/62785432/83698500-384f0880-a5c7-11ea-966a-e98fe78a0a47.png)
![ScreenShot260](https://user-images.githubusercontent.com/62785432/83698506-3b49f900-a5c7-11ea-9387-d4ec5b9eb1f5.png)
![ScreenShot261](https://user-images.githubusercontent.com/62785432/83698510-3c7b2600-a5c7-11ea-882f-1ec99222f07f.png)
![ScreenShot258](https://user-images.githubusercontent.com/62785432/83698513-3dac5300-a5c7-11ea-89da-0c645999ca60.png)

**Additional context**
Call me Mr. Bug Finder

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
