### ISSUE TITLE
Low quality greybeard robes. (Vanilla maybe?)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#95]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
Vanilla looking textures on greybeard robes

**To Reproduce**
Find greybeards and look at robes

**Expected behavior**
no vanilla textures

**Screenshots**
![ScreenShot262](https://user-images.githubusercontent.com/62785432/83699380-7f3dfd80-a5c9-11ea-9df2-796a942e98d6.png)

**Additional context**
Bug man to the rescue

**Comment by ForgottenGlory** [comment]
A quick search on Nexus doesn't reveal any acceptable retextures for these, I'm open to suggestions.

**Comment by Konsetsuki** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/8731

Maybe just replace them?

**Comment by TwistedModding** [comment]
> https://www.nexusmods.com/skyrimspecialedition/mods/8731
> 
> Maybe just replace them?

Those still look very low quality, I'm gonna do a little digging.

**Comment by tHiNgXX9** [comment]
not sure if these would be something you like FG, or if they would work since they're a Skyrim and not an SSE retexture. 

https://www.nexusmods.com/skyrim/mods/45280/

**Comment by ForgottenGlory** [comment]
Until there's a good vanilla Greybeard Robe retexture I think we'll just have to deal with this unfortunately.
