### ISSUE TITLE
Overbalanced mace

### ISSUE THREAD

**Issue by Konsetsuki** [ForgottenGlory/Living-Skyrim-2#97]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Beta 2
**Describe the bug**
Over tuned mace, sells for a lot and has decent stats for the crafting cost.
However tempering it costs Ebony Ingots.

**To Reproduce**
Smith the Skullcrusher 3 Iron ingot and 2 leather strips.

**Expected behavior**

**Screenshots**
![ScreenShot219](https://user-images.githubusercontent.com/13601605/83700352-75ad9900-a5bb-11ea-9db1-275406c2c64f.png)
![ScreenShot218](https://user-images.githubusercontent.com/13601605/83700358-78a88980-a5bb-11ea-86fa-9aaf72d31704.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
