### ISSUE TITLE
Dark Face bug on ancano

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-2#98]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
2.0.0 beta 1

**Describe the bug**
Dark face bug on ancano

**To Reproduce**
Go to college of winterhold

**Expected behavior**
No darkface bug.

**Screenshots**
![ScreenShot264](https://user-images.githubusercontent.com/62785432/83700641-fde86a00-a5cc-11ea-8083-a0bf25e08079.png)
![ScreenShot263](https://user-images.githubusercontent.com/62785432/83700645-ffb22d80-a5cc-11ea-8d62-3174704f8c42.png)

**Additional context**
His tan is wonderful, stop bullying him.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
