### ISSUE TITLE
Ainethatch BFB

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim-2#99]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

**LS Version**
Newest Beta Release
**Describe the bug**
BFB on NPC in Karthwasten

**To Reproduce**
Walk into Karthwasten and see Ainethatch

**Expected behavior**
No BFB on NPC
![20200603174354_1](https://user-images.githubusercontent.com/62521502/83702860-bbba2b00-a5c2-11ea-8314-29b4ae5113b9.jpg)
![20200603174357_1](https://user-images.githubusercontent.com/62521502/83702866-c07edf00-a5c2-11ea-8301-79a83d8de776.jpg)

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.**

**Additional context**
No mods added

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
